// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.0 (commit d220349adb7af7eefa810eb08a185609356b83f6).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed partial class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(ActiveConsumableEffect = new(conn));
            AddTable(AllEnchantments = new(conn));
            AddTable(AllItems = new(conn));
            AddTable(AllTextures = new(conn));
            AddTable(BaseAdjacencyRule = new(conn));
            AddTable(BiomeDef = new(conn));
            AddTable(BiomeRegion = new(conn));
            AddTable(BiomeRegionDef = new(conn));
            AddTable(BuildingTile = new(conn));
            AddTable(BulletPatternEvent = new(conn));
            AddTable(DecorGroundRule = new(conn));
            AddTable(Enchantment = new(conn));
            AddTable(Enemy = new(conn));
            AddTable(EnemyAttack = new(conn));
            AddTable(EnemyBehavior = new(conn));
            AddTable(EnemyPhases = new(conn));
            AddTable(EnemySequenceStep = new(conn));
            AddTable(EnemyTemplate = new(conn));
            AddTable(EnemyTemplates = new(conn));
            AddTable(HexDecor = new(conn));
            AddTable(Item = new(conn));
            AddTable(LayeringRule = new(conn));
            AddTable(LocalLobbyPlayer = new(conn));
            AddTable(LocalPlayer = new(conn));
            AddTable(LocalPlayerActiveProfile = new(conn));
            AddTable(LocalPlayerData = new(conn));
            AddTable(LocalPlayerInventory = new(conn));
            AddTable(LocalPlayerPosition = new(conn));
            AddTable(LocalPlayerProfiles = new(conn));
            AddTable(LocalPlayerStats = new(conn));
            AddTable(LoggedInPlayer = new(conn));
            AddTable(LootDrop = new(conn));
            AddTable(MapConfig = new(conn));
            AddTable(MovementDef = new(conn));
            AddTable(MultiStepDef = new(conn));
            AddTable(NearbyEnemies = new(conn));
            AddTable(NearbyHexDecor = new(conn));
            AddTable(NearbyLootDrops = new(conn));
            AddTable(NearbyRemotePlayers = new(conn));
            AddTable(NearbyRemotePlayersProfiles = new(conn));
            AddTable(NearbyTerrainTiles = new(conn));
            AddTable(OverlayAdjacencyRule = new(conn));
            AddTable(PlayerChunk = new(conn));
            AddTable(PlayerData = new(conn));
            AddTable(PlayerInventory = new(conn));
            AddTable(PlayerPosition = new(conn));
            AddTable(PlayerProfile = new(conn));
            AddTable(PlayerStats = new(conn));
            AddTable(RepeatStepDef = new(conn));
            AddTable(RepeatStepInstance = new(conn));
            AddTable(SingleStepDef = new(conn));
            AddTable(TextureEntry = new(conn));
            AddTable(TriangleTile = new(conn));
            AddTable(WorldDef = new(conn));
        }
    }


    public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures>
    {
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
    }

    public sealed class EventContext : IEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;

        /// <summary>
        /// The event that caused this callback to run.
        /// </summary>
        public readonly Event<Reducer> Event;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to procedures defined by the module.
        ///
        /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
        /// with a callback for when the procedure completes and returns a value.
        /// </summary>
        public RemoteProcedures Procedures => conn.Procedures;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;
        /// <summary>
        /// Register a callback to be called when a reducer with no handler returns an error.
        /// </summary>
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal EventContext(DbConnection conn, Event<Reducer> Event)
        {
            this.conn = conn;
            this.Event = Event;
        }
    }

    public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        /// <summary>
        /// The reducer event that caused this callback to run.
        /// </summary>
        public readonly ReducerEvent<Reducer> Event;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to procedures defined by the module.
        ///
        /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
        /// with a callback for when the procedure completes and returns a value.
        /// </summary>
        public RemoteProcedures Procedures => conn.Procedures;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;
        /// <summary>
        /// Register a callback to be called when a reducer with no handler returns an error.
        /// </summary>
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
        {
            this.conn = conn;
            Event = reducerEvent;
        }
    }

    public sealed class ErrorContext : IErrorContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        /// <summary>
        /// The <c>Exception</c> that caused this error callback to be run.
        /// </summary>
        public readonly Exception Event;
        Exception IErrorContext.Event
        {
            get
            {
                return Event;
            }
        }

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to procedures defined by the module.
        ///
        /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
        /// with a callback for when the procedure completes and returns a value.
        /// </summary>
        public RemoteProcedures Procedures => conn.Procedures;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;
        /// <summary>
        /// Register a callback to be called when a reducer with no handler returns an error.
        /// </summary>
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ErrorContext(DbConnection conn, Exception error)
        {
            this.conn = conn;
            Event = error;
        }
    }

    public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to procedures defined by the module.
        ///
        /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
        /// with a callback for when the procedure completes and returns a value.
        /// </summary>
        public RemoteProcedures Procedures => conn.Procedures;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;
        /// <summary>
        /// Register a callback to be called when a reducer with no handler returns an error.
        /// </summary>
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal SubscriptionEventContext(DbConnection conn)
        {
            this.conn = conn;
        }
    }

    public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        /// <summary>
        /// The procedure event that caused this callback to run.
        /// </summary>
        public readonly ProcedureEvent Event;

        /// <summary>
        /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
        ///
        /// The returned <c>DbView</c> will have a method to access each table defined by the module.
        /// </summary>
        public RemoteTables Db => conn.Db;
        /// <summary>
        /// Access to reducers defined by the module.
        ///
        /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
        /// plus methods for adding and removing callbacks on each of those reducers.
        /// </summary>
        public RemoteReducers Reducers => conn.Reducers;
        /// <summary>
        /// Access to procedures defined by the module.
        ///
        /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
        /// with a callback for when the procedure completes and returns a value.
        /// </summary>
        public RemoteProcedures Procedures => conn.Procedures;
        /// <summary>
        /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
        /// </summary>
        public bool IsActive => conn.IsActive;
        /// <summary>
        /// Close the connection.
        ///
        /// Throws an error if the connection is already closed.
        /// </summary>
        public void Disconnect()
        {
            conn.Disconnect();
        }
        /// <summary>
        /// Start building a subscription.
        /// </summary>
        /// <returns>A builder-pattern constructor for subscribing to queries,
        /// causing matching rows to be replicated into the client cache.</returns>
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        /// <summary>
        /// Get the <c>Identity</c> of this connection.
        ///
        /// This method returns null if the connection was constructed anonymously
        /// and we have not yet received our newly-generated <c>Identity</c> from the host.
        /// </summary>
        public Identity? Identity => conn.Identity;
        /// <summary>
        /// Get this connection's <c>ConnectionId</c>.
        /// </summary>
        public ConnectionId ConnectionId => conn.ConnectionId;
        /// <summary>
        /// Register a callback to be called when a reducer with no handler returns an error.
        /// </summary>
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
        {
            this.conn = conn;
            this.Event = Event;
        }
    }

    /// <summary>
    /// Builder-pattern constructor for subscription queries.
    /// </summary>
    public sealed class SubscriptionBuilder
    {
        private readonly IDbConnection conn;

        private event Action<SubscriptionEventContext>? Applied;
        private event Action<ErrorContext, Exception>? Error;

        /// <summary>
        /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
        /// </summary>
        public SubscriptionBuilder(IDbConnection conn)
        {
            this.conn = conn;
        }

        /// <summary>
        /// Register a callback to run when the subscription is applied.
        /// </summary>
        public SubscriptionBuilder OnApplied(
            Action<SubscriptionEventContext> callback
        )
        {
            Applied += callback;
            return this;
        }

        /// <summary>
        /// Register a callback to run when the subscription fails.
        ///
        /// Note that this callback may run either when attempting to apply the subscription,
        /// in which case <c>Self::on_applied</c> will never run,
        /// or later during the subscription's lifetime if the module's interface changes,
        /// in which case <c>Self::on_applied</c> may have already run.
        /// </summary>
        public SubscriptionBuilder OnError(
            Action<ErrorContext, Exception> callback
        )
        {
            Error += callback;
            return this;
        }

        /// <summary>
        /// Add a typed query to this subscription.
        ///
        /// This is the entry point for building subscriptions without writing SQL by hand.
        /// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
        /// </summary>
        public TypedSubscriptionBuilder AddQuery<TRow>(
            Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
        )
        {
            var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
            return typed.AddQuery(build);
        }

        /// <summary>
        /// Subscribe to the following SQL queries.
        ///
        /// This method returns immediately, with the data not yet added to the DbConnection.
        /// The provided callbacks will be invoked once the data is returned from the remote server.
        /// Data from all the provided queries will be returned at the same time.
        ///
        /// See the SpacetimeDB SQL docs for more information on SQL syntax:
        /// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
        /// </summary>
        public SubscriptionHandle Subscribe(
            string[] querySqls
        ) => new(conn, Applied, Error, querySqls);

        /// <summary>
        /// Subscribe to all rows from all tables.
        ///
        /// This method is intended as a convenience
        /// for applications where client-side memory use and network bandwidth are not concerns.
        /// Applications where these resources are a constraint
        /// should register more precise queries via <c>Self.Subscribe</c>
        /// in order to replicate only the subset of data which the client needs to function.
        ///
        /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
        /// A connection may either <c>Self.Subscribe</c> to particular queries,
        /// or <c>Self.SubscribeToAllTables</c>, but not both.
        /// Attempting to call <c>Self.Subscribe</c>
        /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
        /// or vice versa, may misbehave in any number of ways,
        /// including dropping subscriptions, corrupting the client cache, or panicking.
        /// </summary>
        public SubscriptionHandle SubscribeToAllTables() =>
            new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
    }

    public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext>
    {
        /// <summary>
        /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
        /// </summary>
        public SubscriptionHandle(
            IDbConnection conn,
            Action<SubscriptionEventContext>? onApplied,
            Action<ErrorContext, Exception>? onError,
            string[] querySqls
        ) : base(conn, onApplied, onError, querySqls)
        { }
    }

    public sealed class QueryBuilder
    {
        public From From { get; } = new();

        internal static string[] AllTablesSqlQueries() => new string[]
        {
            new QueryBuilder().From.ActiveConsumableEffect().ToSql(),
            new QueryBuilder().From.AllEnchantments().ToSql(),
            new QueryBuilder().From.AllItems().ToSql(),
            new QueryBuilder().From.AllTextures().ToSql(),
            new QueryBuilder().From.BaseAdjacencyRule().ToSql(),
            new QueryBuilder().From.BiomeDef().ToSql(),
            new QueryBuilder().From.BiomeRegion().ToSql(),
            new QueryBuilder().From.BiomeRegionDef().ToSql(),
            new QueryBuilder().From.BuildingTile().ToSql(),
            new QueryBuilder().From.BulletPatternEvent().ToSql(),
            new QueryBuilder().From.DecorGroundRule().ToSql(),
            new QueryBuilder().From.Enchantment().ToSql(),
            new QueryBuilder().From.Enemy().ToSql(),
            new QueryBuilder().From.EnemyAttack().ToSql(),
            new QueryBuilder().From.EnemyBehavior().ToSql(),
            new QueryBuilder().From.EnemyPhases().ToSql(),
            new QueryBuilder().From.EnemySequenceStep().ToSql(),
            new QueryBuilder().From.EnemyTemplate().ToSql(),
            new QueryBuilder().From.EnemyTemplates().ToSql(),
            new QueryBuilder().From.HexDecor().ToSql(),
            new QueryBuilder().From.Item().ToSql(),
            new QueryBuilder().From.LayeringRule().ToSql(),
            new QueryBuilder().From.LocalLobbyPlayer().ToSql(),
            new QueryBuilder().From.LocalPlayer().ToSql(),
            new QueryBuilder().From.LocalPlayerActiveProfile().ToSql(),
            new QueryBuilder().From.LocalPlayerData().ToSql(),
            new QueryBuilder().From.LocalPlayerInventory().ToSql(),
            new QueryBuilder().From.LocalPlayerPosition().ToSql(),
            new QueryBuilder().From.LocalPlayerProfiles().ToSql(),
            new QueryBuilder().From.LocalPlayerStats().ToSql(),
            new QueryBuilder().From.LoggedInPlayer().ToSql(),
            new QueryBuilder().From.LootDrop().ToSql(),
            new QueryBuilder().From.MapConfig().ToSql(),
            new QueryBuilder().From.MovementDef().ToSql(),
            new QueryBuilder().From.MultiStepDef().ToSql(),
            new QueryBuilder().From.NearbyEnemies().ToSql(),
            new QueryBuilder().From.NearbyHexDecor().ToSql(),
            new QueryBuilder().From.NearbyLootDrops().ToSql(),
            new QueryBuilder().From.NearbyRemotePlayers().ToSql(),
            new QueryBuilder().From.NearbyRemotePlayersProfiles().ToSql(),
            new QueryBuilder().From.NearbyTerrainTiles().ToSql(),
            new QueryBuilder().From.OverlayAdjacencyRule().ToSql(),
            new QueryBuilder().From.PlayerChunk().ToSql(),
            new QueryBuilder().From.PlayerData().ToSql(),
            new QueryBuilder().From.PlayerInventory().ToSql(),
            new QueryBuilder().From.PlayerPosition().ToSql(),
            new QueryBuilder().From.PlayerProfile().ToSql(),
            new QueryBuilder().From.PlayerStats().ToSql(),
            new QueryBuilder().From.RepeatStepDef().ToSql(),
            new QueryBuilder().From.RepeatStepInstance().ToSql(),
            new QueryBuilder().From.SingleStepDef().ToSql(),
            new QueryBuilder().From.TextureEntry().ToSql(),
            new QueryBuilder().From.TriangleTile().ToSql(),
            new QueryBuilder().From.WorldDef().ToSql(),
        }
        ;
    }

    public sealed class From
    {
        public global::SpacetimeDB.Table<ActiveConsumableEffect, ActiveConsumableEffectCols, ActiveConsumableEffectIxCols> ActiveConsumableEffect() => new("active_consumable_effect", new ActiveConsumableEffectCols("active_consumable_effect"), new ActiveConsumableEffectIxCols("active_consumable_effect"));
        public global::SpacetimeDB.Table<Enchantment, AllEnchantmentsCols, AllEnchantmentsIxCols> AllEnchantments() => new("all_enchantments", new AllEnchantmentsCols("all_enchantments"), new AllEnchantmentsIxCols("all_enchantments"));
        public global::SpacetimeDB.Table<Item, AllItemsCols, AllItemsIxCols> AllItems() => new("all_items", new AllItemsCols("all_items"), new AllItemsIxCols("all_items"));
        public global::SpacetimeDB.Table<TextureEntry, AllTexturesCols, AllTexturesIxCols> AllTextures() => new("all_textures", new AllTexturesCols("all_textures"), new AllTexturesIxCols("all_textures"));
        public global::SpacetimeDB.Table<BaseAdjacencyRule, BaseAdjacencyRuleCols, BaseAdjacencyRuleIxCols> BaseAdjacencyRule() => new("base_adjacency_rule", new BaseAdjacencyRuleCols("base_adjacency_rule"), new BaseAdjacencyRuleIxCols("base_adjacency_rule"));
        public global::SpacetimeDB.Table<BiomeDef, BiomeDefCols, BiomeDefIxCols> BiomeDef() => new("biome_def", new BiomeDefCols("biome_def"), new BiomeDefIxCols("biome_def"));
        public global::SpacetimeDB.Table<BiomeRegion, BiomeRegionCols, BiomeRegionIxCols> BiomeRegion() => new("biome_region", new BiomeRegionCols("biome_region"), new BiomeRegionIxCols("biome_region"));
        public global::SpacetimeDB.Table<BiomeRegionDef, BiomeRegionDefCols, BiomeRegionDefIxCols> BiomeRegionDef() => new("biome_region_def", new BiomeRegionDefCols("biome_region_def"), new BiomeRegionDefIxCols("biome_region_def"));
        public global::SpacetimeDB.Table<BuildingTile, BuildingTileCols, BuildingTileIxCols> BuildingTile() => new("building_tile", new BuildingTileCols("building_tile"), new BuildingTileIxCols("building_tile"));
        public global::SpacetimeDB.Table<BulletPatternEvent, BulletPatternEventCols, BulletPatternEventIxCols> BulletPatternEvent() => new("bullet_pattern_event", new BulletPatternEventCols("bullet_pattern_event"), new BulletPatternEventIxCols("bullet_pattern_event"));
        public global::SpacetimeDB.Table<DecorGroundRule, DecorGroundRuleCols, DecorGroundRuleIxCols> DecorGroundRule() => new("decor_ground_rule", new DecorGroundRuleCols("decor_ground_rule"), new DecorGroundRuleIxCols("decor_ground_rule"));
        public global::SpacetimeDB.Table<Enchantment, EnchantmentCols, EnchantmentIxCols> Enchantment() => new("enchantment", new EnchantmentCols("enchantment"), new EnchantmentIxCols("enchantment"));
        public global::SpacetimeDB.Table<Enemy, EnemyCols, EnemyIxCols> Enemy() => new("enemy", new EnemyCols("enemy"), new EnemyIxCols("enemy"));
        public global::SpacetimeDB.Table<EnemyAttack, EnemyAttackCols, EnemyAttackIxCols> EnemyAttack() => new("enemy_attack", new EnemyAttackCols("enemy_attack"), new EnemyAttackIxCols("enemy_attack"));
        public global::SpacetimeDB.Table<EnemyBehavior, EnemyBehaviorCols, EnemyBehaviorIxCols> EnemyBehavior() => new("enemy_behavior", new EnemyBehaviorCols("enemy_behavior"), new EnemyBehaviorIxCols("enemy_behavior"));
        public global::SpacetimeDB.Table<EnemyPhase, EnemyPhasesCols, EnemyPhasesIxCols> EnemyPhases() => new("enemy_phases", new EnemyPhasesCols("enemy_phases"), new EnemyPhasesIxCols("enemy_phases"));
        public global::SpacetimeDB.Table<EnemySequenceStep, EnemySequenceStepCols, EnemySequenceStepIxCols> EnemySequenceStep() => new("enemy_sequence_step", new EnemySequenceStepCols("enemy_sequence_step"), new EnemySequenceStepIxCols("enemy_sequence_step"));
        public global::SpacetimeDB.Table<EnemyTemplate, EnemyTemplateCols, EnemyTemplateIxCols> EnemyTemplate() => new("enemy_template", new EnemyTemplateCols("enemy_template"), new EnemyTemplateIxCols("enemy_template"));
        public global::SpacetimeDB.Table<EnemyTemplate, EnemyTemplatesCols, EnemyTemplatesIxCols> EnemyTemplates() => new("enemy_templates", new EnemyTemplatesCols("enemy_templates"), new EnemyTemplatesIxCols("enemy_templates"));
        public global::SpacetimeDB.Table<HexDecor, HexDecorCols, HexDecorIxCols> HexDecor() => new("hex_decor", new HexDecorCols("hex_decor"), new HexDecorIxCols("hex_decor"));
        public global::SpacetimeDB.Table<Item, ItemCols, ItemIxCols> Item() => new("item", new ItemCols("item"), new ItemIxCols("item"));
        public global::SpacetimeDB.Table<LayeringRule, LayeringRuleCols, LayeringRuleIxCols> LayeringRule() => new("layering_rule", new LayeringRuleCols("layering_rule"), new LayeringRuleIxCols("layering_rule"));
        public global::SpacetimeDB.Table<LoggedOutPlayer, LocalLobbyPlayerCols, LocalLobbyPlayerIxCols> LocalLobbyPlayer() => new("local_lobby_player", new LocalLobbyPlayerCols("local_lobby_player"), new LocalLobbyPlayerIxCols("local_lobby_player"));
        public global::SpacetimeDB.Table<LoggedInPlayer, LocalPlayerCols, LocalPlayerIxCols> LocalPlayer() => new("local_player", new LocalPlayerCols("local_player"), new LocalPlayerIxCols("local_player"));
        public global::SpacetimeDB.Table<PlayerProfile, LocalPlayerActiveProfileCols, LocalPlayerActiveProfileIxCols> LocalPlayerActiveProfile() => new("local_player_active_profile", new LocalPlayerActiveProfileCols("local_player_active_profile"), new LocalPlayerActiveProfileIxCols("local_player_active_profile"));
        public global::SpacetimeDB.Table<PlayerData, LocalPlayerDataCols, LocalPlayerDataIxCols> LocalPlayerData() => new("local_player_data", new LocalPlayerDataCols("local_player_data"), new LocalPlayerDataIxCols("local_player_data"));
        public global::SpacetimeDB.Table<PlayerInventory, LocalPlayerInventoryCols, LocalPlayerInventoryIxCols> LocalPlayerInventory() => new("local_player_inventory", new LocalPlayerInventoryCols("local_player_inventory"), new LocalPlayerInventoryIxCols("local_player_inventory"));
        public global::SpacetimeDB.Table<PlayerPosition, LocalPlayerPositionCols, LocalPlayerPositionIxCols> LocalPlayerPosition() => new("local_player_position", new LocalPlayerPositionCols("local_player_position"), new LocalPlayerPositionIxCols("local_player_position"));
        public global::SpacetimeDB.Table<PlayerProfile, LocalPlayerProfilesCols, LocalPlayerProfilesIxCols> LocalPlayerProfiles() => new("local_player_profiles", new LocalPlayerProfilesCols("local_player_profiles"), new LocalPlayerProfilesIxCols("local_player_profiles"));
        public global::SpacetimeDB.Table<PlayerStats, LocalPlayerStatsCols, LocalPlayerStatsIxCols> LocalPlayerStats() => new("local_player_stats", new LocalPlayerStatsCols("local_player_stats"), new LocalPlayerStatsIxCols("local_player_stats"));
        public global::SpacetimeDB.Table<LoggedInPlayer, LoggedInPlayerCols, LoggedInPlayerIxCols> LoggedInPlayer() => new("logged_in_player", new LoggedInPlayerCols("logged_in_player"), new LoggedInPlayerIxCols("logged_in_player"));
        public global::SpacetimeDB.Table<LootDrop, LootDropCols, LootDropIxCols> LootDrop() => new("loot_drop", new LootDropCols("loot_drop"), new LootDropIxCols("loot_drop"));
        public global::SpacetimeDB.Table<MapConfig, MapConfigCols, MapConfigIxCols> MapConfig() => new("map_config", new MapConfigCols("map_config"), new MapConfigIxCols("map_config"));
        public global::SpacetimeDB.Table<MovementDef, MovementDefCols, MovementDefIxCols> MovementDef() => new("movement_def", new MovementDefCols("movement_def"), new MovementDefIxCols("movement_def"));
        public global::SpacetimeDB.Table<MultiStepDef, MultiStepDefCols, MultiStepDefIxCols> MultiStepDef() => new("multi_step_def", new MultiStepDefCols("multi_step_def"), new MultiStepDefIxCols("multi_step_def"));
        public global::SpacetimeDB.Table<Enemy, NearbyEnemiesCols, NearbyEnemiesIxCols> NearbyEnemies() => new("nearby_enemies", new NearbyEnemiesCols("nearby_enemies"), new NearbyEnemiesIxCols("nearby_enemies"));
        public global::SpacetimeDB.Table<HexDecor, NearbyHexDecorCols, NearbyHexDecorIxCols> NearbyHexDecor() => new("nearby_hex_decor", new NearbyHexDecorCols("nearby_hex_decor"), new NearbyHexDecorIxCols("nearby_hex_decor"));
        public global::SpacetimeDB.Table<LootDrop, NearbyLootDropsCols, NearbyLootDropsIxCols> NearbyLootDrops() => new("nearby_loot_drops", new NearbyLootDropsCols("nearby_loot_drops"), new NearbyLootDropsIxCols("nearby_loot_drops"));
        public global::SpacetimeDB.Table<PlayerPosition, NearbyRemotePlayersCols, NearbyRemotePlayersIxCols> NearbyRemotePlayers() => new("nearby_remote_players", new NearbyRemotePlayersCols("nearby_remote_players"), new NearbyRemotePlayersIxCols("nearby_remote_players"));
        public global::SpacetimeDB.Table<PlayerProfile, NearbyRemotePlayersProfilesCols, NearbyRemotePlayersProfilesIxCols> NearbyRemotePlayersProfiles() => new("nearby_remote_players_profiles", new NearbyRemotePlayersProfilesCols("nearby_remote_players_profiles"), new NearbyRemotePlayersProfilesIxCols("nearby_remote_players_profiles"));
        public global::SpacetimeDB.Table<TriangleTile, NearbyTerrainTilesCols, NearbyTerrainTilesIxCols> NearbyTerrainTiles() => new("nearby_terrain_tiles", new NearbyTerrainTilesCols("nearby_terrain_tiles"), new NearbyTerrainTilesIxCols("nearby_terrain_tiles"));
        public global::SpacetimeDB.Table<OverlayAdjacencyRule, OverlayAdjacencyRuleCols, OverlayAdjacencyRuleIxCols> OverlayAdjacencyRule() => new("overlay_adjacency_rule", new OverlayAdjacencyRuleCols("overlay_adjacency_rule"), new OverlayAdjacencyRuleIxCols("overlay_adjacency_rule"));
        public global::SpacetimeDB.Table<PlayerChunk, PlayerChunkCols, PlayerChunkIxCols> PlayerChunk() => new("player_chunk", new PlayerChunkCols("player_chunk"), new PlayerChunkIxCols("player_chunk"));
        public global::SpacetimeDB.Table<PlayerData, PlayerDataCols, PlayerDataIxCols> PlayerData() => new("player_data", new PlayerDataCols("player_data"), new PlayerDataIxCols("player_data"));
        public global::SpacetimeDB.Table<PlayerInventory, PlayerInventoryCols, PlayerInventoryIxCols> PlayerInventory() => new("player_inventory", new PlayerInventoryCols("player_inventory"), new PlayerInventoryIxCols("player_inventory"));
        public global::SpacetimeDB.Table<PlayerPosition, PlayerPositionCols, PlayerPositionIxCols> PlayerPosition() => new("player_position", new PlayerPositionCols("player_position"), new PlayerPositionIxCols("player_position"));
        public global::SpacetimeDB.Table<PlayerProfile, PlayerProfileCols, PlayerProfileIxCols> PlayerProfile() => new("player_profile", new PlayerProfileCols("player_profile"), new PlayerProfileIxCols("player_profile"));
        public global::SpacetimeDB.Table<PlayerStats, PlayerStatsCols, PlayerStatsIxCols> PlayerStats() => new("player_stats", new PlayerStatsCols("player_stats"), new PlayerStatsIxCols("player_stats"));
        public global::SpacetimeDB.Table<RepeatStepDef, RepeatStepDefCols, RepeatStepDefIxCols> RepeatStepDef() => new("repeat_step_def", new RepeatStepDefCols("repeat_step_def"), new RepeatStepDefIxCols("repeat_step_def"));
        public global::SpacetimeDB.Table<RepeatStepInstance, RepeatStepInstanceCols, RepeatStepInstanceIxCols> RepeatStepInstance() => new("repeat_step_instance", new RepeatStepInstanceCols("repeat_step_instance"), new RepeatStepInstanceIxCols("repeat_step_instance"));
        public global::SpacetimeDB.Table<SingleStepDef, SingleStepDefCols, SingleStepDefIxCols> SingleStepDef() => new("single_step_def", new SingleStepDefCols("single_step_def"), new SingleStepDefIxCols("single_step_def"));
        public global::SpacetimeDB.Table<TextureEntry, TextureEntryCols, TextureEntryIxCols> TextureEntry() => new("texture_entry", new TextureEntryCols("texture_entry"), new TextureEntryIxCols("texture_entry"));
        public global::SpacetimeDB.Table<TriangleTile, TriangleTileCols, TriangleTileIxCols> TriangleTile() => new("triangle_tile", new TriangleTileCols("triangle_tile"), new TriangleTileIxCols("triangle_tile"));
        public global::SpacetimeDB.Table<WorldDef, WorldDefCols, WorldDefIxCols> WorldDef() => new("world_def", new WorldDefCols("world_def"), new WorldDefIxCols("world_def"));
    }

    public sealed class TypedSubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private Action<SubscriptionEventContext>? Applied;
        private Action<ErrorContext, Exception>? Error;
        private readonly List<string> querySqls = new();

        internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
        {
            this.conn = conn;
            Applied = applied;
            Error = error;
        }

        public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
        {
            Applied += callback;
            return this;
        }

        public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
        {
            Error += callback;
            return this;
        }

        public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
        {
            var qb = new QueryBuilder();
            querySqls.Add(build(qb).ToSql());
            return this;
        }

        public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public abstract partial class Procedure
    {
        private Procedure() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
        new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch
            {
                Reducer.AddChunks args => Reducers.InvokeAddChunks(eventContext, args),
                Reducer.ApplyEnchantment args => Reducers.InvokeApplyEnchantment(eventContext, args),
                Reducer.ChangeStats args => Reducers.InvokeChangeStats(eventContext, args),
                Reducer.ClaimAdmin args => Reducers.InvokeClaimAdmin(eventContext, args),
                Reducer.ClearChunks args => Reducers.InvokeClearChunks(eventContext, args),
                Reducer.CreateProfile args => Reducers.InvokeCreateProfile(eventContext, args),
                Reducer.DeleteProfile args => Reducers.InvokeDeleteProfile(eventContext, args),
                Reducer.DespawnEnemy args => Reducers.InvokeDespawnEnemy(eventContext, args),
                Reducer.DropItem args => Reducers.InvokeDropItem(eventContext, args),
                Reducer.GenerateWorldManual args => Reducers.InvokeGenerateWorldManual(eventContext, args),
                Reducer.GenerateWorldProc args => Reducers.InvokeGenerateWorldProc(eventContext, args),
                Reducer.GiveItem args => Reducers.InvokeGiveItem(eventContext, args),
                Reducer.JoinWorld args => Reducers.InvokeJoinWorld(eventContext, args),
                Reducer.LeaveWorld args => Reducers.InvokeLeaveWorld(eventContext, args),
                Reducer.PickupDrop args => Reducers.InvokePickupDrop(eventContext, args),
                Reducer.PlaceBuilding args => Reducers.InvokePlaceBuilding(eventContext, args),
                Reducer.ReleaseAdmin args => Reducers.InvokeReleaseAdmin(eventContext, args),
                Reducer.RemoveBuilding args => Reducers.InvokeRemoveBuilding(eventContext, args),
                Reducer.RemoveEnchantment args => Reducers.InvokeRemoveEnchantment(eventContext, args),
                Reducer.RemoveItem args => Reducers.InvokeRemoveItem(eventContext, args),
                Reducer.ReportEnemyHit args => Reducers.InvokeReportEnemyHit(eventContext, args),
                Reducer.ReportHit args => Reducers.InvokeReportHit(eventContext, args),
                Reducer.ReportMovement args => Reducers.InvokeReportMovement(eventContext, args),
                Reducer.SetUsername args => Reducers.InvokeSetUsername(eventContext, args),
                Reducer.SpawnEnemy args => Reducers.InvokeSpawnEnemy(eventContext, args),
                Reducer.SwapSlots args => Reducers.InvokeSwapSlots(eventContext, args),
                Reducer.ToggleDebug args => Reducers.InvokeToggleDebug(eventContext, args),
                Reducer.UpsertBiomeDef args => Reducers.InvokeUpsertBiomeDef(eventContext, args),
                Reducer.UpsertBiomeRegionDef args => Reducers.InvokeUpsertBiomeRegionDef(eventContext, args),
                Reducer.UpsertEnchantment args => Reducers.InvokeUpsertEnchantment(eventContext, args),
                Reducer.UpsertEnemyTemplate args => Reducers.InvokeUpsertEnemyTemplate(eventContext, args),
                Reducer.UpsertItem args => Reducers.InvokeUpsertItem(eventContext, args),
                Reducer.UpsertTextureEntry args => Reducers.InvokeUpsertTextureEntry(eventContext, args),
                Reducer.UpsertWorldDef args => Reducers.InvokeUpsertWorldDef(eventContext, args),
                Reducer.UseItem args => Reducers.InvokeUseItem(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
