// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityBehavior
    {
        [DataMember(Name = "effect")]
        public AbilityEffect Effect;
        [DataMember(Name = "potency")]
        public float Potency;
        [DataMember(Name = "duration")]
        public float Duration;
        [DataMember(Name = "cooldown_seconds")]
        public float CooldownSeconds;
        [DataMember(Name = "max_charges")]
        public uint MaxCharges;

        public AbilityBehavior(
            AbilityEffect Effect,
            float Potency,
            float Duration,
            float CooldownSeconds,
            uint MaxCharges
        )
        {
            this.Effect = Effect;
            this.Potency = Potency;
            this.Duration = Duration;
            this.CooldownSeconds = CooldownSeconds;
            this.MaxCharges = MaxCharges;
        }

        public AbilityBehavior()
        {
            this.Effect = null!;
        }
    }
}
