// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityUseBuffParams
    {
        [DataMember(Name = "buff")]
        public ConsumableBuffEffect Buff;
        [DataMember(Name = "duration")]
        public float Duration;

        public AbilityUseBuffParams(
            ConsumableBuffEffect Buff,
            float Duration
        )
        {
            this.Buff = Buff;
            this.Duration = Duration;
        }

        public AbilityUseBuffParams()
        {
            this.Buff = null!;
        }
    }
}
