// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActiveConsumableEffect
    {
        [DataMember(Name = "effect_id")]
        public ulong EffectId;
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "modifier")]
        public StatModifier Modifier;
        [DataMember(Name = "remaining")]
        public float Remaining;

        public ActiveConsumableEffect(
            ulong EffectId,
            ulong ProfileId,
            StatModifier Modifier,
            float Remaining
        )
        {
            this.EffectId = EffectId;
            this.ProfileId = ProfileId;
            this.Modifier = Modifier;
            this.Remaining = Remaining;
        }

        public ActiveConsumableEffect()
        {
            this.Modifier = new();
        }
    }
}
