// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AttackSequence
    {
        [DataMember(Name = "steps")]
        public System.Collections.Generic.List<SequenceStepDef> Steps;
        [DataMember(Name = "start_delay")]
        public float StartDelay;

        public AttackSequence(
            System.Collections.Generic.List<SequenceStepDef> Steps,
            float StartDelay
        )
        {
            this.Steps = Steps;
            this.StartDelay = StartDelay;
        }

        public AttackSequence()
        {
            this.Steps = new();
        }
    }
}
