// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BiomeWeight
    {
        [DataMember(Name = "biome_id")]
        public string BiomeId;
        [DataMember(Name = "weight")]
        public float Weight;

        public BiomeWeight(
            string BiomeId,
            float Weight
        )
        {
            this.BiomeId = BiomeId;
            this.Weight = Weight;
        }

        public BiomeWeight()
        {
            this.BiomeId = "";
        }
    }
}
