// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BiomeRegionDef
    {
        [DataMember(Name = "region_def_id")]
        public string RegionDefId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "enemy_template_ids")]
        public System.Collections.Generic.List<string> EnemyTemplateIds;
        [DataMember(Name = "max_enemies")]
        public uint MaxEnemies;
        [DataMember(Name = "spawn_radius")]
        public float SpawnRadius;

        public BiomeRegionDef(
            string RegionDefId,
            string DisplayName,
            System.Collections.Generic.List<string> EnemyTemplateIds,
            uint MaxEnemies,
            float SpawnRadius
        )
        {
            this.RegionDefId = RegionDefId;
            this.DisplayName = DisplayName;
            this.EnemyTemplateIds = EnemyTemplateIds;
            this.MaxEnemies = MaxEnemies;
            this.SpawnRadius = SpawnRadius;
        }

        public BiomeRegionDef()
        {
            this.RegionDefId = "";
            this.DisplayName = "";
            this.EnemyTemplateIds = new();
        }
    }
}
