// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingTile
    {
        [DataMember(Name = "tile_id")]
        public ulong TileId;
        [DataMember(Name = "hex_q")]
        public int HexQ;
        [DataMember(Name = "hex_r")]
        public int HexR;
        [DataMember(Name = "chunk_q")]
        public int ChunkQ;
        [DataMember(Name = "chunk_r")]
        public int ChunkR;
        [DataMember(Name = "local_index")]
        public int LocalIndex;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;
        [DataMember(Name = "building_type")]
        public string BuildingType;
        [DataMember(Name = "owner_id")]
        public SpacetimeDB.Identity? OwnerId;

        public BuildingTile(
            ulong TileId,
            int HexQ,
            int HexR,
            int ChunkQ,
            int ChunkR,
            int LocalIndex,
            long ChunkIndex,
            string BuildingType,
            SpacetimeDB.Identity? OwnerId
        )
        {
            this.TileId = TileId;
            this.HexQ = HexQ;
            this.HexR = HexR;
            this.ChunkQ = ChunkQ;
            this.ChunkR = ChunkR;
            this.LocalIndex = LocalIndex;
            this.ChunkIndex = ChunkIndex;
            this.BuildingType = BuildingType;
            this.OwnerId = OwnerId;
        }

        public BuildingTile()
        {
            this.BuildingType = "";
        }
    }
}
