// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BulletPatternEvent
    {
        [DataMember(Name = "event_id")]
        public ulong EventId;
        [DataMember(Name = "enemy_id")]
        public ulong EnemyId;
        [DataMember(Name = "source_step")]
        public SequenceStepRef SourceStep;
        [DataMember(Name = "origin_x")]
        public float OriginX;
        [DataMember(Name = "origin_y")]
        public float OriginY;
        [DataMember(Name = "origin_offset_x")]
        public float OriginOffsetX;
        [DataMember(Name = "origin_offset_y")]
        public float OriginOffsetY;
        [DataMember(Name = "base_angle_offset")]
        public float BaseAngleOffset;
        [DataMember(Name = "pattern_type")]
        public PatternType PatternType;
        [DataMember(Name = "target")]
        public SpacetimeDB.Identity? Target;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "lifetime")]
        public float Lifetime;
        [DataMember(Name = "angular_speed")]
        public float AngularSpeed;
        [DataMember(Name = "speed_acceleration")]
        public float SpeedAcceleration;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;

        public BulletPatternEvent(
            ulong EventId,
            ulong EnemyId,
            SequenceStepRef SourceStep,
            float OriginX,
            float OriginY,
            float OriginOffsetX,
            float OriginOffsetY,
            float BaseAngleOffset,
            PatternType PatternType,
            SpacetimeDB.Identity? Target,
            string TextureId,
            float Lifetime,
            float AngularSpeed,
            float SpeedAcceleration,
            long ChunkIndex
        )
        {
            this.EventId = EventId;
            this.EnemyId = EnemyId;
            this.SourceStep = SourceStep;
            this.OriginX = OriginX;
            this.OriginY = OriginY;
            this.OriginOffsetX = OriginOffsetX;
            this.OriginOffsetY = OriginOffsetY;
            this.BaseAngleOffset = BaseAngleOffset;
            this.PatternType = PatternType;
            this.Target = Target;
            this.TextureId = TextureId;
            this.Lifetime = Lifetime;
            this.AngularSpeed = AngularSpeed;
            this.SpeedAcceleration = SpeedAcceleration;
            this.ChunkIndex = ChunkIndex;
        }

        public BulletPatternEvent()
        {
            this.SourceStep = null!;
            this.PatternType = null!;
            this.TextureId = "";
        }
    }
}
