// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BulletControlEvent
    {
        [DataMember(Name = "event_id")]
        public ulong EventId;
        [DataMember(Name = "kind")]
        public BulletControlKind Kind;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "target_x")]
        public float TargetX;
        [DataMember(Name = "target_y")]
        public float TargetY;
        [DataMember(Name = "duration")]
        public float Duration;
        [DataMember(Name = "cast_by")]
        public SpacetimeDB.Identity CastBy;

        public BulletControlEvent(
            ulong EventId,
            BulletControlKind Kind,
            float X,
            float Y,
            float Radius,
            float TargetX,
            float TargetY,
            float Duration,
            SpacetimeDB.Identity CastBy
        )
        {
            this.EventId = EventId;
            this.Kind = Kind;
            this.X = X;
            this.Y = Y;
            this.Radius = Radius;
            this.TargetX = TargetX;
            this.TargetY = TargetY;
            this.Duration = Duration;
            this.CastBy = CastBy;
        }

        public BulletControlEvent()
        {
        }
    }
}
