// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConsumableBehavior
    {
        [DataMember(Name = "effect")]
        public ConsumableEffect Effect;
        [DataMember(Name = "potency")]
        public float Potency;
        [DataMember(Name = "duration")]
        public float Duration;

        public ConsumableBehavior(
            ConsumableEffect Effect,
            float Potency,
            float Duration
        )
        {
            this.Effect = Effect;
            this.Potency = Potency;
            this.Duration = Duration;
        }

        public ConsumableBehavior()
        {
            this.Effect = null!;
        }
    }
}
