// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CurtainParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;
        [DataMember(Name = "angle_span")]
        public float AngleSpan;
        [DataMember(Name = "gap_index")]
        public uint GapIndex;

        public CurtainParams(
            float Speed,
            uint Count,
            float AngleSpan,
            uint GapIndex
        )
        {
            this.Speed = Speed;
            this.Count = Count;
            this.AngleSpan = AngleSpan;
            this.GapIndex = GapIndex;
        }

        public CurtainParams()
        {
        }
    }
}
