// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DecorGroundRule
    {
        [DataMember(Name = "rule_id")]
        public ulong RuleId;
        [DataMember(Name = "decor_tag")]
        public string DecorTag;
        [DataMember(Name = "denied_base_tag")]
        public string DeniedBaseTag;

        public DecorGroundRule(
            ulong RuleId,
            string DecorTag,
            string DeniedBaseTag
        )
        {
            this.RuleId = RuleId;
            this.DecorTag = DecorTag;
            this.DeniedBaseTag = DeniedBaseTag;
        }

        public DecorGroundRule()
        {
            this.DecorTag = "";
            this.DeniedBaseTag = "";
        }
    }
}
