// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DecorConfig
    {
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "shadow_texture_id")]
        public string ShadowTextureId;
        [DataMember(Name = "chance")]
        public float Chance;
        [DataMember(Name = "tags")]
        public System.Collections.Generic.List<string> Tags;

        public DecorConfig(
            string TextureId,
            string ShadowTextureId,
            float Chance,
            System.Collections.Generic.List<string> Tags
        )
        {
            this.TextureId = TextureId;
            this.ShadowTextureId = ShadowTextureId;
            this.Chance = Chance;
            this.Tags = Tags;
        }

        public DecorConfig()
        {
            this.TextureId = "";
            this.ShadowTextureId = "";
            this.Tags = new();
        }
    }
}
