// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Enchantment
    {
        [DataMember(Name = "enchantment_id")]
        public string EnchantmentId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "stat_modifiers")]
        public System.Collections.Generic.List<StatModifier> StatModifiers;
        [DataMember(Name = "allowed_slots")]
        public System.Collections.Generic.List<EquipSlot> AllowedSlots;

        public Enchantment(
            string EnchantmentId,
            string DisplayName,
            string Description,
            string TextureId,
            System.Collections.Generic.List<StatModifier> StatModifiers,
            System.Collections.Generic.List<EquipSlot> AllowedSlots
        )
        {
            this.EnchantmentId = EnchantmentId;
            this.DisplayName = DisplayName;
            this.Description = Description;
            this.TextureId = TextureId;
            this.StatModifiers = StatModifiers;
            this.AllowedSlots = AllowedSlots;
        }

        public Enchantment()
        {
            this.EnchantmentId = "";
            this.DisplayName = "";
            this.Description = "";
            this.TextureId = "";
            this.StatModifiers = new();
            this.AllowedSlots = new();
        }
    }
}
