// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyAttack
    {
        [DataMember(Name = "attack_id")]
        public ulong AttackId;
        [DataMember(Name = "phase_id")]
        public ulong PhaseId;
        [DataMember(Name = "attack_index")]
        public uint AttackIndex;
        [DataMember(Name = "step_index")]
        public uint StepIndex;
        [DataMember(Name = "step_timer")]
        public SpacetimeDB.Timestamp StepTimer;
        [DataMember(Name = "step_waiting")]
        public bool StepWaiting;
        [DataMember(Name = "start_delaying")]
        public bool StartDelaying;
        [DataMember(Name = "loop_waiting")]
        public bool LoopWaiting;

        public EnemyAttack(
            ulong AttackId,
            ulong PhaseId,
            uint AttackIndex,
            uint StepIndex,
            SpacetimeDB.Timestamp StepTimer,
            bool StepWaiting,
            bool StartDelaying,
            bool LoopWaiting
        )
        {
            this.AttackId = AttackId;
            this.PhaseId = PhaseId;
            this.AttackIndex = AttackIndex;
            this.StepIndex = StepIndex;
            this.StepTimer = StepTimer;
            this.StepWaiting = StepWaiting;
            this.StartDelaying = StartDelaying;
            this.LoopWaiting = LoopWaiting;
        }

        public EnemyAttack()
        {
        }
    }
}
