// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyPhase
    {
        [DataMember(Name = "phase_id")]
        public ulong PhaseId;
        [DataMember(Name = "behavior_id")]
        public ulong BehaviorId;
        [DataMember(Name = "phase_index")]
        public byte PhaseIndex;
        [DataMember(Name = "hp_threshold")]
        public float HpThreshold;
        [DataMember(Name = "movement_def_id")]
        public ulong MovementDefId;
        [DataMember(Name = "phase_loop_delay")]
        public float PhaseLoopDelay;
        [DataMember(Name = "phase_waiting")]
        public bool PhaseWaiting;
        [DataMember(Name = "phase_loop_timer")]
        public SpacetimeDB.Timestamp PhaseLoopTimer;
        [DataMember(Name = "move_cycle_started_at")]
        public SpacetimeDB.Timestamp MoveCycleStartedAt;

        public EnemyPhase(
            ulong PhaseId,
            ulong BehaviorId,
            byte PhaseIndex,
            float HpThreshold,
            ulong MovementDefId,
            float PhaseLoopDelay,
            bool PhaseWaiting,
            SpacetimeDB.Timestamp PhaseLoopTimer,
            SpacetimeDB.Timestamp MoveCycleStartedAt
        )
        {
            this.PhaseId = PhaseId;
            this.BehaviorId = BehaviorId;
            this.PhaseIndex = PhaseIndex;
            this.HpThreshold = HpThreshold;
            this.MovementDefId = MovementDefId;
            this.PhaseLoopDelay = PhaseLoopDelay;
            this.PhaseWaiting = PhaseWaiting;
            this.PhaseLoopTimer = PhaseLoopTimer;
            this.MoveCycleStartedAt = MoveCycleStartedAt;
        }

        public EnemyPhase()
        {
        }
    }
}
