// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyTemplate
    {
        [DataMember(Name = "template_id")]
        public string TemplateId;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "max_hp")]
        public uint MaxHp;
        [DataMember(Name = "defense")]
        public uint Defense;
        [DataMember(Name = "move_sim_factor")]
        public float MoveSimFactor;
        [DataMember(Name = "attack_sim_factor")]
        public float AttackSimFactor;
        [DataMember(Name = "aggro_lock_seconds")]
        public float AggroLockSeconds;
        [DataMember(Name = "phases")]
        public System.Collections.Generic.List<PhaseDef> Phases;

        public EnemyTemplate(
            string TemplateId,
            string TextureId,
            string DisplayName,
            uint MaxHp,
            uint Defense,
            float MoveSimFactor,
            float AttackSimFactor,
            float AggroLockSeconds,
            System.Collections.Generic.List<PhaseDef> Phases
        )
        {
            this.TemplateId = TemplateId;
            this.TextureId = TextureId;
            this.DisplayName = DisplayName;
            this.MaxHp = MaxHp;
            this.Defense = Defense;
            this.MoveSimFactor = MoveSimFactor;
            this.AttackSimFactor = AttackSimFactor;
            this.AggroLockSeconds = AggroLockSeconds;
            this.Phases = Phases;
        }

        public EnemyTemplate()
        {
            this.TemplateId = "";
            this.TextureId = "";
            this.DisplayName = "";
            this.Phases = new();
        }
    }
}
