// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemyBehavior
    {
        [DataMember(Name = "behavior_id")]
        public ulong BehaviorId;
        [DataMember(Name = "aggro_target")]
        public SpacetimeDB.Identity? AggroTarget;
        [DataMember(Name = "aggro_locked_until")]
        public SpacetimeDB.Timestamp AggroLockedUntil;
        [DataMember(Name = "was_simulating")]
        public bool WasSimulating;
        [DataMember(Name = "active_phase_index")]
        public byte ActivePhaseIndex;
        [DataMember(Name = "velocity_x")]
        public float VelocityX;
        [DataMember(Name = "velocity_y")]
        public float VelocityY;

        public EnemyBehavior(
            ulong BehaviorId,
            SpacetimeDB.Identity? AggroTarget,
            SpacetimeDB.Timestamp AggroLockedUntil,
            bool WasSimulating,
            byte ActivePhaseIndex,
            float VelocityX,
            float VelocityY
        )
        {
            this.BehaviorId = BehaviorId;
            this.AggroTarget = AggroTarget;
            this.AggroLockedUntil = AggroLockedUntil;
            this.WasSimulating = WasSimulating;
            this.ActivePhaseIndex = ActivePhaseIndex;
            this.VelocityX = VelocityX;
            this.VelocityY = VelocityY;
        }

        public EnemyBehavior()
        {
        }
    }
}
