// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Enemy
    {
        [DataMember(Name = "enemy_id")]
        public ulong EnemyId;
        [DataMember(Name = "template_id")]
        public string TemplateId;
        [DataMember(Name = "behavior_id")]
        public ulong BehaviorId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "spawn_time")]
        public SpacetimeDB.Timestamp SpawnTime;
        [DataMember(Name = "hp")]
        public uint Hp;
        [DataMember(Name = "phase")]
        public byte Phase;
        [DataMember(Name = "is_elite")]
        public bool IsElite;
        [DataMember(Name = "immortal")]
        public bool Immortal;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;

        public Enemy(
            ulong EnemyId,
            string TemplateId,
            ulong BehaviorId,
            float X,
            float Y,
            SpacetimeDB.Timestamp SpawnTime,
            uint Hp,
            byte Phase,
            bool IsElite,
            bool Immortal,
            long ChunkIndex
        )
        {
            this.EnemyId = EnemyId;
            this.TemplateId = TemplateId;
            this.BehaviorId = BehaviorId;
            this.X = X;
            this.Y = Y;
            this.SpawnTime = SpawnTime;
            this.Hp = Hp;
            this.Phase = Phase;
            this.IsElite = IsElite;
            this.Immortal = Immortal;
            this.ChunkIndex = ChunkIndex;
        }

        public Enemy()
        {
            this.TemplateId = "";
        }
    }
}
