// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemySequenceStep
    {
        [DataMember(Name = "step_id")]
        public ulong StepId;
        [DataMember(Name = "attack_id")]
        public ulong AttackId;
        [DataMember(Name = "step_index")]
        public uint StepIndex;
        [DataMember(Name = "step")]
        public SequenceStepRef Step;

        public EnemySequenceStep(
            ulong StepId,
            ulong AttackId,
            uint StepIndex,
            SequenceStepRef Step
        )
        {
            this.StepId = StepId;
            this.AttackId = AttackId;
            this.StepIndex = StepIndex;
            this.Step = Step;
        }

        public EnemySequenceStep()
        {
            this.Step = null!;
        }
    }
}
