// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FleeParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "min_range")]
        public float MinRange;
        [DataMember(Name = "active_duration")]
        public float ActiveDuration;
        [DataMember(Name = "pause_duration")]
        public float PauseDuration;

        public FleeParams(
            float Speed,
            float MinRange,
            float ActiveDuration,
            float PauseDuration
        )
        {
            this.Speed = Speed;
            this.MinRange = MinRange;
            this.ActiveDuration = ActiveDuration;
            this.PauseDuration = PauseDuration;
        }

        public FleeParams()
        {
        }
    }
}
