// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GroundTextureConfig
    {
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "chance")]
        public float Chance;
        [DataMember(Name = "tags")]
        public System.Collections.Generic.List<string> Tags;
        [DataMember(Name = "allowed_rotations")]
        public System.Collections.Generic.List<byte> AllowedRotations;

        public GroundTextureConfig(
            string TextureId,
            float Chance,
            System.Collections.Generic.List<string> Tags,
            System.Collections.Generic.List<byte> AllowedRotations
        )
        {
            this.TextureId = TextureId;
            this.Chance = Chance;
            this.Tags = Tags;
            this.AllowedRotations = AllowedRotations;
        }

        public GroundTextureConfig()
        {
            this.TextureId = "";
            this.Tags = new();
            this.AllowedRotations = new();
        }
    }
}
