// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HexDecor
    {
        [DataMember(Name = "decor_id")]
        public ulong DecorId;
        [DataMember(Name = "hex_q")]
        public int HexQ;
        [DataMember(Name = "hex_r")]
        public int HexR;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "shadow_texture_id")]
        public string ShadowTextureId;
        [DataMember(Name = "rotation_degrees")]
        public float RotationDegrees;
        [DataMember(Name = "biome_id")]
        public string BiomeId;
        [DataMember(Name = "region_id")]
        public ulong RegionId;

        public HexDecor(
            ulong DecorId,
            int HexQ,
            int HexR,
            long ChunkIndex,
            string TextureId,
            string ShadowTextureId,
            float RotationDegrees,
            string BiomeId,
            ulong RegionId
        )
        {
            this.DecorId = DecorId;
            this.HexQ = HexQ;
            this.HexR = HexR;
            this.ChunkIndex = ChunkIndex;
            this.TextureId = TextureId;
            this.ShadowTextureId = ShadowTextureId;
            this.RotationDegrees = RotationDegrees;
            this.BiomeId = BiomeId;
            this.RegionId = RegionId;
        }

        public HexDecor()
        {
            this.TextureId = "";
            this.ShadowTextureId = "";
            this.BiomeId = "";
        }
    }
}
