// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventorySlot
    {
        [DataMember(Name = "allowed_slots")]
        public System.Collections.Generic.List<EquipSlot> AllowedSlots;
        [DataMember(Name = "item_id")]
        public string? ItemId;
        [DataMember(Name = "enchantment_ids")]
        public System.Collections.Generic.List<string> EnchantmentIds;

        public InventorySlot(
            System.Collections.Generic.List<EquipSlot> AllowedSlots,
            string? ItemId,
            System.Collections.Generic.List<string> EnchantmentIds
        )
        {
            this.AllowedSlots = AllowedSlots;
            this.ItemId = ItemId;
            this.EnchantmentIds = EnchantmentIds;
        }

        public InventorySlot()
        {
            this.AllowedSlots = new();
            this.EnchantmentIds = new();
        }
    }
}
