// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Item
    {
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "equip_slot")]
        public EquipSlot EquipSlot;
        [DataMember(Name = "stat_modifiers")]
        public System.Collections.Generic.List<StatModifier> StatModifiers;
        [DataMember(Name = "behaviors")]
        public System.Collections.Generic.List<ItemBehavior> Behaviors;
        [DataMember(Name = "max_enchantments")]
        public uint MaxEnchantments;

        public Item(
            string ItemId,
            string DisplayName,
            string Description,
            string TextureId,
            EquipSlot EquipSlot,
            System.Collections.Generic.List<StatModifier> StatModifiers,
            System.Collections.Generic.List<ItemBehavior> Behaviors,
            uint MaxEnchantments
        )
        {
            this.ItemId = ItemId;
            this.DisplayName = DisplayName;
            this.Description = Description;
            this.TextureId = TextureId;
            this.EquipSlot = EquipSlot;
            this.StatModifiers = StatModifiers;
            this.Behaviors = Behaviors;
            this.MaxEnchantments = MaxEnchantments;
        }

        public Item()
        {
            this.ItemId = "";
            this.DisplayName = "";
            this.Description = "";
            this.TextureId = "";
            this.StatModifiers = new();
            this.Behaviors = new();
        }
    }
}
