// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LayeringRule
    {
        [DataMember(Name = "rule_id")]
        public ulong RuleId;
        [DataMember(Name = "overlay_tag")]
        public string OverlayTag;
        [DataMember(Name = "allowed_base_tag")]
        public string AllowedBaseTag;

        public LayeringRule(
            ulong RuleId,
            string OverlayTag,
            string AllowedBaseTag
        )
        {
            this.RuleId = RuleId;
            this.OverlayTag = OverlayTag;
            this.AllowedBaseTag = AllowedBaseTag;
        }

        public LayeringRule()
        {
            this.OverlayTag = "";
            this.AllowedBaseTag = "";
        }
    }
}
