// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedInPlayer
    {
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "is_admin")]
        public bool IsAdmin;
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;

        public LoggedInPlayer(
            SpacetimeDB.Identity PlayerId,
            string Username,
            bool IsAdmin,
            ulong ProfileId
        )
        {
            this.PlayerId = PlayerId;
            this.Username = Username;
            this.IsAdmin = IsAdmin;
            this.ProfileId = ProfileId;
        }

        public LoggedInPlayer()
        {
            this.Username = "";
        }
    }
}
