// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LootDrop
    {
        [DataMember(Name = "drop_id")]
        public ulong DropId;
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp ExpiresAt;
        [DataMember(Name = "dropped_by")]
        public SpacetimeDB.Identity? DroppedBy;
        [DataMember(Name = "enchantment_ids")]
        public System.Collections.Generic.List<string> EnchantmentIds;

        public LootDrop(
            ulong DropId,
            string ItemId,
            float X,
            float Y,
            long ChunkIndex,
            SpacetimeDB.Timestamp ExpiresAt,
            SpacetimeDB.Identity? DroppedBy,
            System.Collections.Generic.List<string> EnchantmentIds
        )
        {
            this.DropId = DropId;
            this.ItemId = ItemId;
            this.X = X;
            this.Y = Y;
            this.ChunkIndex = ChunkIndex;
            this.ExpiresAt = ExpiresAt;
            this.DroppedBy = DroppedBy;
            this.EnchantmentIds = EnchantmentIds;
        }

        public LootDrop()
        {
            this.ItemId = "";
            this.EnchantmentIds = new();
        }
    }
}
