// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ManualBiomeInput
    {
        [DataMember(Name = "biome_id")]
        public string BiomeId;
        [DataMember(Name = "center_hex_q")]
        public int CenterHexQ;
        [DataMember(Name = "center_hex_r")]
        public int CenterHexR;
        [DataMember(Name = "ground_textures")]
        public System.Collections.Generic.List<GroundTextureConfig> GroundTextures;
        [DataMember(Name = "overlay_textures")]
        public System.Collections.Generic.List<OverlayTextureConfig> OverlayTextures;
        [DataMember(Name = "regions")]
        public System.Collections.Generic.List<ManualRegionInput> Regions;
        [DataMember(Name = "ground_noise_scale")]
        public float GroundNoiseScale;
        [DataMember(Name = "overlay_noise_scale")]
        public float OverlayNoiseScale;
        [DataMember(Name = "decor_configs")]
        public System.Collections.Generic.List<DecorConfig> DecorConfigs;
        [DataMember(Name = "decor_noise_scale")]
        public float DecorNoiseScale;
        [DataMember(Name = "decor_min_separation")]
        public int DecorMinSeparation;

        public ManualBiomeInput(
            string BiomeId,
            int CenterHexQ,
            int CenterHexR,
            System.Collections.Generic.List<GroundTextureConfig> GroundTextures,
            System.Collections.Generic.List<OverlayTextureConfig> OverlayTextures,
            System.Collections.Generic.List<ManualRegionInput> Regions,
            float GroundNoiseScale,
            float OverlayNoiseScale,
            System.Collections.Generic.List<DecorConfig> DecorConfigs,
            float DecorNoiseScale,
            int DecorMinSeparation
        )
        {
            this.BiomeId = BiomeId;
            this.CenterHexQ = CenterHexQ;
            this.CenterHexR = CenterHexR;
            this.GroundTextures = GroundTextures;
            this.OverlayTextures = OverlayTextures;
            this.Regions = Regions;
            this.GroundNoiseScale = GroundNoiseScale;
            this.OverlayNoiseScale = OverlayNoiseScale;
            this.DecorConfigs = DecorConfigs;
            this.DecorNoiseScale = DecorNoiseScale;
            this.DecorMinSeparation = DecorMinSeparation;
        }

        public ManualBiomeInput()
        {
            this.BiomeId = "";
            this.GroundTextures = new();
            this.OverlayTextures = new();
            this.Regions = new();
            this.DecorConfigs = new();
        }
    }
}
