// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ManualRegionInput
    {
        [DataMember(Name = "region_id")]
        public string RegionId;
        [DataMember(Name = "center_hex_q")]
        public int CenterHexQ;
        [DataMember(Name = "center_hex_r")]
        public int CenterHexR;
        [DataMember(Name = "enemy_template_ids")]
        public System.Collections.Generic.List<string> EnemyTemplateIds;
        [DataMember(Name = "max_enemies")]
        public uint MaxEnemies;
        [DataMember(Name = "spawn_radius")]
        public float SpawnRadius;

        public ManualRegionInput(
            string RegionId,
            int CenterHexQ,
            int CenterHexR,
            System.Collections.Generic.List<string> EnemyTemplateIds,
            uint MaxEnemies,
            float SpawnRadius
        )
        {
            this.RegionId = RegionId;
            this.CenterHexQ = CenterHexQ;
            this.CenterHexR = CenterHexR;
            this.EnemyTemplateIds = EnemyTemplateIds;
            this.MaxEnemies = MaxEnemies;
            this.SpawnRadius = SpawnRadius;
        }

        public ManualRegionInput()
        {
            this.RegionId = "";
            this.EnemyTemplateIds = new();
        }
    }
}
