// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "chunk_hex_radius")]
        public int ChunkHexRadius;
        [DataMember(Name = "chunk_cols")]
        public int ChunkCols;
        [DataMember(Name = "chunk_rows")]
        public int ChunkRows;
        [DataMember(Name = "hex_outer_radius")]
        public float HexOuterRadius;
        [DataMember(Name = "lap_q_x")]
        public float LapQX;
        [DataMember(Name = "lap_q_y")]
        public float LapQY;
        [DataMember(Name = "lap_r_x")]
        public float LapRX;
        [DataMember(Name = "lap_r_y")]
        public float LapRY;

        public MapConfig(
            uint Id,
            int ChunkHexRadius,
            int ChunkCols,
            int ChunkRows,
            float HexOuterRadius,
            float LapQX,
            float LapQY,
            float LapRX,
            float LapRY
        )
        {
            this.Id = Id;
            this.ChunkHexRadius = ChunkHexRadius;
            this.ChunkCols = ChunkCols;
            this.ChunkRows = ChunkRows;
            this.HexOuterRadius = HexOuterRadius;
            this.LapQX = LapQX;
            this.LapQY = LapQY;
            this.LapRX = LapRX;
            this.LapRY = LapRY;
        }

        public MapConfig()
        {
        }
    }
}
