// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MovementDef
    {
        [DataMember(Name = "def_id")]
        public ulong DefId;
        [DataMember(Name = "movement")]
        public MovementBehavior Movement;

        public MovementDef(
            ulong DefId,
            MovementBehavior Movement
        )
        {
            this.DefId = DefId;
            this.Movement = Movement;
        }

        public MovementDef()
        {
            this.Movement = null!;
        }
    }
}
