// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MultiShot
    {
        [DataMember(Name = "pattern_type")]
        public PatternType PatternType;
        [DataMember(Name = "target")]
        public EnemyTarget Target;
        [DataMember(Name = "offset_x")]
        public float OffsetX;
        [DataMember(Name = "offset_y")]
        public float OffsetY;
        [DataMember(Name = "base_angle_offset")]
        public float BaseAngleOffset;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "lifetime")]
        public float Lifetime;
        [DataMember(Name = "damage")]
        public uint Damage;

        public MultiShot(
            PatternType PatternType,
            EnemyTarget Target,
            float OffsetX,
            float OffsetY,
            float BaseAngleOffset,
            string TextureId,
            float Lifetime,
            uint Damage
        )
        {
            this.PatternType = PatternType;
            this.Target = Target;
            this.OffsetX = OffsetX;
            this.OffsetY = OffsetY;
            this.BaseAngleOffset = BaseAngleOffset;
            this.TextureId = TextureId;
            this.Lifetime = Lifetime;
            this.Damage = Damage;
        }

        public MultiShot()
        {
            this.PatternType = null!;
            this.TextureId = "";
        }
    }
}
