// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MultiStepDef
    {
        [DataMember(Name = "def_id")]
        public ulong DefId;
        [DataMember(Name = "shots")]
        public System.Collections.Generic.List<MultiShot> Shots;
        [DataMember(Name = "next_step_delay")]
        public float NextStepDelay;

        public MultiStepDef(
            ulong DefId,
            System.Collections.Generic.List<MultiShot> Shots,
            float NextStepDelay
        )
        {
            this.DefId = DefId;
            this.Shots = Shots;
            this.NextStepDelay = NextStepDelay;
        }

        public MultiStepDef()
        {
            this.Shots = new();
        }
    }
}
