// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MultiStepRef
    {
        [DataMember(Name = "def_id")]
        public ulong DefId;
        [DataMember(Name = "shot_index")]
        public uint ShotIndex;

        public MultiStepRef(
            ulong DefId,
            uint ShotIndex
        )
        {
            this.DefId = DefId;
            this.ShotIndex = ShotIndex;
        }

        public MultiStepRef()
        {
        }
    }
}
