// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OverlayAdjacencyRule
    {
        [DataMember(Name = "rule_id")]
        public ulong RuleId;
        [DataMember(Name = "tag_a")]
        public string TagA;
        [DataMember(Name = "tag_b")]
        public string TagB;

        public OverlayAdjacencyRule(
            ulong RuleId,
            string TagA,
            string TagB
        )
        {
            this.RuleId = RuleId;
            this.TagA = TagA;
            this.TagB = TagB;
        }

        public OverlayAdjacencyRule()
        {
            this.TagA = "";
            this.TagB = "";
        }
    }
}
