// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PhaseDef
    {
        [DataMember(Name = "phase_index")]
        public byte PhaseIndex;
        [DataMember(Name = "hp_threshold")]
        public float HpThreshold;
        [DataMember(Name = "movement_def_id")]
        public ulong MovementDefId;
        [DataMember(Name = "phase_loop_delay")]
        public float PhaseLoopDelay;
        [DataMember(Name = "attacks")]
        public System.Collections.Generic.List<AttackSequence> Attacks;

        public PhaseDef(
            byte PhaseIndex,
            float HpThreshold,
            ulong MovementDefId,
            float PhaseLoopDelay,
            System.Collections.Generic.List<AttackSequence> Attacks
        )
        {
            this.PhaseIndex = PhaseIndex;
            this.HpThreshold = HpThreshold;
            this.MovementDefId = MovementDefId;
            this.PhaseLoopDelay = PhaseLoopDelay;
            this.Attacks = Attacks;
        }

        public PhaseDef()
        {
            this.Attacks = new();
        }
    }
}
