// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerRotation
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "screen_rotation")]
        public float ScreenRotation;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;

        public PlayerRotation(
            ulong ProfileId,
            SpacetimeDB.Identity PlayerId,
            float ScreenRotation,
            long ChunkIndex
        )
        {
            this.ProfileId = ProfileId;
            this.PlayerId = PlayerId;
            this.ScreenRotation = ScreenRotation;
            this.ChunkIndex = ChunkIndex;
        }

        public PlayerRotation()
        {
        }
    }
}
