// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInventorySlot
    {
        [DataMember(Name = "slot_id")]
        public ulong SlotId;
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "slot_index")]
        public uint SlotIndex;
        [DataMember(Name = "role")]
        public SlotRole Role;
        [DataMember(Name = "item_id")]
        public string? ItemId;
        [DataMember(Name = "enchantment_ids")]
        public System.Collections.Generic.List<string> EnchantmentIds;
        [DataMember(Name = "cooldown_until")]
        public SpacetimeDB.Timestamp? CooldownUntil;
        [DataMember(Name = "charges")]
        public uint Charges;
        [DataMember(Name = "active_toggle")]
        public uint ActiveToggle;
        [DataMember(Name = "occupied_by")]
        public uint? OccupiedBy;

        public PlayerInventorySlot(
            ulong SlotId,
            ulong ProfileId,
            uint SlotIndex,
            SlotRole Role,
            string? ItemId,
            System.Collections.Generic.List<string> EnchantmentIds,
            SpacetimeDB.Timestamp? CooldownUntil,
            uint Charges,
            uint ActiveToggle,
            uint? OccupiedBy
        )
        {
            this.SlotId = SlotId;
            this.ProfileId = ProfileId;
            this.SlotIndex = SlotIndex;
            this.Role = Role;
            this.ItemId = ItemId;
            this.EnchantmentIds = EnchantmentIds;
            this.CooldownUntil = CooldownUntil;
            this.Charges = Charges;
            this.ActiveToggle = ActiveToggle;
            this.OccupiedBy = OccupiedBy;
        }

        public PlayerInventorySlot()
        {
            this.EnchantmentIds = new();
        }
    }
}
