// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerPosition
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "rotation")]
        public float Rotation;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;

        public PlayerPosition(
            ulong ProfileId,
            SpacetimeDB.Identity PlayerId,
            float X,
            float Y,
            float Rotation,
            long ChunkIndex
        )
        {
            this.ProfileId = ProfileId;
            this.PlayerId = PlayerId;
            this.X = X;
            this.Y = Y;
            this.Rotation = Rotation;
            this.ChunkIndex = ChunkIndex;
        }

        public PlayerPosition()
        {
        }
    }
}
