// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStats
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "strength")]
        public int Strength;
        [DataMember(Name = "wisdom")]
        public int Wisdom;
        [DataMember(Name = "dexterity")]
        public int Dexterity;
        [DataMember(Name = "damage_dealer")]
        public int DamageDealer;
        [DataMember(Name = "supporter")]
        public int Supporter;
        [DataMember(Name = "artisan")]
        public int Artisan;

        public PlayerStats(
            ulong ProfileId,
            int Strength,
            int Wisdom,
            int Dexterity,
            int DamageDealer,
            int Supporter,
            int Artisan
        )
        {
            this.ProfileId = ProfileId;
            this.Strength = Strength;
            this.Wisdom = Wisdom;
            this.Dexterity = Dexterity;
            this.DamageDealer = DamageDealer;
            this.Supporter = Supporter;
            this.Artisan = Artisan;
        }

        public PlayerStats()
        {
        }
    }
}
