// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerHitFlag
    {
        [DataMember(Name = "flag_id")]
        public ulong FlagId;
        [DataMember(Name = "hit_player")]
        public SpacetimeDB.Identity HitPlayer;
        [DataMember(Name = "reported_by")]
        public SpacetimeDB.Identity ReportedBy;
        [DataMember(Name = "reported_at")]
        public SpacetimeDB.Timestamp ReportedAt;

        public PlayerHitFlag(
            ulong FlagId,
            SpacetimeDB.Identity HitPlayer,
            SpacetimeDB.Identity ReportedBy,
            SpacetimeDB.Timestamp ReportedAt
        )
        {
            this.FlagId = FlagId;
            this.HitPlayer = HitPlayer;
            this.ReportedBy = ReportedBy;
            this.ReportedAt = ReportedAt;
        }

        public PlayerHitFlag()
        {
        }
    }
}
