// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInventory
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "slots")]
        public System.Collections.Generic.List<InventorySlot> Slots;

        public PlayerInventory(
            ulong ProfileId,
            System.Collections.Generic.List<InventorySlot> Slots
        )
        {
            this.ProfileId = ProfileId;
            this.Slots = Slots;
        }

        public PlayerInventory()
        {
            this.Slots = new();
        }
    }
}
