// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerData
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "xp")]
        public uint Xp;
        [DataMember(Name = "hp")]
        public uint Hp;
        [DataMember(Name = "max_hp")]
        public uint MaxHp;
        [DataMember(Name = "defense")]
        public int Defense;
        [DataMember(Name = "base_speed")]
        public float BaseSpeed;

        public PlayerData(
            ulong ProfileId,
            uint Level,
            uint Xp,
            uint Hp,
            uint MaxHp,
            int Defense,
            float BaseSpeed
        )
        {
            this.ProfileId = ProfileId;
            this.Level = Level;
            this.Xp = Xp;
            this.Hp = Hp;
            this.MaxHp = MaxHp;
            this.Defense = Defense;
            this.BaseSpeed = BaseSpeed;
        }

        public PlayerData()
        {
        }
    }
}
