// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStatAllocation
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "strength")]
        public uint Strength;
        [DataMember(Name = "wisdom")]
        public uint Wisdom;
        [DataMember(Name = "dexterity")]
        public uint Dexterity;
        [DataMember(Name = "damage_dealer")]
        public uint DamageDealer;
        [DataMember(Name = "supporter")]
        public uint Supporter;
        [DataMember(Name = "artisan")]
        public uint Artisan;
        [DataMember(Name = "unspent_points")]
        public uint UnspentPoints;

        public PlayerStatAllocation(
            ulong ProfileId,
            uint Strength,
            uint Wisdom,
            uint Dexterity,
            uint DamageDealer,
            uint Supporter,
            uint Artisan,
            uint UnspentPoints
        )
        {
            this.ProfileId = ProfileId;
            this.Strength = Strength;
            this.Wisdom = Wisdom;
            this.Dexterity = Dexterity;
            this.DamageDealer = DamageDealer;
            this.Supporter = Supporter;
            this.Artisan = Artisan;
            this.UnspentPoints = UnspentPoints;
        }

        public PlayerStatAllocation()
        {
        }
    }
}
