// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStats
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "strength")]
        public int Strength;
        [DataMember(Name = "wisdom")]
        public int Wisdom;
        [DataMember(Name = "dexterity")]
        public int Dexterity;
        [DataMember(Name = "defense")]
        public int Defense;
        [DataMember(Name = "vitality")]
        public int Vitality;
        [DataMember(Name = "speed")]
        public int Speed;

        public PlayerStats(
            ulong ProfileId,
            int Strength,
            int Wisdom,
            int Dexterity,
            int Defense,
            int Vitality,
            int Speed
        )
        {
            this.ProfileId = ProfileId;
            this.Strength = Strength;
            this.Wisdom = Wisdom;
            this.Dexterity = Dexterity;
            this.Defense = Defense;
            this.Vitality = Vitality;
            this.Speed = Speed;
        }

        public PlayerStats()
        {
        }
    }
}
