// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerProfile
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "profile_name")]
        public string ProfileName;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "aim_assist")]
        public bool AimAssist;
        [DataMember(Name = "lock_on")]
        public bool LockOn;

        public PlayerProfile(
            ulong ProfileId,
            SpacetimeDB.Identity PlayerId,
            string ProfileName,
            string TextureId,
            bool AimAssist,
            bool LockOn
        )
        {
            this.ProfileId = ProfileId;
            this.PlayerId = PlayerId;
            this.ProfileName = ProfileName;
            this.TextureId = TextureId;
            this.AimAssist = AimAssist;
            this.LockOn = LockOn;
        }

        public PlayerProfile()
        {
            this.ProfileName = "";
            this.TextureId = "";
        }
    }
}
