// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerChunk
    {
        [DataMember(Name = "profile_id")]
        public ulong ProfileId;
        [DataMember(Name = "chunk_q")]
        public int ChunkQ;
        [DataMember(Name = "chunk_r")]
        public int ChunkR;

        public PlayerChunk(
            ulong ProfileId,
            int ChunkQ,
            int ChunkR
        )
        {
            this.ProfileId = ProfileId;
            this.ChunkQ = ChunkQ;
            this.ChunkR = ChunkR;
        }

        public PlayerChunk()
        {
        }
    }
}
