// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RectParams
    {
        [DataMember(Name = "length")]
        public float Length;
        [DataMember(Name = "width")]
        public float Width;

        public RectParams(
            float Length,
            float Width
        )
        {
            this.Length = Length;
            this.Width = Width;
        }

        public RectParams()
        {
        }
    }
}
