// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RegionWeight
    {
        [DataMember(Name = "region_def_id")]
        public string RegionDefId;
        [DataMember(Name = "weight")]
        public float Weight;

        public RegionWeight(
            string RegionDefId,
            float Weight
        )
        {
            this.RegionDefId = RegionDefId;
            this.Weight = Weight;
        }

        public RegionWeight()
        {
            this.RegionDefId = "";
        }
    }
}
