// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RepeatStepInstance
    {
        [DataMember(Name = "repeat_id")]
        public ulong RepeatId;
        [DataMember(Name = "pattern_type")]
        public PatternType PatternType;
        [DataMember(Name = "target")]
        public EnemyTarget Target;
        [DataMember(Name = "offset_x")]
        public float OffsetX;
        [DataMember(Name = "offset_y")]
        public float OffsetY;
        [DataMember(Name = "base_angle_offset")]
        public float BaseAngleOffset;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "lifetime")]
        public float Lifetime;
        [DataMember(Name = "damage")]
        public uint Damage;
        [DataMember(Name = "angular_speed")]
        public float AngularSpeed;
        [DataMember(Name = "speed_acceleration")]
        public float SpeedAcceleration;
        [DataMember(Name = "repeat_interval")]
        public float RepeatInterval;
        [DataMember(Name = "repeat_target")]
        public uint RepeatTarget;
        [DataMember(Name = "angle_step")]
        public float AngleStep;
        [DataMember(Name = "next_step_delay")]
        public float NextStepDelay;
        [DataMember(Name = "repeat_count")]
        public uint RepeatCount;

        public RepeatStepInstance(
            ulong RepeatId,
            PatternType PatternType,
            EnemyTarget Target,
            float OffsetX,
            float OffsetY,
            float BaseAngleOffset,
            string TextureId,
            float Lifetime,
            uint Damage,
            float AngularSpeed,
            float SpeedAcceleration,
            float RepeatInterval,
            uint RepeatTarget,
            float AngleStep,
            float NextStepDelay,
            uint RepeatCount
        )
        {
            this.RepeatId = RepeatId;
            this.PatternType = PatternType;
            this.Target = Target;
            this.OffsetX = OffsetX;
            this.OffsetY = OffsetY;
            this.BaseAngleOffset = BaseAngleOffset;
            this.TextureId = TextureId;
            this.Lifetime = Lifetime;
            this.Damage = Damage;
            this.AngularSpeed = AngularSpeed;
            this.SpeedAcceleration = SpeedAcceleration;
            this.RepeatInterval = RepeatInterval;
            this.RepeatTarget = RepeatTarget;
            this.AngleStep = AngleStep;
            this.NextStepDelay = NextStepDelay;
            this.RepeatCount = RepeatCount;
        }

        public RepeatStepInstance()
        {
            this.PatternType = null!;
            this.TextureId = "";
        }
    }
}
