// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RingParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;

        public RingParams(
            float Speed,
            uint Count
        )
        {
            this.Speed = Speed;
            this.Count = Count;
        }

        public RingParams()
        {
        }
    }
}
