// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RingParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;
        [DataMember(Name = "line")]
        public uint Line;
        [DataMember(Name = "line_speed_step")]
        public float LineSpeedStep;

        public RingParams(
            float Speed,
            uint Count,
            uint Line,
            float LineSpeedStep
        )
        {
            this.Speed = Speed;
            this.Count = Count;
            this.Line = Line;
            this.LineSpeedStep = LineSpeedStep;
        }

        public RingParams()
        {
        }
    }
}
