// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotgunParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;
        [DataMember(Name = "line")]
        public uint Line;
        [DataMember(Name = "line_speed_step")]
        public float LineSpeedStep;
        [DataMember(Name = "spread")]
        public float Spread;
        [DataMember(Name = "speed_variance")]
        public float SpeedVariance;
        [DataMember(Name = "lifetime_variance")]
        public float LifetimeVariance;

        public ShotgunParams(
            float Speed,
            uint Count,
            uint Line,
            float LineSpeedStep,
            float Spread,
            float SpeedVariance,
            float LifetimeVariance
        )
        {
            this.Speed = Speed;
            this.Count = Count;
            this.Line = Line;
            this.LineSpeedStep = LineSpeedStep;
            this.Spread = Spread;
            this.SpeedVariance = SpeedVariance;
            this.LifetimeVariance = LifetimeVariance;
        }

        public ShotgunParams()
        {
        }
    }
}
