// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotgunParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;
        [DataMember(Name = "spread")]
        public float Spread;
        [DataMember(Name = "speed_variance")]
        public float SpeedVariance;
        [DataMember(Name = "lifetime_variance")]
        public float LifetimeVariance;

        public ShotgunParams(
            float Speed,
            uint Count,
            float Spread,
            float SpeedVariance,
            float LifetimeVariance
        )
        {
            this.Speed = Speed;
            this.Count = Count;
            this.Spread = Spread;
            this.SpeedVariance = SpeedVariance;
            this.LifetimeVariance = LifetimeVariance;
        }

        public ShotgunParams()
        {
        }
    }
}
