// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StatModifier
    {
        [DataMember(Name = "stat")]
        public StatKind Stat;
        [DataMember(Name = "amount")]
        public float Amount;
        [DataMember(Name = "mode")]
        public StatMode Mode;

        public StatModifier(
            StatKind Stat,
            float Amount,
            StatMode Mode
        )
        {
            this.Stat = Stat;
            this.Amount = Amount;
            this.Mode = Mode;
        }

        public StatModifier()
        {
        }
    }
}
