// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TextureEntry
    {
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "res_path")]
        public string ResPath;
        [DataMember(Name = "kind")]
        public TextureKind Kind;

        public TextureEntry(
            string TextureId,
            string ResPath,
            TextureKind Kind
        )
        {
            this.TextureId = TextureId;
            this.ResPath = ResPath;
            this.Kind = Kind;
        }

        public TextureEntry()
        {
            this.TextureId = "";
            this.ResPath = "";
        }
    }
}
