// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TriangleTile
    {
        [DataMember(Name = "tile_id")]
        public ulong TileId;
        [DataMember(Name = "hex_q")]
        public int HexQ;
        [DataMember(Name = "hex_r")]
        public int HexR;
        [DataMember(Name = "tri_index")]
        public byte TriIndex;
        [DataMember(Name = "chunk_index")]
        public long ChunkIndex;
        [DataMember(Name = "texture_id")]
        public string TextureId;
        [DataMember(Name = "rotation")]
        public byte Rotation;
        [DataMember(Name = "overlay_texture_id")]
        public string? OverlayTextureId;
        [DataMember(Name = "overlay_rotation")]
        public byte OverlayRotation;
        [DataMember(Name = "overlay_scale")]
        public float OverlayScale;
        [DataMember(Name = "biome_id")]
        public string BiomeId;
        [DataMember(Name = "region_id")]
        public ulong RegionId;

        public TriangleTile(
            ulong TileId,
            int HexQ,
            int HexR,
            byte TriIndex,
            long ChunkIndex,
            string TextureId,
            byte Rotation,
            string? OverlayTextureId,
            byte OverlayRotation,
            float OverlayScale,
            string BiomeId,
            ulong RegionId
        )
        {
            this.TileId = TileId;
            this.HexQ = HexQ;
            this.HexR = HexR;
            this.TriIndex = TriIndex;
            this.ChunkIndex = ChunkIndex;
            this.TextureId = TextureId;
            this.Rotation = Rotation;
            this.OverlayTextureId = OverlayTextureId;
            this.OverlayRotation = OverlayRotation;
            this.OverlayScale = OverlayScale;
            this.BiomeId = BiomeId;
            this.RegionId = RegionId;
        }

        public TriangleTile()
        {
            this.TextureId = "";
            this.BiomeId = "";
        }
    }
}
