// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VolleyParams
    {
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "count")]
        public uint Count;
        [DataMember(Name = "speed_variance")]
        public float SpeedVariance;
        [DataMember(Name = "angle_jitter")]
        public float AngleJitter;

        public VolleyParams(
            float Speed,
            uint Count,
            float SpeedVariance,
            float AngleJitter
        )
        {
            this.Speed = Speed;
            this.Count = Count;
            this.SpeedVariance = SpeedVariance;
            this.AngleJitter = AngleJitter;
        }

        public VolleyParams()
        {
        }
    }
}
