// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponBehavior
    {
        [DataMember(Name = "damage")]
        public uint Damage;
        [DataMember(Name = "range")]
        public float Range;
        [DataMember(Name = "fire_rate")]
        public float FireRate;
        [DataMember(Name = "projectile_speed")]
        public float ProjectileSpeed;
        [DataMember(Name = "shot_count")]
        public uint ShotCount;
        [DataMember(Name = "zone_count")]
        public uint ZoneCount;
        [DataMember(Name = "pierce")]
        public bool Pierce;
        [DataMember(Name = "projectile_texture_id")]
        public string ProjectileTextureId;
        [DataMember(Name = "pattern")]
        public WeaponPattern Pattern;
        [DataMember(Name = "spread_angle")]
        public float SpreadAngle;

        public WeaponBehavior(
            uint Damage,
            float Range,
            float FireRate,
            float ProjectileSpeed,
            uint ShotCount,
            uint ZoneCount,
            bool Pierce,
            string ProjectileTextureId,
            WeaponPattern Pattern,
            float SpreadAngle
        )
        {
            this.Damage = Damage;
            this.Range = Range;
            this.FireRate = FireRate;
            this.ProjectileSpeed = ProjectileSpeed;
            this.ShotCount = ShotCount;
            this.ZoneCount = ZoneCount;
            this.Pierce = Pierce;
            this.ProjectileTextureId = ProjectileTextureId;
            this.Pattern = Pattern;
            this.SpreadAngle = SpreadAngle;
        }

        public WeaponBehavior()
        {
            this.ProjectileTextureId = "";
        }
    }
}
