// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldDef
    {
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "biome_weights")]
        public System.Collections.Generic.List<BiomeWeight> BiomeWeights;

        public WorldDef(
            string WorldId,
            string DisplayName,
            System.Collections.Generic.List<BiomeWeight> BiomeWeights
        )
        {
            this.WorldId = WorldId;
            this.DisplayName = DisplayName;
            this.BiomeWeights = BiomeWeights;
        }

        public WorldDef()
        {
            this.WorldId = "";
            this.DisplayName = "";
            this.BiomeWeights = new();
        }
    }
}
