// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivateAbilityHandler(ReducerEventContext ctx, uint slotIndex, float targetX, float targetY);
        public event ActivateAbilityHandler? OnActivateAbility;

        public void ActivateAbility(uint slotIndex, float targetX, float targetY)
        {
            conn.InternalCallReducer(new Reducer.ActivateAbility(slotIndex, targetX, targetY));
        }

        public bool InvokeActivateAbility(ReducerEventContext ctx, Reducer.ActivateAbility args)
        {
            if (OnActivateAbility == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnActivateAbility(
                ctx,
                args.SlotIndex,
                args.TargetX,
                args.TargetY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivateAbility : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot_index")]
            public uint SlotIndex;
            [DataMember(Name = "target_x")]
            public float TargetX;
            [DataMember(Name = "target_y")]
            public float TargetY;

            public ActivateAbility(
                uint SlotIndex,
                float TargetX,
                float TargetY
            )
            {
                this.SlotIndex = SlotIndex;
                this.TargetX = TargetX;
                this.TargetY = TargetY;
            }

            public ActivateAbility()
            {
            }

            string IReducerArgs.ReducerName => "activate_ability";
        }
    }
}
