// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddChunksHandler(ReducerEventContext ctx, int chunkHexRadius, int chunkCols, int chunkRows, float hexOuterRadius);
        public event AddChunksHandler? OnAddChunks;

        public void AddChunks(int chunkHexRadius, int chunkCols, int chunkRows, float hexOuterRadius)
        {
            conn.InternalCallReducer(new Reducer.AddChunks(chunkHexRadius, chunkCols, chunkRows, hexOuterRadius));
        }

        public bool InvokeAddChunks(ReducerEventContext ctx, Reducer.AddChunks args)
        {
            if (OnAddChunks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddChunks(
                ctx,
                args.ChunkHexRadius,
                args.ChunkCols,
                args.ChunkRows,
                args.HexOuterRadius
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddChunks : Reducer, IReducerArgs
        {
            [DataMember(Name = "chunk_hex_radius")]
            public int ChunkHexRadius;
            [DataMember(Name = "chunk_cols")]
            public int ChunkCols;
            [DataMember(Name = "chunk_rows")]
            public int ChunkRows;
            [DataMember(Name = "hex_outer_radius")]
            public float HexOuterRadius;

            public AddChunks(
                int ChunkHexRadius,
                int ChunkCols,
                int ChunkRows,
                float HexOuterRadius
            )
            {
                this.ChunkHexRadius = ChunkHexRadius;
                this.ChunkCols = ChunkCols;
                this.ChunkRows = ChunkRows;
                this.HexOuterRadius = HexOuterRadius;
            }

            public AddChunks()
            {
            }

            string IReducerArgs.ReducerName => "add_chunks";
        }
    }
}
