// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AllocateStatHandler(ReducerEventContext ctx, SpacetimeDB.Types.StatKind stat, uint points);
        public event AllocateStatHandler? OnAllocateStat;

        public void AllocateStat(SpacetimeDB.Types.StatKind stat, uint points)
        {
            conn.InternalCallReducer(new Reducer.AllocateStat(stat, points));
        }

        public bool InvokeAllocateStat(ReducerEventContext ctx, Reducer.AllocateStat args)
        {
            if (OnAllocateStat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAllocateStat(
                ctx,
                args.Stat,
                args.Points
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AllocateStat : Reducer, IReducerArgs
        {
            [DataMember(Name = "stat")]
            public StatKind Stat;
            [DataMember(Name = "points")]
            public uint Points;

            public AllocateStat(
                StatKind Stat,
                uint Points
            )
            {
                this.Stat = Stat;
                this.Points = Points;
            }

            public AllocateStat()
            {
            }

            string IReducerArgs.ReducerName => "allocate_stat";
        }
    }
}
