// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyEnchantmentHandler(ReducerEventContext ctx, uint slotIndex, string enchantmentId);
        public event ApplyEnchantmentHandler? OnApplyEnchantment;

        public void ApplyEnchantment(uint slotIndex, string enchantmentId)
        {
            conn.InternalCallReducer(new Reducer.ApplyEnchantment(slotIndex, enchantmentId));
        }

        public bool InvokeApplyEnchantment(ReducerEventContext ctx, Reducer.ApplyEnchantment args)
        {
            if (OnApplyEnchantment == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyEnchantment(
                ctx,
                args.SlotIndex,
                args.EnchantmentId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyEnchantment : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot_index")]
            public uint SlotIndex;
            [DataMember(Name = "enchantment_id")]
            public string EnchantmentId;

            public ApplyEnchantment(
                uint SlotIndex,
                string EnchantmentId
            )
            {
                this.SlotIndex = SlotIndex;
                this.EnchantmentId = EnchantmentId;
            }

            public ApplyEnchantment()
            {
                this.EnchantmentId = "";
            }

            string IReducerArgs.ReducerName => "apply_enchantment";
        }
    }
}
