// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangeStatsHandler(ReducerEventContext ctx, string targetUsername, string profileName, int strength, int wisdom, int dexterity, int damageDealer, int supporter, int artisan);
        public event ChangeStatsHandler? OnChangeStats;

        public void ChangeStats(string targetUsername, string profileName, int strength, int wisdom, int dexterity, int damageDealer, int supporter, int artisan)
        {
            conn.InternalCallReducer(new Reducer.ChangeStats(targetUsername, profileName, strength, wisdom, dexterity, damageDealer, supporter, artisan));
        }

        public bool InvokeChangeStats(ReducerEventContext ctx, Reducer.ChangeStats args)
        {
            if (OnChangeStats == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangeStats(
                ctx,
                args.TargetUsername,
                args.ProfileName,
                args.Strength,
                args.Wisdom,
                args.Dexterity,
                args.DamageDealer,
                args.Supporter,
                args.Artisan
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangeStats : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_username")]
            public string TargetUsername;
            [DataMember(Name = "profile_name")]
            public string ProfileName;
            [DataMember(Name = "strength")]
            public int Strength;
            [DataMember(Name = "wisdom")]
            public int Wisdom;
            [DataMember(Name = "dexterity")]
            public int Dexterity;
            [DataMember(Name = "damage_dealer")]
            public int DamageDealer;
            [DataMember(Name = "supporter")]
            public int Supporter;
            [DataMember(Name = "artisan")]
            public int Artisan;

            public ChangeStats(
                string TargetUsername,
                string ProfileName,
                int Strength,
                int Wisdom,
                int Dexterity,
                int DamageDealer,
                int Supporter,
                int Artisan
            )
            {
                this.TargetUsername = TargetUsername;
                this.ProfileName = ProfileName;
                this.Strength = Strength;
                this.Wisdom = Wisdom;
                this.Dexterity = Dexterity;
                this.DamageDealer = DamageDealer;
                this.Supporter = Supporter;
                this.Artisan = Artisan;
            }

            public ChangeStats()
            {
                this.TargetUsername = "";
                this.ProfileName = "";
            }

            string IReducerArgs.ReducerName => "change_stats";
        }
    }
}
