// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ControlBulletsHandler(ReducerEventContext ctx, SpacetimeDB.Types.BulletControlKind kind, float x, float y, float radius, float targetX, float targetY);
        public event ControlBulletsHandler? OnControlBullets;

        public void ControlBullets(SpacetimeDB.Types.BulletControlKind kind, float x, float y, float radius, float targetX, float targetY)
        {
            conn.InternalCallReducer(new Reducer.ControlBullets(kind, x, y, radius, targetX, targetY));
        }

        public bool InvokeControlBullets(ReducerEventContext ctx, Reducer.ControlBullets args)
        {
            if (OnControlBullets == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnControlBullets(
                ctx,
                args.Kind,
                args.X,
                args.Y,
                args.Radius,
                args.TargetX,
                args.TargetY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ControlBullets : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public BulletControlKind Kind;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "radius")]
            public float Radius;
            [DataMember(Name = "target_x")]
            public float TargetX;
            [DataMember(Name = "target_y")]
            public float TargetY;

            public ControlBullets(
                BulletControlKind Kind,
                float X,
                float Y,
                float Radius,
                float TargetX,
                float TargetY
            )
            {
                this.Kind = Kind;
                this.X = X;
                this.Y = Y;
                this.Radius = Radius;
                this.TargetX = TargetX;
                this.TargetY = TargetY;
            }

            public ControlBullets()
            {
            }

            string IReducerArgs.ReducerName => "control_bullets";
        }
    }
}
