// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateProfileHandler(ReducerEventContext ctx, string profileName, string textureId);
        public event CreateProfileHandler? OnCreateProfile;

        public void CreateProfile(string profileName, string textureId)
        {
            conn.InternalCallReducer(new Reducer.CreateProfile(profileName, textureId));
        }

        public bool InvokeCreateProfile(ReducerEventContext ctx, Reducer.CreateProfile args)
        {
            if (OnCreateProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateProfile(
                ctx,
                args.ProfileName,
                args.TextureId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "profile_name")]
            public string ProfileName;
            [DataMember(Name = "texture_id")]
            public string TextureId;

            public CreateProfile(
                string ProfileName,
                string TextureId
            )
            {
                this.ProfileName = ProfileName;
                this.TextureId = TextureId;
            }

            public CreateProfile()
            {
                this.ProfileName = "";
                this.TextureId = "";
            }

            string IReducerArgs.ReducerName => "create_profile";
        }
    }
}
