// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteProfileHandler(ReducerEventContext ctx, ulong profileId);
        public event DeleteProfileHandler? OnDeleteProfile;

        public void DeleteProfile(ulong profileId)
        {
            conn.InternalCallReducer(new Reducer.DeleteProfile(profileId));
        }

        public bool InvokeDeleteProfile(ReducerEventContext ctx, Reducer.DeleteProfile args)
        {
            if (OnDeleteProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteProfile(
                ctx,
                args.ProfileId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "profile_id")]
            public ulong ProfileId;

            public DeleteProfile(ulong ProfileId)
            {
                this.ProfileId = ProfileId;
            }

            public DeleteProfile()
            {
            }

            string IReducerArgs.ReducerName => "delete_profile";
        }
    }
}
