// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DespawnEnemyHandler(ReducerEventContext ctx, ulong enemyId);
        public event DespawnEnemyHandler? OnDespawnEnemy;

        public void DespawnEnemy(ulong enemyId)
        {
            conn.InternalCallReducer(new Reducer.DespawnEnemy(enemyId));
        }

        public bool InvokeDespawnEnemy(ReducerEventContext ctx, Reducer.DespawnEnemy args)
        {
            if (OnDespawnEnemy == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDespawnEnemy(
                ctx,
                args.EnemyId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DespawnEnemy : Reducer, IReducerArgs
        {
            [DataMember(Name = "enemy_id")]
            public ulong EnemyId;

            public DespawnEnemy(ulong EnemyId)
            {
                this.EnemyId = EnemyId;
            }

            public DespawnEnemy()
            {
            }

            string IReducerArgs.ReducerName => "despawn_enemy";
        }
    }
}
