// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DropItemHandler(ReducerEventContext ctx, uint slotIndex);
        public event DropItemHandler? OnDropItem;

        public void DropItem(uint slotIndex)
        {
            conn.InternalCallReducer(new Reducer.DropItem(slotIndex));
        }

        public bool InvokeDropItem(ReducerEventContext ctx, Reducer.DropItem args)
        {
            if (OnDropItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDropItem(
                ctx,
                args.SlotIndex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DropItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot_index")]
            public uint SlotIndex;

            public DropItem(uint SlotIndex)
            {
                this.SlotIndex = SlotIndex;
            }

            public DropItem()
            {
            }

            string IReducerArgs.ReducerName => "drop_item";
        }
    }
}
