// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FlagPlayerHitHandler(ReducerEventContext ctx, SpacetimeDB.Identity hitPlayer);
        public event FlagPlayerHitHandler? OnFlagPlayerHit;

        public void FlagPlayerHit(SpacetimeDB.Identity hitPlayer)
        {
            conn.InternalCallReducer(new Reducer.FlagPlayerHit(hitPlayer));
        }

        public bool InvokeFlagPlayerHit(ReducerEventContext ctx, Reducer.FlagPlayerHit args)
        {
            if (OnFlagPlayerHit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFlagPlayerHit(
                ctx,
                args.HitPlayer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FlagPlayerHit : Reducer, IReducerArgs
        {
            [DataMember(Name = "hit_player")]
            public SpacetimeDB.Identity HitPlayer;

            public FlagPlayerHit(SpacetimeDB.Identity HitPlayer)
            {
                this.HitPlayer = HitPlayer;
            }

            public FlagPlayerHit()
            {
            }

            string IReducerArgs.ReducerName => "flag_player_hit";
        }
    }
}
