// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GenerateWorldManualHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.ManualBiomeInput> biomes);
        public event GenerateWorldManualHandler? OnGenerateWorldManual;

        public void GenerateWorldManual(System.Collections.Generic.List<SpacetimeDB.Types.ManualBiomeInput> biomes)
        {
            conn.InternalCallReducer(new Reducer.GenerateWorldManual(biomes));
        }

        public bool InvokeGenerateWorldManual(ReducerEventContext ctx, Reducer.GenerateWorldManual args)
        {
            if (OnGenerateWorldManual == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGenerateWorldManual(
                ctx,
                args.Biomes
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GenerateWorldManual : Reducer, IReducerArgs
        {
            [DataMember(Name = "biomes")]
            public System.Collections.Generic.List<ManualBiomeInput> Biomes;

            public GenerateWorldManual(System.Collections.Generic.List<ManualBiomeInput> Biomes)
            {
                this.Biomes = Biomes;
            }

            public GenerateWorldManual()
            {
                this.Biomes = new();
            }

            string IReducerArgs.ReducerName => "generate_world_manual";
        }
    }
}
