// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GenerateWorldProcHandler(ReducerEventContext ctx, string worldId, ulong seed);
        public event GenerateWorldProcHandler? OnGenerateWorldProc;

        public void GenerateWorldProc(string worldId, ulong seed)
        {
            conn.InternalCallReducer(new Reducer.GenerateWorldProc(worldId, seed));
        }

        public bool InvokeGenerateWorldProc(ReducerEventContext ctx, Reducer.GenerateWorldProc args)
        {
            if (OnGenerateWorldProc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGenerateWorldProc(
                ctx,
                args.WorldId,
                args.Seed
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GenerateWorldProc : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;
            [DataMember(Name = "seed")]
            public ulong Seed;

            public GenerateWorldProc(
                string WorldId,
                ulong Seed
            )
            {
                this.WorldId = WorldId;
                this.Seed = Seed;
            }

            public GenerateWorldProc()
            {
                this.WorldId = "";
            }

            string IReducerArgs.ReducerName => "generate_world_proc";
        }
    }
}
