// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinWorldHandler(ReducerEventContext ctx, ulong profileId);
        public event JoinWorldHandler? OnJoinWorld;

        public void JoinWorld(ulong profileId)
        {
            conn.InternalCallReducer(new Reducer.JoinWorld(profileId));
        }

        public bool InvokeJoinWorld(ReducerEventContext ctx, Reducer.JoinWorld args)
        {
            if (OnJoinWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinWorld(
                ctx,
                args.ProfileId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "profile_id")]
            public ulong ProfileId;

            public JoinWorld(ulong ProfileId)
            {
                this.ProfileId = ProfileId;
            }

            public JoinWorld()
            {
            }

            string IReducerArgs.ReducerName => "join_world";
        }
    }
}
