// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PickupDropHandler(ReducerEventContext ctx, ulong dropId);
        public event PickupDropHandler? OnPickupDrop;

        public void PickupDrop(ulong dropId)
        {
            conn.InternalCallReducer(new Reducer.PickupDrop(dropId));
        }

        public bool InvokePickupDrop(ReducerEventContext ctx, Reducer.PickupDrop args)
        {
            if (OnPickupDrop == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPickupDrop(
                ctx,
                args.DropId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PickupDrop : Reducer, IReducerArgs
        {
            [DataMember(Name = "drop_id")]
            public ulong DropId;

            public PickupDrop(ulong DropId)
            {
                this.DropId = DropId;
            }

            public PickupDrop()
            {
            }

            string IReducerArgs.ReducerName => "pickup_drop";
        }
    }
}
