// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceBuildingHandler(ReducerEventContext ctx, int hexQ, int hexR, string buildingType);
        public event PlaceBuildingHandler? OnPlaceBuilding;

        public void PlaceBuilding(int hexQ, int hexR, string buildingType)
        {
            conn.InternalCallReducer(new Reducer.PlaceBuilding(hexQ, hexR, buildingType));
        }

        public bool InvokePlaceBuilding(ReducerEventContext ctx, Reducer.PlaceBuilding args)
        {
            if (OnPlaceBuilding == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceBuilding(
                ctx,
                args.HexQ,
                args.HexR,
                args.BuildingType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceBuilding : Reducer, IReducerArgs
        {
            [DataMember(Name = "hex_q")]
            public int HexQ;
            [DataMember(Name = "hex_r")]
            public int HexR;
            [DataMember(Name = "building_type")]
            public string BuildingType;

            public PlaceBuilding(
                int HexQ,
                int HexR,
                string BuildingType
            )
            {
                this.HexQ = HexQ;
                this.HexR = HexR;
                this.BuildingType = BuildingType;
            }

            public PlaceBuilding()
            {
                this.BuildingType = "";
            }

            string IReducerArgs.ReducerName => "place_building";
        }
    }
}
