// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReleaseAdminHandler(ReducerEventContext ctx);
        public event ReleaseAdminHandler? OnReleaseAdmin;

        public void ReleaseAdmin()
        {
            conn.InternalCallReducer(new Reducer.ReleaseAdmin());
        }

        public bool InvokeReleaseAdmin(ReducerEventContext ctx, Reducer.ReleaseAdmin args)
        {
            if (OnReleaseAdmin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReleaseAdmin(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReleaseAdmin : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "release_admin";
        }
    }
}
