// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveItemHandler(ReducerEventContext ctx, string targetUsername, string profileName, string itemId);
        public event RemoveItemHandler? OnRemoveItem;

        public void RemoveItem(string targetUsername, string profileName, string itemId)
        {
            conn.InternalCallReducer(new Reducer.RemoveItem(targetUsername, profileName, itemId));
        }

        public bool InvokeRemoveItem(ReducerEventContext ctx, Reducer.RemoveItem args)
        {
            if (OnRemoveItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveItem(
                ctx,
                args.TargetUsername,
                args.ProfileName,
                args.ItemId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_username")]
            public string TargetUsername;
            [DataMember(Name = "profile_name")]
            public string ProfileName;
            [DataMember(Name = "item_id")]
            public string ItemId;

            public RemoveItem(
                string TargetUsername,
                string ProfileName,
                string ItemId
            )
            {
                this.TargetUsername = TargetUsername;
                this.ProfileName = ProfileName;
                this.ItemId = ItemId;
            }

            public RemoveItem()
            {
                this.TargetUsername = "";
                this.ProfileName = "";
                this.ItemId = "";
            }

            string IReducerArgs.ReducerName => "remove_item";
        }
    }
}
