// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveBuildingHandler(ReducerEventContext ctx, int hexQ, int hexR);
        public event RemoveBuildingHandler? OnRemoveBuilding;

        public void RemoveBuilding(int hexQ, int hexR)
        {
            conn.InternalCallReducer(new Reducer.RemoveBuilding(hexQ, hexR));
        }

        public bool InvokeRemoveBuilding(ReducerEventContext ctx, Reducer.RemoveBuilding args)
        {
            if (OnRemoveBuilding == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveBuilding(
                ctx,
                args.HexQ,
                args.HexR
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveBuilding : Reducer, IReducerArgs
        {
            [DataMember(Name = "hex_q")]
            public int HexQ;
            [DataMember(Name = "hex_r")]
            public int HexR;

            public RemoveBuilding(
                int HexQ,
                int HexR
            )
            {
                this.HexQ = HexQ;
                this.HexR = HexR;
            }

            public RemoveBuilding()
            {
            }

            string IReducerArgs.ReducerName => "remove_building";
        }
    }
}
