// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportScreenRotationHandler(ReducerEventContext ctx, float screenRotation);
        public event ReportScreenRotationHandler? OnReportScreenRotation;

        public void ReportScreenRotation(float screenRotation)
        {
            conn.InternalCallReducer(new Reducer.ReportScreenRotation(screenRotation));
        }

        public bool InvokeReportScreenRotation(ReducerEventContext ctx, Reducer.ReportScreenRotation args)
        {
            if (OnReportScreenRotation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportScreenRotation(
                ctx,
                args.ScreenRotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportScreenRotation : Reducer, IReducerArgs
        {
            [DataMember(Name = "screen_rotation")]
            public float ScreenRotation;

            public ReportScreenRotation(float ScreenRotation)
            {
                this.ScreenRotation = ScreenRotation;
            }

            public ReportScreenRotation()
            {
            }

            string IReducerArgs.ReducerName => "report_screen_rotation";
        }
    }
}
