// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportHitHandler(ReducerEventContext ctx, SpacetimeDB.Types.SequenceStepRef attack);
        public event ReportHitHandler? OnReportHit;

        public void ReportHit(SpacetimeDB.Types.SequenceStepRef attack)
        {
            conn.InternalCallReducer(new Reducer.ReportHit(attack));
        }

        public bool InvokeReportHit(ReducerEventContext ctx, Reducer.ReportHit args)
        {
            if (OnReportHit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportHit(
                ctx,
                args.Attack
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportHit : Reducer, IReducerArgs
        {
            [DataMember(Name = "attack")]
            public SequenceStepRef Attack;

            public ReportHit(SequenceStepRef Attack)
            {
                this.Attack = Attack;
            }

            public ReportHit()
            {
                this.Attack = null!;
            }

            string IReducerArgs.ReducerName => "report_hit";
        }
    }
}
