// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportMovementHandler(ReducerEventContext ctx, float x, float y, float rotation);
        public event ReportMovementHandler? OnReportMovement;

        public void ReportMovement(float x, float y, float rotation)
        {
            conn.InternalCallReducer(new Reducer.ReportMovement(x, y, rotation));
        }

        public bool InvokeReportMovement(ReducerEventContext ctx, Reducer.ReportMovement args)
        {
            if (OnReportMovement == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportMovement(
                ctx,
                args.X,
                args.Y,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportMovement : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "rotation")]
            public float Rotation;

            public ReportMovement(
                float X,
                float Y,
                float Rotation
            )
            {
                this.X = X;
                this.Y = Y;
                this.Rotation = Rotation;
            }

            public ReportMovement()
            {
            }

            string IReducerArgs.ReducerName => "report_movement";
        }
    }
}
