// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportEnemyHitHandler(ReducerEventContext ctx, ulong enemyId);
        public event ReportEnemyHitHandler? OnReportEnemyHit;

        public void ReportEnemyHit(ulong enemyId)
        {
            conn.InternalCallReducer(new Reducer.ReportEnemyHit(enemyId));
        }

        public bool InvokeReportEnemyHit(ReducerEventContext ctx, Reducer.ReportEnemyHit args)
        {
            if (OnReportEnemyHit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportEnemyHit(
                ctx,
                args.EnemyId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportEnemyHit : Reducer, IReducerArgs
        {
            [DataMember(Name = "enemy_id")]
            public ulong EnemyId;

            public ReportEnemyHit(ulong EnemyId)
            {
                this.EnemyId = EnemyId;
            }

            public ReportEnemyHit()
            {
            }

            string IReducerArgs.ReducerName => "report_enemy_hit";
        }
    }
}
