// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetSlotToggleHandler(ReducerEventContext ctx, uint slotIndex, uint value);
        public event SetSlotToggleHandler? OnSetSlotToggle;

        public void SetSlotToggle(uint slotIndex, uint value)
        {
            conn.InternalCallReducer(new Reducer.SetSlotToggle(slotIndex, value));
        }

        public bool InvokeSetSlotToggle(ReducerEventContext ctx, Reducer.SetSlotToggle args)
        {
            if (OnSetSlotToggle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetSlotToggle(
                ctx,
                args.SlotIndex,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetSlotToggle : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot_index")]
            public uint SlotIndex;
            [DataMember(Name = "value")]
            public uint Value;

            public SetSlotToggle(
                uint SlotIndex,
                uint Value
            )
            {
                this.SlotIndex = SlotIndex;
                this.Value = Value;
            }

            public SetSlotToggle()
            {
            }

            string IReducerArgs.ReducerName => "set_slot_toggle";
        }
    }
}
