// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetUsernameHandler(ReducerEventContext ctx, string username);
        public event SetUsernameHandler? OnSetUsername;

        public void SetUsername(string username)
        {
            conn.InternalCallReducer(new Reducer.SetUsername(username));
        }

        public bool InvokeSetUsername(ReducerEventContext ctx, Reducer.SetUsername args)
        {
            if (OnSetUsername == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetUsername(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetUsername : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public SetUsername(string Username)
            {
                this.Username = Username;
            }

            public SetUsername()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "set_username";
        }
    }
}
