// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnEnemyHandler(ReducerEventContext ctx, string templateId, float x, float y, bool isElite, bool immortal);
        public event SpawnEnemyHandler? OnSpawnEnemy;

        public void SpawnEnemy(string templateId, float x, float y, bool isElite, bool immortal)
        {
            conn.InternalCallReducer(new Reducer.SpawnEnemy(templateId, x, y, isElite, immortal));
        }

        public bool InvokeSpawnEnemy(ReducerEventContext ctx, Reducer.SpawnEnemy args)
        {
            if (OnSpawnEnemy == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnEnemy(
                ctx,
                args.TemplateId,
                args.X,
                args.Y,
                args.IsElite,
                args.Immortal
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnEnemy : Reducer, IReducerArgs
        {
            [DataMember(Name = "template_id")]
            public string TemplateId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "is_elite")]
            public bool IsElite;
            [DataMember(Name = "immortal")]
            public bool Immortal;

            public SpawnEnemy(
                string TemplateId,
                float X,
                float Y,
                bool IsElite,
                bool Immortal
            )
            {
                this.TemplateId = TemplateId;
                this.X = X;
                this.Y = Y;
                this.IsElite = IsElite;
                this.Immortal = Immortal;
            }

            public SpawnEnemy()
            {
                this.TemplateId = "";
            }

            string IReducerArgs.ReducerName => "spawn_enemy";
        }
    }
}
