// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SwapSlotsHandler(ReducerEventContext ctx, uint fromIndex, uint toIndex);
        public event SwapSlotsHandler? OnSwapSlots;

        public void SwapSlots(uint fromIndex, uint toIndex)
        {
            conn.InternalCallReducer(new Reducer.SwapSlots(fromIndex, toIndex));
        }

        public bool InvokeSwapSlots(ReducerEventContext ctx, Reducer.SwapSlots args)
        {
            if (OnSwapSlots == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSwapSlots(
                ctx,
                args.FromIndex,
                args.ToIndex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SwapSlots : Reducer, IReducerArgs
        {
            [DataMember(Name = "from_index")]
            public uint FromIndex;
            [DataMember(Name = "to_index")]
            public uint ToIndex;

            public SwapSlots(
                uint FromIndex,
                uint ToIndex
            )
            {
                this.FromIndex = FromIndex;
                this.ToIndex = ToIndex;
            }

            public SwapSlots()
            {
            }

            string IReducerArgs.ReducerName => "swap_slots";
        }
    }
}
