// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ToggleDebugHandler(ReducerEventContext ctx);
        public event ToggleDebugHandler? OnToggleDebug;

        public void ToggleDebug()
        {
            conn.InternalCallReducer(new Reducer.ToggleDebug());
        }

        public bool InvokeToggleDebug(ReducerEventContext ctx, Reducer.ToggleDebug args)
        {
            if (OnToggleDebug == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnToggleDebug(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ToggleDebug : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "toggle_debug";
        }
    }
}
