// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertSingleStepDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.SingleStepDef def);
        public event UpsertSingleStepDefHandler? OnUpsertSingleStepDef;

        public void UpsertSingleStepDef(SpacetimeDB.Types.SingleStepDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertSingleStepDef(def));
        }

        public bool InvokeUpsertSingleStepDef(ReducerEventContext ctx, Reducer.UpsertSingleStepDef args)
        {
            if (OnUpsertSingleStepDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertSingleStepDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertSingleStepDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public SingleStepDef Def;

            public UpsertSingleStepDef(SingleStepDef Def)
            {
                this.Def = Def;
            }

            public UpsertSingleStepDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_single_step_def";
        }
    }
}
