// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertBiomeDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.BiomeDef def);
        public event UpsertBiomeDefHandler? OnUpsertBiomeDef;

        public void UpsertBiomeDef(SpacetimeDB.Types.BiomeDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertBiomeDef(def));
        }

        public bool InvokeUpsertBiomeDef(ReducerEventContext ctx, Reducer.UpsertBiomeDef args)
        {
            if (OnUpsertBiomeDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertBiomeDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertBiomeDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public BiomeDef Def;

            public UpsertBiomeDef(BiomeDef Def)
            {
                this.Def = Def;
            }

            public UpsertBiomeDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_biome_def";
        }
    }
}
