// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertItemHandler(ReducerEventContext ctx, SpacetimeDB.Types.Item item);
        public event UpsertItemHandler? OnUpsertItem;

        public void UpsertItem(SpacetimeDB.Types.Item item)
        {
            conn.InternalCallReducer(new Reducer.UpsertItem(item));
        }

        public bool InvokeUpsertItem(ReducerEventContext ctx, Reducer.UpsertItem args)
        {
            if (OnUpsertItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertItem(
                ctx,
                args.Item
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item")]
            public Item Item;

            public UpsertItem(Item Item)
            {
                this.Item = Item;
            }

            public UpsertItem()
            {
                this.Item = new();
            }

            string IReducerArgs.ReducerName => "upsert_item";
        }
    }
}
