// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertEnchantmentHandler(ReducerEventContext ctx, SpacetimeDB.Types.Enchantment enchantment);
        public event UpsertEnchantmentHandler? OnUpsertEnchantment;

        public void UpsertEnchantment(SpacetimeDB.Types.Enchantment enchantment)
        {
            conn.InternalCallReducer(new Reducer.UpsertEnchantment(enchantment));
        }

        public bool InvokeUpsertEnchantment(ReducerEventContext ctx, Reducer.UpsertEnchantment args)
        {
            if (OnUpsertEnchantment == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertEnchantment(
                ctx,
                args.Enchantment
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertEnchantment : Reducer, IReducerArgs
        {
            [DataMember(Name = "enchantment")]
            public Enchantment Enchantment;

            public UpsertEnchantment(Enchantment Enchantment)
            {
                this.Enchantment = Enchantment;
            }

            public UpsertEnchantment()
            {
                this.Enchantment = new();
            }

            string IReducerArgs.ReducerName => "upsert_enchantment";
        }
    }
}
