// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertTextureEntryHandler(ReducerEventContext ctx, SpacetimeDB.Types.TextureEntry entry);
        public event UpsertTextureEntryHandler? OnUpsertTextureEntry;

        public void UpsertTextureEntry(SpacetimeDB.Types.TextureEntry entry)
        {
            conn.InternalCallReducer(new Reducer.UpsertTextureEntry(entry));
        }

        public bool InvokeUpsertTextureEntry(ReducerEventContext ctx, Reducer.UpsertTextureEntry args)
        {
            if (OnUpsertTextureEntry == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertTextureEntry(
                ctx,
                args.Entry
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertTextureEntry : Reducer, IReducerArgs
        {
            [DataMember(Name = "entry")]
            public TextureEntry Entry;

            public UpsertTextureEntry(TextureEntry Entry)
            {
                this.Entry = Entry;
            }

            public UpsertTextureEntry()
            {
                this.Entry = new();
            }

            string IReducerArgs.ReducerName => "upsert_texture_entry";
        }
    }
}
