// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertWorldDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.WorldDef def);
        public event UpsertWorldDefHandler? OnUpsertWorldDef;

        public void UpsertWorldDef(SpacetimeDB.Types.WorldDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertWorldDef(def));
        }

        public bool InvokeUpsertWorldDef(ReducerEventContext ctx, Reducer.UpsertWorldDef args)
        {
            if (OnUpsertWorldDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertWorldDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertWorldDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public WorldDef Def;

            public UpsertWorldDef(WorldDef Def)
            {
                this.Def = Def;
            }

            public UpsertWorldDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_world_def";
        }
    }
}
