// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertEnemyTemplateHandler(ReducerEventContext ctx, SpacetimeDB.Types.EnemyTemplate template);
        public event UpsertEnemyTemplateHandler? OnUpsertEnemyTemplate;

        public void UpsertEnemyTemplate(SpacetimeDB.Types.EnemyTemplate template)
        {
            conn.InternalCallReducer(new Reducer.UpsertEnemyTemplate(template));
        }

        public bool InvokeUpsertEnemyTemplate(ReducerEventContext ctx, Reducer.UpsertEnemyTemplate args)
        {
            if (OnUpsertEnemyTemplate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertEnemyTemplate(
                ctx,
                args.Template
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertEnemyTemplate : Reducer, IReducerArgs
        {
            [DataMember(Name = "template")]
            public EnemyTemplate Template;

            public UpsertEnemyTemplate(EnemyTemplate Template)
            {
                this.Template = Template;
            }

            public UpsertEnemyTemplate()
            {
                this.Template = new();
            }

            string IReducerArgs.ReducerName => "upsert_enemy_template";
        }
    }
}
