// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertBiomeRegionDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.BiomeRegionDef def);
        public event UpsertBiomeRegionDefHandler? OnUpsertBiomeRegionDef;

        public void UpsertBiomeRegionDef(SpacetimeDB.Types.BiomeRegionDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertBiomeRegionDef(def));
        }

        public bool InvokeUpsertBiomeRegionDef(ReducerEventContext ctx, Reducer.UpsertBiomeRegionDef args)
        {
            if (OnUpsertBiomeRegionDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertBiomeRegionDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertBiomeRegionDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public BiomeRegionDef Def;

            public UpsertBiomeRegionDef(BiomeRegionDef Def)
            {
                this.Def = Def;
            }

            public UpsertBiomeRegionDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_biome_region_def";
        }
    }
}
