// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertRepeatStepDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.RepeatStepDef def);
        public event UpsertRepeatStepDefHandler? OnUpsertRepeatStepDef;

        public void UpsertRepeatStepDef(SpacetimeDB.Types.RepeatStepDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertRepeatStepDef(def));
        }

        public bool InvokeUpsertRepeatStepDef(ReducerEventContext ctx, Reducer.UpsertRepeatStepDef args)
        {
            if (OnUpsertRepeatStepDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertRepeatStepDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertRepeatStepDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public RepeatStepDef Def;

            public UpsertRepeatStepDef(RepeatStepDef Def)
            {
                this.Def = Def;
            }

            public UpsertRepeatStepDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_repeat_step_def";
        }
    }
}
