// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertMovementDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.MovementDef def);
        public event UpsertMovementDefHandler? OnUpsertMovementDef;

        public void UpsertMovementDef(SpacetimeDB.Types.MovementDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertMovementDef(def));
        }

        public bool InvokeUpsertMovementDef(ReducerEventContext ctx, Reducer.UpsertMovementDef args)
        {
            if (OnUpsertMovementDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertMovementDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertMovementDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public MovementDef Def;

            public UpsertMovementDef(MovementDef Def)
            {
                this.Def = Def;
            }

            public UpsertMovementDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_movement_def";
        }
    }
}
