// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertMultiStepDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.MultiStepDef def);
        public event UpsertMultiStepDefHandler? OnUpsertMultiStepDef;

        public void UpsertMultiStepDef(SpacetimeDB.Types.MultiStepDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertMultiStepDef(def));
        }

        public bool InvokeUpsertMultiStepDef(ReducerEventContext ctx, Reducer.UpsertMultiStepDef args)
        {
            if (OnUpsertMultiStepDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertMultiStepDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertMultiStepDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public MultiStepDef Def;

            public UpsertMultiStepDef(MultiStepDef Def)
            {
                this.Def = Def;
            }

            public UpsertMultiStepDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_multi_step_def";
        }
    }
}
