// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UseItemHandler(ReducerEventContext ctx, uint slotIndex);
        public event UseItemHandler? OnUseItem;

        public void UseItem(uint slotIndex)
        {
            conn.InternalCallReducer(new Reducer.UseItem(slotIndex));
        }

        public bool InvokeUseItem(ReducerEventContext ctx, Reducer.UseItem args)
        {
            if (OnUseItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUseItem(
                ctx,
                args.SlotIndex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UseItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "slot_index")]
            public uint SlotIndex;

            public UseItem(uint SlotIndex)
            {
                this.SlotIndex = SlotIndex;
            }

            public UseItem()
            {
            }

            string IReducerArgs.ReducerName => "use_item";
        }
    }
}
