// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveConsumableEffectHandle : RemoteTableHandle<EventContext, ActiveConsumableEffect>
        {
            public override string RemoteTableName => "active_consumable_effect";

            public sealed class EffectIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveConsumableEffect row) => row.EffectId;

                public EffectIdUniqueIndex(ActiveConsumableEffectHandle table) : base(table) { }
            }

            public readonly EffectIdUniqueIndex EffectId;

            public sealed class ProfileIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveConsumableEffect row) => row.ProfileId;

                public ProfileIdIndex(ActiveConsumableEffectHandle table) : base(table) { }
            }

            public readonly ProfileIdIndex ProfileId;

            internal ActiveConsumableEffectHandle(DbConnection conn) : base(conn)
            {
                EffectId = new(this);
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(ActiveConsumableEffect row) => row.EffectId;
        }

        public readonly ActiveConsumableEffectHandle ActiveConsumableEffect;
    }

    public sealed class ActiveConsumableEffectCols
    {
        public global::SpacetimeDB.Col<ActiveConsumableEffect, ulong> EffectId { get; }
        public global::SpacetimeDB.Col<ActiveConsumableEffect, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<ActiveConsumableEffect, StatModifier> Modifier { get; }
        public global::SpacetimeDB.Col<ActiveConsumableEffect, float> Remaining { get; }

        public ActiveConsumableEffectCols(string tableName)
        {
            EffectId = new global::SpacetimeDB.Col<ActiveConsumableEffect, ulong>(tableName, "effect_id");
            ProfileId = new global::SpacetimeDB.Col<ActiveConsumableEffect, ulong>(tableName, "profile_id");
            Modifier = new global::SpacetimeDB.Col<ActiveConsumableEffect, StatModifier>(tableName, "modifier");
            Remaining = new global::SpacetimeDB.Col<ActiveConsumableEffect, float>(tableName, "remaining");
        }
    }

    public sealed class ActiveConsumableEffectIxCols
    {
        public global::SpacetimeDB.IxCol<ActiveConsumableEffect, ulong> EffectId { get; }
        public global::SpacetimeDB.IxCol<ActiveConsumableEffect, ulong> ProfileId { get; }

        public ActiveConsumableEffectIxCols(string tableName)
        {
            EffectId = new global::SpacetimeDB.IxCol<ActiveConsumableEffect, ulong>(tableName, "effect_id");
            ProfileId = new global::SpacetimeDB.IxCol<ActiveConsumableEffect, ulong>(tableName, "profile_id");
        }
    }
}
