// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AllEnchantmentsHandle : RemoteTableHandle<EventContext, Enchantment>
        {
            public override string RemoteTableName => "all_enchantments";

            public sealed class EnchantmentIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Enchantment row) => row.EnchantmentId;

                public EnchantmentIdUniqueIndex(AllEnchantmentsHandle table) : base(table) { }
            }

            public readonly EnchantmentIdUniqueIndex EnchantmentId;

            internal AllEnchantmentsHandle(DbConnection conn) : base(conn)
            {
                EnchantmentId = new(this);
            }

            protected override object GetPrimaryKey(Enchantment row) => row.EnchantmentId;
        }

        public readonly AllEnchantmentsHandle AllEnchantments;
    }

    public sealed class AllEnchantmentsCols
    {
        public global::SpacetimeDB.Col<Enchantment, string> EnchantmentId { get; }
        public global::SpacetimeDB.Col<Enchantment, string> DisplayName { get; }
        public global::SpacetimeDB.Col<Enchantment, string> Description { get; }
        public global::SpacetimeDB.Col<Enchantment, string> TextureId { get; }
        public global::SpacetimeDB.Col<Enchantment, System.Collections.Generic.List<StatModifier>> StatModifiers { get; }
        public global::SpacetimeDB.Col<Enchantment, System.Collections.Generic.List<EquipSlot>> AllowedSlots { get; }

        public AllEnchantmentsCols(string tableName)
        {
            EnchantmentId = new global::SpacetimeDB.Col<Enchantment, string>(tableName, "enchantment_id");
            DisplayName = new global::SpacetimeDB.Col<Enchantment, string>(tableName, "display_name");
            Description = new global::SpacetimeDB.Col<Enchantment, string>(tableName, "description");
            TextureId = new global::SpacetimeDB.Col<Enchantment, string>(tableName, "texture_id");
            StatModifiers = new global::SpacetimeDB.Col<Enchantment, System.Collections.Generic.List<StatModifier>>(tableName, "stat_modifiers");
            AllowedSlots = new global::SpacetimeDB.Col<Enchantment, System.Collections.Generic.List<EquipSlot>>(tableName, "allowed_slots");
        }
    }

    public sealed class AllEnchantmentsIxCols
    {
        public global::SpacetimeDB.IxCol<Enchantment, string> EnchantmentId { get; }

        public AllEnchantmentsIxCols(string tableName)
        {
            EnchantmentId = new global::SpacetimeDB.IxCol<Enchantment, string>(tableName, "enchantment_id");
        }
    }
}
