// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AllItemsHandle : RemoteTableHandle<EventContext, Item>
        {
            public override string RemoteTableName => "all_items";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Item row) => row.ItemId;

                public ItemIdUniqueIndex(AllItemsHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            internal AllItemsHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
            }

            protected override object GetPrimaryKey(Item row) => row.ItemId;
        }

        public readonly AllItemsHandle AllItems;
    }

    public sealed class AllItemsCols
    {
        public global::SpacetimeDB.Col<Item, string> ItemId { get; }
        public global::SpacetimeDB.Col<Item, string> DisplayName { get; }
        public global::SpacetimeDB.Col<Item, string> Description { get; }
        public global::SpacetimeDB.Col<Item, string> TextureId { get; }
        public global::SpacetimeDB.Col<Item, EquipSlot> EquipSlot { get; }
        public global::SpacetimeDB.Col<Item, System.Collections.Generic.List<StatModifier>> StatModifiers { get; }
        public global::SpacetimeDB.Col<Item, System.Collections.Generic.List<ItemBehavior>> Behaviors { get; }
        public global::SpacetimeDB.Col<Item, uint> MaxEnchantments { get; }

        public AllItemsCols(string tableName)
        {
            ItemId = new global::SpacetimeDB.Col<Item, string>(tableName, "item_id");
            DisplayName = new global::SpacetimeDB.Col<Item, string>(tableName, "display_name");
            Description = new global::SpacetimeDB.Col<Item, string>(tableName, "description");
            TextureId = new global::SpacetimeDB.Col<Item, string>(tableName, "texture_id");
            EquipSlot = new global::SpacetimeDB.Col<Item, EquipSlot>(tableName, "equip_slot");
            StatModifiers = new global::SpacetimeDB.Col<Item, System.Collections.Generic.List<StatModifier>>(tableName, "stat_modifiers");
            Behaviors = new global::SpacetimeDB.Col<Item, System.Collections.Generic.List<ItemBehavior>>(tableName, "behaviors");
            MaxEnchantments = new global::SpacetimeDB.Col<Item, uint>(tableName, "max_enchantments");
        }
    }

    public sealed class AllItemsIxCols
    {
        public global::SpacetimeDB.IxCol<Item, string> ItemId { get; }

        public AllItemsIxCols(string tableName)
        {
            ItemId = new global::SpacetimeDB.IxCol<Item, string>(tableName, "item_id");
        }
    }
}
