// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseAdjacencyRuleHandle : RemoteTableHandle<EventContext, BaseAdjacencyRule>
        {
            public override string RemoteTableName => "base_adjacency_rule";

            public sealed class RuleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BaseAdjacencyRule row) => row.RuleId;

                public RuleIdUniqueIndex(BaseAdjacencyRuleHandle table) : base(table) { }
            }

            public readonly RuleIdUniqueIndex RuleId;

            internal BaseAdjacencyRuleHandle(DbConnection conn) : base(conn)
            {
                RuleId = new(this);
            }

            protected override object GetPrimaryKey(BaseAdjacencyRule row) => row.RuleId;
        }

        public readonly BaseAdjacencyRuleHandle BaseAdjacencyRule;
    }

    public sealed class BaseAdjacencyRuleCols
    {
        public global::SpacetimeDB.Col<BaseAdjacencyRule, ulong> RuleId { get; }
        public global::SpacetimeDB.Col<BaseAdjacencyRule, string> TagA { get; }
        public global::SpacetimeDB.Col<BaseAdjacencyRule, string> TagB { get; }

        public BaseAdjacencyRuleCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.Col<BaseAdjacencyRule, ulong>(tableName, "rule_id");
            TagA = new global::SpacetimeDB.Col<BaseAdjacencyRule, string>(tableName, "tag_a");
            TagB = new global::SpacetimeDB.Col<BaseAdjacencyRule, string>(tableName, "tag_b");
        }
    }

    public sealed class BaseAdjacencyRuleIxCols
    {
        public global::SpacetimeDB.IxCol<BaseAdjacencyRule, ulong> RuleId { get; }

        public BaseAdjacencyRuleIxCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.IxCol<BaseAdjacencyRule, ulong>(tableName, "rule_id");
        }
    }
}
