// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BiomeRegionDefHandle : RemoteTableHandle<EventContext, BiomeRegionDef>
        {
            public override string RemoteTableName => "biome_region_def";

            public sealed class RegionDefIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(BiomeRegionDef row) => row.RegionDefId;

                public RegionDefIdUniqueIndex(BiomeRegionDefHandle table) : base(table) { }
            }

            public readonly RegionDefIdUniqueIndex RegionDefId;

            internal BiomeRegionDefHandle(DbConnection conn) : base(conn)
            {
                RegionDefId = new(this);
            }

            protected override object GetPrimaryKey(BiomeRegionDef row) => row.RegionDefId;
        }

        public readonly BiomeRegionDefHandle BiomeRegionDef;
    }

    public sealed class BiomeRegionDefCols
    {
        public global::SpacetimeDB.Col<BiomeRegionDef, string> RegionDefId { get; }
        public global::SpacetimeDB.Col<BiomeRegionDef, string> DisplayName { get; }
        public global::SpacetimeDB.Col<BiomeRegionDef, System.Collections.Generic.List<string>> EnemyTemplateIds { get; }
        public global::SpacetimeDB.Col<BiomeRegionDef, uint> MaxEnemies { get; }
        public global::SpacetimeDB.Col<BiomeRegionDef, float> SpawnRadius { get; }

        public BiomeRegionDefCols(string tableName)
        {
            RegionDefId = new global::SpacetimeDB.Col<BiomeRegionDef, string>(tableName, "region_def_id");
            DisplayName = new global::SpacetimeDB.Col<BiomeRegionDef, string>(tableName, "display_name");
            EnemyTemplateIds = new global::SpacetimeDB.Col<BiomeRegionDef, System.Collections.Generic.List<string>>(tableName, "enemy_template_ids");
            MaxEnemies = new global::SpacetimeDB.Col<BiomeRegionDef, uint>(tableName, "max_enemies");
            SpawnRadius = new global::SpacetimeDB.Col<BiomeRegionDef, float>(tableName, "spawn_radius");
        }
    }

    public sealed class BiomeRegionDefIxCols
    {
        public global::SpacetimeDB.IxCol<BiomeRegionDef, string> RegionDefId { get; }

        public BiomeRegionDefIxCols(string tableName)
        {
            RegionDefId = new global::SpacetimeDB.IxCol<BiomeRegionDef, string>(tableName, "region_def_id");
        }
    }
}
