// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BiomeRegionHandle : RemoteTableHandle<EventContext, BiomeRegion>
        {
            public override string RemoteTableName => "biome_region";

            public sealed class RegionIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BiomeRegion row) => row.RegionId;

                public RegionIdUniqueIndex(BiomeRegionHandle table) : base(table) { }
            }

            public readonly RegionIdUniqueIndex RegionId;

            internal BiomeRegionHandle(DbConnection conn) : base(conn)
            {
                RegionId = new(this);
            }

            protected override object GetPrimaryKey(BiomeRegion row) => row.RegionId;
        }

        public readonly BiomeRegionHandle BiomeRegion;
    }

    public sealed class BiomeRegionCols
    {
        public global::SpacetimeDB.Col<BiomeRegion, ulong> RegionId { get; }
        public global::SpacetimeDB.Col<BiomeRegion, string> BiomeId { get; }
        public global::SpacetimeDB.Col<BiomeRegion, int> CenterHexQ { get; }
        public global::SpacetimeDB.Col<BiomeRegion, int> CenterHexR { get; }
        public global::SpacetimeDB.Col<BiomeRegion, System.Collections.Generic.List<string>> EnemyTemplateIds { get; }
        public global::SpacetimeDB.Col<BiomeRegion, uint> MaxEnemies { get; }
        public global::SpacetimeDB.Col<BiomeRegion, float> SpawnRadius { get; }

        public BiomeRegionCols(string tableName)
        {
            RegionId = new global::SpacetimeDB.Col<BiomeRegion, ulong>(tableName, "region_id");
            BiomeId = new global::SpacetimeDB.Col<BiomeRegion, string>(tableName, "biome_id");
            CenterHexQ = new global::SpacetimeDB.Col<BiomeRegion, int>(tableName, "center_hex_q");
            CenterHexR = new global::SpacetimeDB.Col<BiomeRegion, int>(tableName, "center_hex_r");
            EnemyTemplateIds = new global::SpacetimeDB.Col<BiomeRegion, System.Collections.Generic.List<string>>(tableName, "enemy_template_ids");
            MaxEnemies = new global::SpacetimeDB.Col<BiomeRegion, uint>(tableName, "max_enemies");
            SpawnRadius = new global::SpacetimeDB.Col<BiomeRegion, float>(tableName, "spawn_radius");
        }
    }

    public sealed class BiomeRegionIxCols
    {
        public global::SpacetimeDB.IxCol<BiomeRegion, ulong> RegionId { get; }

        public BiomeRegionIxCols(string tableName)
        {
            RegionId = new global::SpacetimeDB.IxCol<BiomeRegion, ulong>(tableName, "region_id");
        }
    }
}
