// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BiomeDefHandle : RemoteTableHandle<EventContext, BiomeDef>
        {
            public override string RemoteTableName => "biome_def";

            public sealed class BiomeIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(BiomeDef row) => row.BiomeId;

                public BiomeIdUniqueIndex(BiomeDefHandle table) : base(table) { }
            }

            public readonly BiomeIdUniqueIndex BiomeId;

            internal BiomeDefHandle(DbConnection conn) : base(conn)
            {
                BiomeId = new(this);
            }

            protected override object GetPrimaryKey(BiomeDef row) => row.BiomeId;
        }

        public readonly BiomeDefHandle BiomeDef;
    }

    public sealed class BiomeDefCols
    {
        public global::SpacetimeDB.Col<BiomeDef, string> BiomeId { get; }
        public global::SpacetimeDB.Col<BiomeDef, string> DisplayName { get; }
        public global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<GroundTextureConfig>> GroundTextures { get; }
        public global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<OverlayTextureConfig>> OverlayTextures { get; }
        public global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<RegionWeight>> RegionWeights { get; }
        public global::SpacetimeDB.Col<BiomeDef, float> GroundNoiseScale { get; }
        public global::SpacetimeDB.Col<BiomeDef, float> OverlayNoiseScale { get; }
        public global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<DecorConfig>> DecorConfigs { get; }
        public global::SpacetimeDB.Col<BiomeDef, float> DecorNoiseScale { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> DecorMinSeparation { get; }

        public BiomeDefCols(string tableName)
        {
            BiomeId = new global::SpacetimeDB.Col<BiomeDef, string>(tableName, "biome_id");
            DisplayName = new global::SpacetimeDB.Col<BiomeDef, string>(tableName, "display_name");
            GroundTextures = new global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<GroundTextureConfig>>(tableName, "ground_textures");
            OverlayTextures = new global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<OverlayTextureConfig>>(tableName, "overlay_textures");
            RegionWeights = new global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<RegionWeight>>(tableName, "region_weights");
            GroundNoiseScale = new global::SpacetimeDB.Col<BiomeDef, float>(tableName, "ground_noise_scale");
            OverlayNoiseScale = new global::SpacetimeDB.Col<BiomeDef, float>(tableName, "overlay_noise_scale");
            DecorConfigs = new global::SpacetimeDB.Col<BiomeDef, System.Collections.Generic.List<DecorConfig>>(tableName, "decor_configs");
            DecorNoiseScale = new global::SpacetimeDB.Col<BiomeDef, float>(tableName, "decor_noise_scale");
            DecorMinSeparation = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "decor_min_separation");
        }
    }

    public sealed class BiomeDefIxCols
    {
        public global::SpacetimeDB.IxCol<BiomeDef, string> BiomeId { get; }

        public BiomeDefIxCols(string tableName)
        {
            BiomeId = new global::SpacetimeDB.IxCol<BiomeDef, string>(tableName, "biome_id");
        }
    }
}
