// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingTileHandle : RemoteTableHandle<EventContext, BuildingTile>
        {
            public override string RemoteTableName => "building_tile";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(BuildingTile row) => row.ChunkIndex;

                public ChunkIndexIndex(BuildingTileHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class HexQIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(BuildingTile row) => row.HexQ;

                public HexQIndex(BuildingTileHandle table) : base(table) { }
            }

            public readonly HexQIndex HexQ;

            public sealed class TileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BuildingTile row) => row.TileId;

                public TileIdUniqueIndex(BuildingTileHandle table) : base(table) { }
            }

            public readonly TileIdUniqueIndex TileId;

            internal BuildingTileHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                HexQ = new(this);
                TileId = new(this);
            }

            protected override object GetPrimaryKey(BuildingTile row) => row.TileId;
        }

        public readonly BuildingTileHandle BuildingTile;
    }

    public sealed class BuildingTileCols
    {
        public global::SpacetimeDB.Col<BuildingTile, ulong> TileId { get; }
        public global::SpacetimeDB.Col<BuildingTile, int> HexQ { get; }
        public global::SpacetimeDB.Col<BuildingTile, int> HexR { get; }
        public global::SpacetimeDB.Col<BuildingTile, int> ChunkQ { get; }
        public global::SpacetimeDB.Col<BuildingTile, int> ChunkR { get; }
        public global::SpacetimeDB.Col<BuildingTile, int> LocalIndex { get; }
        public global::SpacetimeDB.Col<BuildingTile, long> ChunkIndex { get; }
        public global::SpacetimeDB.Col<BuildingTile, string> BuildingType { get; }
        public global::SpacetimeDB.Col<BuildingTile, SpacetimeDB.Identity> OwnerId { get; }

        public BuildingTileCols(string tableName)
        {
            TileId = new global::SpacetimeDB.Col<BuildingTile, ulong>(tableName, "tile_id");
            HexQ = new global::SpacetimeDB.Col<BuildingTile, int>(tableName, "hex_q");
            HexR = new global::SpacetimeDB.Col<BuildingTile, int>(tableName, "hex_r");
            ChunkQ = new global::SpacetimeDB.Col<BuildingTile, int>(tableName, "chunk_q");
            ChunkR = new global::SpacetimeDB.Col<BuildingTile, int>(tableName, "chunk_r");
            LocalIndex = new global::SpacetimeDB.Col<BuildingTile, int>(tableName, "local_index");
            ChunkIndex = new global::SpacetimeDB.Col<BuildingTile, long>(tableName, "chunk_index");
            BuildingType = new global::SpacetimeDB.Col<BuildingTile, string>(tableName, "building_type");
            OwnerId = new global::SpacetimeDB.Col<BuildingTile, SpacetimeDB.Identity>(tableName, "owner_id");
        }
    }

    public sealed class BuildingTileIxCols
    {
        public global::SpacetimeDB.IxCol<BuildingTile, ulong> TileId { get; }
        public global::SpacetimeDB.IxCol<BuildingTile, int> HexQ { get; }
        public global::SpacetimeDB.IxCol<BuildingTile, long> ChunkIndex { get; }

        public BuildingTileIxCols(string tableName)
        {
            TileId = new global::SpacetimeDB.IxCol<BuildingTile, ulong>(tableName, "tile_id");
            HexQ = new global::SpacetimeDB.IxCol<BuildingTile, int>(tableName, "hex_q");
            ChunkIndex = new global::SpacetimeDB.IxCol<BuildingTile, long>(tableName, "chunk_index");
        }
    }
}
