// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BulletControlEventHandle : RemoteEventTableHandle<EventContext, BulletControlEvent>
        {
            public override string RemoteTableName => "bullet_control_event";

            public sealed class EventIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BulletControlEvent row) => row.EventId;

                public EventIdUniqueIndex(BulletControlEventHandle table) : base(table) { }
            }

            public readonly EventIdUniqueIndex EventId;

            internal BulletControlEventHandle(DbConnection conn) : base(conn)
            {
                EventId = new(this);
            }

            protected override object GetPrimaryKey(BulletControlEvent row) => row.EventId;
        }

        public readonly BulletControlEventHandle BulletControlEvent;
    }

    public sealed class BulletControlEventCols
    {
        public global::SpacetimeDB.Col<BulletControlEvent, ulong> EventId { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, BulletControlKind> Kind { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> X { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> Y { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> Radius { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> TargetX { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> TargetY { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, float> Duration { get; }
        public global::SpacetimeDB.Col<BulletControlEvent, SpacetimeDB.Identity> CastBy { get; }

        public BulletControlEventCols(string tableName)
        {
            EventId = new global::SpacetimeDB.Col<BulletControlEvent, ulong>(tableName, "event_id");
            Kind = new global::SpacetimeDB.Col<BulletControlEvent, BulletControlKind>(tableName, "kind");
            X = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "y");
            Radius = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "radius");
            TargetX = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "target_x");
            TargetY = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "target_y");
            Duration = new global::SpacetimeDB.Col<BulletControlEvent, float>(tableName, "duration");
            CastBy = new global::SpacetimeDB.Col<BulletControlEvent, SpacetimeDB.Identity>(tableName, "cast_by");
        }
    }

    public sealed class BulletControlEventIxCols
    {
        public global::SpacetimeDB.IxCol<BulletControlEvent, ulong> EventId { get; }

        public BulletControlEventIxCols(string tableName)
        {
            EventId = new global::SpacetimeDB.IxCol<BulletControlEvent, ulong>(tableName, "event_id");
        }
    }
}
