// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BulletPatternEventHandle : RemoteEventTableHandle<EventContext, BulletPatternEvent>
        {
            public override string RemoteTableName => "bullet_pattern_event";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(BulletPatternEvent row) => row.ChunkIndex;

                public ChunkIndexIndex(BulletPatternEventHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class EventIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BulletPatternEvent row) => row.EventId;

                public EventIdUniqueIndex(BulletPatternEventHandle table) : base(table) { }
            }

            public readonly EventIdUniqueIndex EventId;

            internal BulletPatternEventHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                EventId = new(this);
            }

            protected override object GetPrimaryKey(BulletPatternEvent row) => row.EventId;
        }

        public readonly BulletPatternEventHandle BulletPatternEvent;
    }

    public sealed class BulletPatternEventCols
    {
        public global::SpacetimeDB.Col<BulletPatternEvent, ulong> EventId { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, ulong> EnemyId { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, SequenceStepRef> SourceStep { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> OriginX { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> OriginY { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> OriginOffsetX { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> OriginOffsetY { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> BaseAngleOffset { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, PatternType> PatternType { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, SpacetimeDB.Identity> Target { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, string> TextureId { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, float> Lifetime { get; }
        public global::SpacetimeDB.Col<BulletPatternEvent, long> ChunkIndex { get; }

        public BulletPatternEventCols(string tableName)
        {
            EventId = new global::SpacetimeDB.Col<BulletPatternEvent, ulong>(tableName, "event_id");
            EnemyId = new global::SpacetimeDB.Col<BulletPatternEvent, ulong>(tableName, "enemy_id");
            SourceStep = new global::SpacetimeDB.Col<BulletPatternEvent, SequenceStepRef>(tableName, "source_step");
            OriginX = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "origin_x");
            OriginY = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "origin_y");
            OriginOffsetX = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "origin_offset_x");
            OriginOffsetY = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "origin_offset_y");
            BaseAngleOffset = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "base_angle_offset");
            PatternType = new global::SpacetimeDB.Col<BulletPatternEvent, PatternType>(tableName, "pattern_type");
            Target = new global::SpacetimeDB.Col<BulletPatternEvent, SpacetimeDB.Identity>(tableName, "target");
            TextureId = new global::SpacetimeDB.Col<BulletPatternEvent, string>(tableName, "texture_id");
            Lifetime = new global::SpacetimeDB.Col<BulletPatternEvent, float>(tableName, "lifetime");
            ChunkIndex = new global::SpacetimeDB.Col<BulletPatternEvent, long>(tableName, "chunk_index");
        }
    }

    public sealed class BulletPatternEventIxCols
    {
        public global::SpacetimeDB.IxCol<BulletPatternEvent, ulong> EventId { get; }
        public global::SpacetimeDB.IxCol<BulletPatternEvent, long> ChunkIndex { get; }

        public BulletPatternEventIxCols(string tableName)
        {
            EventId = new global::SpacetimeDB.IxCol<BulletPatternEvent, ulong>(tableName, "event_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<BulletPatternEvent, long>(tableName, "chunk_index");
        }
    }
}
