// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DecorGroundRuleHandle : RemoteTableHandle<EventContext, DecorGroundRule>
        {
            public override string RemoteTableName => "decor_ground_rule";

            public sealed class RuleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DecorGroundRule row) => row.RuleId;

                public RuleIdUniqueIndex(DecorGroundRuleHandle table) : base(table) { }
            }

            public readonly RuleIdUniqueIndex RuleId;

            internal DecorGroundRuleHandle(DbConnection conn) : base(conn)
            {
                RuleId = new(this);
            }

            protected override object GetPrimaryKey(DecorGroundRule row) => row.RuleId;
        }

        public readonly DecorGroundRuleHandle DecorGroundRule;
    }

    public sealed class DecorGroundRuleCols
    {
        public global::SpacetimeDB.Col<DecorGroundRule, ulong> RuleId { get; }
        public global::SpacetimeDB.Col<DecorGroundRule, string> DecorTag { get; }
        public global::SpacetimeDB.Col<DecorGroundRule, string> DeniedBaseTag { get; }

        public DecorGroundRuleCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.Col<DecorGroundRule, ulong>(tableName, "rule_id");
            DecorTag = new global::SpacetimeDB.Col<DecorGroundRule, string>(tableName, "decor_tag");
            DeniedBaseTag = new global::SpacetimeDB.Col<DecorGroundRule, string>(tableName, "denied_base_tag");
        }
    }

    public sealed class DecorGroundRuleIxCols
    {
        public global::SpacetimeDB.IxCol<DecorGroundRule, ulong> RuleId { get; }

        public DecorGroundRuleIxCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.IxCol<DecorGroundRule, ulong>(tableName, "rule_id");
        }
    }
}
