// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyBehaviorHandle : RemoteTableHandle<EventContext, EnemyBehavior>
        {
            public override string RemoteTableName => "enemy_behavior";

            public sealed class BehaviorIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyBehavior row) => row.BehaviorId;

                public BehaviorIdUniqueIndex(EnemyBehaviorHandle table) : base(table) { }
            }

            public readonly BehaviorIdUniqueIndex BehaviorId;

            internal EnemyBehaviorHandle(DbConnection conn) : base(conn)
            {
                BehaviorId = new(this);
            }

            protected override object GetPrimaryKey(EnemyBehavior row) => row.BehaviorId;
        }

        public readonly EnemyBehaviorHandle EnemyBehavior;
    }

    public sealed class EnemyBehaviorCols
    {
        public global::SpacetimeDB.Col<EnemyBehavior, ulong> BehaviorId { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, SpacetimeDB.Identity> AggroTarget { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, SpacetimeDB.Timestamp> AggroLockedUntil { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, bool> WasSimulating { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, byte> ActivePhaseIndex { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, float> VelocityX { get; }
        public global::SpacetimeDB.Col<EnemyBehavior, float> VelocityY { get; }

        public EnemyBehaviorCols(string tableName)
        {
            BehaviorId = new global::SpacetimeDB.Col<EnemyBehavior, ulong>(tableName, "behavior_id");
            AggroTarget = new global::SpacetimeDB.Col<EnemyBehavior, SpacetimeDB.Identity>(tableName, "aggro_target");
            AggroLockedUntil = new global::SpacetimeDB.Col<EnemyBehavior, SpacetimeDB.Timestamp>(tableName, "aggro_locked_until");
            WasSimulating = new global::SpacetimeDB.Col<EnemyBehavior, bool>(tableName, "was_simulating");
            ActivePhaseIndex = new global::SpacetimeDB.Col<EnemyBehavior, byte>(tableName, "active_phase_index");
            VelocityX = new global::SpacetimeDB.Col<EnemyBehavior, float>(tableName, "velocity_x");
            VelocityY = new global::SpacetimeDB.Col<EnemyBehavior, float>(tableName, "velocity_y");
        }
    }

    public sealed class EnemyBehaviorIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyBehavior, ulong> BehaviorId { get; }

        public EnemyBehaviorIxCols(string tableName)
        {
            BehaviorId = new global::SpacetimeDB.IxCol<EnemyBehavior, ulong>(tableName, "behavior_id");
        }
    }
}
