// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemySequenceStepHandle : RemoteTableHandle<EventContext, EnemySequenceStep>
        {
            public override string RemoteTableName => "enemy_sequence_step";

            public sealed class AttackIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EnemySequenceStep row) => row.AttackId;

                public AttackIdIndex(EnemySequenceStepHandle table) : base(table) { }
            }

            public readonly AttackIdIndex AttackId;

            public sealed class StepIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemySequenceStep row) => row.StepId;

                public StepIdUniqueIndex(EnemySequenceStepHandle table) : base(table) { }
            }

            public readonly StepIdUniqueIndex StepId;

            internal EnemySequenceStepHandle(DbConnection conn) : base(conn)
            {
                AttackId = new(this);
                StepId = new(this);
            }

            protected override object GetPrimaryKey(EnemySequenceStep row) => row.StepId;
        }

        public readonly EnemySequenceStepHandle EnemySequenceStep;
    }

    public sealed class EnemySequenceStepCols
    {
        public global::SpacetimeDB.Col<EnemySequenceStep, ulong> StepId { get; }
        public global::SpacetimeDB.Col<EnemySequenceStep, ulong> AttackId { get; }
        public global::SpacetimeDB.Col<EnemySequenceStep, uint> StepIndex { get; }
        public global::SpacetimeDB.Col<EnemySequenceStep, SequenceStepRef> Step { get; }

        public EnemySequenceStepCols(string tableName)
        {
            StepId = new global::SpacetimeDB.Col<EnemySequenceStep, ulong>(tableName, "step_id");
            AttackId = new global::SpacetimeDB.Col<EnemySequenceStep, ulong>(tableName, "attack_id");
            StepIndex = new global::SpacetimeDB.Col<EnemySequenceStep, uint>(tableName, "step_index");
            Step = new global::SpacetimeDB.Col<EnemySequenceStep, SequenceStepRef>(tableName, "step");
        }
    }

    public sealed class EnemySequenceStepIxCols
    {
        public global::SpacetimeDB.IxCol<EnemySequenceStep, ulong> StepId { get; }
        public global::SpacetimeDB.IxCol<EnemySequenceStep, ulong> AttackId { get; }

        public EnemySequenceStepIxCols(string tableName)
        {
            StepId = new global::SpacetimeDB.IxCol<EnemySequenceStep, ulong>(tableName, "step_id");
            AttackId = new global::SpacetimeDB.IxCol<EnemySequenceStep, ulong>(tableName, "attack_id");
        }
    }
}
