// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyPhasesHandle : RemoteTableHandle<EventContext, EnemyPhase>
        {
            public override string RemoteTableName => "enemy_phases";

            public sealed class BehaviorIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyPhase row) => row.BehaviorId;

                public BehaviorIdIndex(EnemyPhasesHandle table) : base(table) { }
            }

            public readonly BehaviorIdIndex BehaviorId;

            public sealed class PhaseIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyPhase row) => row.PhaseId;

                public PhaseIdUniqueIndex(EnemyPhasesHandle table) : base(table) { }
            }

            public readonly PhaseIdUniqueIndex PhaseId;

            internal EnemyPhasesHandle(DbConnection conn) : base(conn)
            {
                BehaviorId = new(this);
                PhaseId = new(this);
            }

            protected override object GetPrimaryKey(EnemyPhase row) => row.PhaseId;
        }

        public readonly EnemyPhasesHandle EnemyPhases;
    }

    public sealed class EnemyPhasesCols
    {
        public global::SpacetimeDB.Col<EnemyPhase, ulong> PhaseId { get; }
        public global::SpacetimeDB.Col<EnemyPhase, ulong> BehaviorId { get; }
        public global::SpacetimeDB.Col<EnemyPhase, byte> PhaseIndex { get; }
        public global::SpacetimeDB.Col<EnemyPhase, float> HpThreshold { get; }
        public global::SpacetimeDB.Col<EnemyPhase, ulong> MovementDefId { get; }
        public global::SpacetimeDB.Col<EnemyPhase, float> PhaseLoopDelay { get; }
        public global::SpacetimeDB.Col<EnemyPhase, bool> PhaseWaiting { get; }
        public global::SpacetimeDB.Col<EnemyPhase, SpacetimeDB.Timestamp> PhaseLoopTimer { get; }
        public global::SpacetimeDB.Col<EnemyPhase, SpacetimeDB.Timestamp> MoveCycleStartedAt { get; }

        public EnemyPhasesCols(string tableName)
        {
            PhaseId = new global::SpacetimeDB.Col<EnemyPhase, ulong>(tableName, "phase_id");
            BehaviorId = new global::SpacetimeDB.Col<EnemyPhase, ulong>(tableName, "behavior_id");
            PhaseIndex = new global::SpacetimeDB.Col<EnemyPhase, byte>(tableName, "phase_index");
            HpThreshold = new global::SpacetimeDB.Col<EnemyPhase, float>(tableName, "hp_threshold");
            MovementDefId = new global::SpacetimeDB.Col<EnemyPhase, ulong>(tableName, "movement_def_id");
            PhaseLoopDelay = new global::SpacetimeDB.Col<EnemyPhase, float>(tableName, "phase_loop_delay");
            PhaseWaiting = new global::SpacetimeDB.Col<EnemyPhase, bool>(tableName, "phase_waiting");
            PhaseLoopTimer = new global::SpacetimeDB.Col<EnemyPhase, SpacetimeDB.Timestamp>(tableName, "phase_loop_timer");
            MoveCycleStartedAt = new global::SpacetimeDB.Col<EnemyPhase, SpacetimeDB.Timestamp>(tableName, "move_cycle_started_at");
        }
    }

    public sealed class EnemyPhasesIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyPhase, ulong> PhaseId { get; }
        public global::SpacetimeDB.IxCol<EnemyPhase, ulong> BehaviorId { get; }

        public EnemyPhasesIxCols(string tableName)
        {
            PhaseId = new global::SpacetimeDB.IxCol<EnemyPhase, ulong>(tableName, "phase_id");
            BehaviorId = new global::SpacetimeDB.IxCol<EnemyPhase, ulong>(tableName, "behavior_id");
        }
    }
}
