// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyAttackHandle : RemoteTableHandle<EventContext, EnemyAttack>
        {
            public override string RemoteTableName => "enemy_attack";

            public sealed class AttackIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyAttack row) => row.AttackId;

                public AttackIdUniqueIndex(EnemyAttackHandle table) : base(table) { }
            }

            public readonly AttackIdUniqueIndex AttackId;

            public sealed class PhaseIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyAttack row) => row.PhaseId;

                public PhaseIdIndex(EnemyAttackHandle table) : base(table) { }
            }

            public readonly PhaseIdIndex PhaseId;

            internal EnemyAttackHandle(DbConnection conn) : base(conn)
            {
                AttackId = new(this);
                PhaseId = new(this);
            }

            protected override object GetPrimaryKey(EnemyAttack row) => row.AttackId;
        }

        public readonly EnemyAttackHandle EnemyAttack;
    }

    public sealed class EnemyAttackCols
    {
        public global::SpacetimeDB.Col<EnemyAttack, ulong> AttackId { get; }
        public global::SpacetimeDB.Col<EnemyAttack, ulong> PhaseId { get; }
        public global::SpacetimeDB.Col<EnemyAttack, uint> AttackIndex { get; }
        public global::SpacetimeDB.Col<EnemyAttack, uint> StepIndex { get; }
        public global::SpacetimeDB.Col<EnemyAttack, SpacetimeDB.Timestamp> StepTimer { get; }
        public global::SpacetimeDB.Col<EnemyAttack, bool> StepWaiting { get; }
        public global::SpacetimeDB.Col<EnemyAttack, bool> StartDelaying { get; }
        public global::SpacetimeDB.Col<EnemyAttack, bool> LoopWaiting { get; }

        public EnemyAttackCols(string tableName)
        {
            AttackId = new global::SpacetimeDB.Col<EnemyAttack, ulong>(tableName, "attack_id");
            PhaseId = new global::SpacetimeDB.Col<EnemyAttack, ulong>(tableName, "phase_id");
            AttackIndex = new global::SpacetimeDB.Col<EnemyAttack, uint>(tableName, "attack_index");
            StepIndex = new global::SpacetimeDB.Col<EnemyAttack, uint>(tableName, "step_index");
            StepTimer = new global::SpacetimeDB.Col<EnemyAttack, SpacetimeDB.Timestamp>(tableName, "step_timer");
            StepWaiting = new global::SpacetimeDB.Col<EnemyAttack, bool>(tableName, "step_waiting");
            StartDelaying = new global::SpacetimeDB.Col<EnemyAttack, bool>(tableName, "start_delaying");
            LoopWaiting = new global::SpacetimeDB.Col<EnemyAttack, bool>(tableName, "loop_waiting");
        }
    }

    public sealed class EnemyAttackIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyAttack, ulong> AttackId { get; }
        public global::SpacetimeDB.IxCol<EnemyAttack, ulong> PhaseId { get; }

        public EnemyAttackIxCols(string tableName)
        {
            AttackId = new global::SpacetimeDB.IxCol<EnemyAttack, ulong>(tableName, "attack_id");
            PhaseId = new global::SpacetimeDB.IxCol<EnemyAttack, ulong>(tableName, "phase_id");
        }
    }
}
