// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyTemplatesHandle : RemoteTableHandle<EventContext, EnemyTemplate>
        {
            public override string RemoteTableName => "enemy_templates";

            public sealed class TemplateIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EnemyTemplate row) => row.TemplateId;

                public TemplateIdUniqueIndex(EnemyTemplatesHandle table) : base(table) { }
            }

            public readonly TemplateIdUniqueIndex TemplateId;

            internal EnemyTemplatesHandle(DbConnection conn) : base(conn)
            {
                TemplateId = new(this);
            }

            protected override object GetPrimaryKey(EnemyTemplate row) => row.TemplateId;
        }

        public readonly EnemyTemplatesHandle EnemyTemplates;
    }

    public sealed class EnemyTemplatesCols
    {
        public global::SpacetimeDB.Col<EnemyTemplate, string> TemplateId { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, string> TextureId { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, string> DisplayName { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, uint> MaxHp { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, uint> Defense { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, float> MoveSimFactor { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, float> AttackSimFactor { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, float> AggroLockSeconds { get; }
        public global::SpacetimeDB.Col<EnemyTemplate, System.Collections.Generic.List<PhaseDef>> Phases { get; }

        public EnemyTemplatesCols(string tableName)
        {
            TemplateId = new global::SpacetimeDB.Col<EnemyTemplate, string>(tableName, "template_id");
            TextureId = new global::SpacetimeDB.Col<EnemyTemplate, string>(tableName, "texture_id");
            DisplayName = new global::SpacetimeDB.Col<EnemyTemplate, string>(tableName, "display_name");
            MaxHp = new global::SpacetimeDB.Col<EnemyTemplate, uint>(tableName, "max_hp");
            Defense = new global::SpacetimeDB.Col<EnemyTemplate, uint>(tableName, "defense");
            MoveSimFactor = new global::SpacetimeDB.Col<EnemyTemplate, float>(tableName, "move_sim_factor");
            AttackSimFactor = new global::SpacetimeDB.Col<EnemyTemplate, float>(tableName, "attack_sim_factor");
            AggroLockSeconds = new global::SpacetimeDB.Col<EnemyTemplate, float>(tableName, "aggro_lock_seconds");
            Phases = new global::SpacetimeDB.Col<EnemyTemplate, System.Collections.Generic.List<PhaseDef>>(tableName, "phases");
        }
    }

    public sealed class EnemyTemplatesIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyTemplate, string> TemplateId { get; }

        public EnemyTemplatesIxCols(string tableName)
        {
            TemplateId = new global::SpacetimeDB.IxCol<EnemyTemplate, string>(tableName, "template_id");
        }
    }
}
