// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyHandle : RemoteTableHandle<EventContext, Enemy>
        {
            public override string RemoteTableName => "enemy";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(Enemy row) => row.ChunkIndex;

                public ChunkIndexIndex(EnemyHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class EnemyIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Enemy row) => row.EnemyId;

                public EnemyIdUniqueIndex(EnemyHandle table) : base(table) { }
            }

            public readonly EnemyIdUniqueIndex EnemyId;

            internal EnemyHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                EnemyId = new(this);
            }

            protected override object GetPrimaryKey(Enemy row) => row.EnemyId;
        }

        public readonly EnemyHandle Enemy;
    }

    public sealed class EnemyCols
    {
        public global::SpacetimeDB.Col<Enemy, ulong> EnemyId { get; }
        public global::SpacetimeDB.Col<Enemy, string> TemplateId { get; }
        public global::SpacetimeDB.Col<Enemy, ulong> BehaviorId { get; }
        public global::SpacetimeDB.Col<Enemy, float> X { get; }
        public global::SpacetimeDB.Col<Enemy, float> Y { get; }
        public global::SpacetimeDB.Col<Enemy, SpacetimeDB.Timestamp> SpawnTime { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Hp { get; }
        public global::SpacetimeDB.Col<Enemy, byte> Phase { get; }
        public global::SpacetimeDB.Col<Enemy, bool> IsElite { get; }
        public global::SpacetimeDB.Col<Enemy, bool> Immortal { get; }
        public global::SpacetimeDB.Col<Enemy, long> ChunkIndex { get; }

        public EnemyCols(string tableName)
        {
            EnemyId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "enemy_id");
            TemplateId = new global::SpacetimeDB.Col<Enemy, string>(tableName, "template_id");
            BehaviorId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "behavior_id");
            X = new global::SpacetimeDB.Col<Enemy, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<Enemy, float>(tableName, "y");
            SpawnTime = new global::SpacetimeDB.Col<Enemy, SpacetimeDB.Timestamp>(tableName, "spawn_time");
            Hp = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "hp");
            Phase = new global::SpacetimeDB.Col<Enemy, byte>(tableName, "phase");
            IsElite = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "is_elite");
            Immortal = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "immortal");
            ChunkIndex = new global::SpacetimeDB.Col<Enemy, long>(tableName, "chunk_index");
        }
    }

    public sealed class EnemyIxCols
    {
        public global::SpacetimeDB.IxCol<Enemy, ulong> EnemyId { get; }
        public global::SpacetimeDB.IxCol<Enemy, long> ChunkIndex { get; }

        public EnemyIxCols(string tableName)
        {
            EnemyId = new global::SpacetimeDB.IxCol<Enemy, ulong>(tableName, "enemy_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<Enemy, long>(tableName, "chunk_index");
        }
    }
}
