// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LayeringRuleHandle : RemoteTableHandle<EventContext, LayeringRule>
        {
            public override string RemoteTableName => "layering_rule";

            public sealed class RuleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LayeringRule row) => row.RuleId;

                public RuleIdUniqueIndex(LayeringRuleHandle table) : base(table) { }
            }

            public readonly RuleIdUniqueIndex RuleId;

            internal LayeringRuleHandle(DbConnection conn) : base(conn)
            {
                RuleId = new(this);
            }

            protected override object GetPrimaryKey(LayeringRule row) => row.RuleId;
        }

        public readonly LayeringRuleHandle LayeringRule;
    }

    public sealed class LayeringRuleCols
    {
        public global::SpacetimeDB.Col<LayeringRule, ulong> RuleId { get; }
        public global::SpacetimeDB.Col<LayeringRule, string> OverlayTag { get; }
        public global::SpacetimeDB.Col<LayeringRule, string> AllowedBaseTag { get; }

        public LayeringRuleCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.Col<LayeringRule, ulong>(tableName, "rule_id");
            OverlayTag = new global::SpacetimeDB.Col<LayeringRule, string>(tableName, "overlay_tag");
            AllowedBaseTag = new global::SpacetimeDB.Col<LayeringRule, string>(tableName, "allowed_base_tag");
        }
    }

    public sealed class LayeringRuleIxCols
    {
        public global::SpacetimeDB.IxCol<LayeringRule, ulong> RuleId { get; }

        public LayeringRuleIxCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.IxCol<LayeringRule, ulong>(tableName, "rule_id");
        }
    }
}
