// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalPlayerStatAllocationHandle : RemoteTableHandle<EventContext, PlayerStatAllocation>
        {
            public override string RemoteTableName => "local_player_stat_allocation";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerStatAllocation row) => row.ProfileId;

                public ProfileIdUniqueIndex(LocalPlayerStatAllocationHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal LocalPlayerStatAllocationHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerStatAllocation row) => row.ProfileId;
        }

        public readonly LocalPlayerStatAllocationHandle LocalPlayerStatAllocation;
    }

    public sealed class LocalPlayerStatAllocationCols
    {
        public global::SpacetimeDB.Col<PlayerStatAllocation, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> Strength { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> Wisdom { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> Dexterity { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> DamageDealer { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> Supporter { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> Artisan { get; }
        public global::SpacetimeDB.Col<PlayerStatAllocation, uint> UnspentPoints { get; }

        public LocalPlayerStatAllocationCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerStatAllocation, ulong>(tableName, "profile_id");
            Strength = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "strength");
            Wisdom = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "wisdom");
            Dexterity = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "dexterity");
            DamageDealer = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "damage_dealer");
            Supporter = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "supporter");
            Artisan = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "artisan");
            UnspentPoints = new global::SpacetimeDB.Col<PlayerStatAllocation, uint>(tableName, "unspent_points");
        }
    }

    public sealed class LocalPlayerStatAllocationIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStatAllocation, ulong> ProfileId { get; }

        public LocalPlayerStatAllocationIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerStatAllocation, ulong>(tableName, "profile_id");
        }
    }
}
