// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalLobbyPlayerHandle : RemoteTableHandle<EventContext, LoggedOutPlayer>
        {
            public override string RemoteTableName => "local_lobby_player";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(LoggedOutPlayer row) => row.PlayerId;

                public PlayerIdUniqueIndex(LocalLobbyPlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal LocalLobbyPlayerHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(LoggedOutPlayer row) => row.PlayerId;
        }

        public readonly LocalLobbyPlayerHandle LocalLobbyPlayer;
    }

    public sealed class LocalLobbyPlayerCols
    {
        public global::SpacetimeDB.Col<LoggedOutPlayer, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<LoggedOutPlayer, string> Username { get; }
        public global::SpacetimeDB.Col<LoggedOutPlayer, bool> IsAdmin { get; }

        public LocalLobbyPlayerCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<LoggedOutPlayer, SpacetimeDB.Identity>(tableName, "player_id");
            Username = new global::SpacetimeDB.Col<LoggedOutPlayer, string>(tableName, "username");
            IsAdmin = new global::SpacetimeDB.Col<LoggedOutPlayer, bool>(tableName, "is_admin");
        }
    }

    public sealed class LocalLobbyPlayerIxCols
    {
        public global::SpacetimeDB.IxCol<LoggedOutPlayer, SpacetimeDB.Identity> PlayerId { get; }

        public LocalLobbyPlayerIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<LoggedOutPlayer, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
