// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalPlayerInventoryHandle : RemoteTableHandle<EventContext, PlayerInventory>
        {
            public override string RemoteTableName => "local_player_inventory";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInventory row) => row.ProfileId;

                public ProfileIdUniqueIndex(LocalPlayerInventoryHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal LocalPlayerInventoryHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerInventory row) => row.ProfileId;
        }

        public readonly LocalPlayerInventoryHandle LocalPlayerInventory;
    }

    public sealed class LocalPlayerInventoryCols
    {
        public global::SpacetimeDB.Col<PlayerInventory, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerInventory, System.Collections.Generic.List<InventorySlot>> Slots { get; }

        public LocalPlayerInventoryCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerInventory, ulong>(tableName, "profile_id");
            Slots = new global::SpacetimeDB.Col<PlayerInventory, System.Collections.Generic.List<InventorySlot>>(tableName, "slots");
        }
    }

    public sealed class LocalPlayerInventoryIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerInventory, ulong> ProfileId { get; }

        public LocalPlayerInventoryIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerInventory, ulong>(tableName, "profile_id");
        }
    }
}
