// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalPlayerProfilesHandle : RemoteTableHandle<EventContext, PlayerProfile>
        {
            public override string RemoteTableName => "local_player_profiles";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerProfile row) => row.ProfileId;

                public ProfileIdUniqueIndex(LocalPlayerProfilesHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal LocalPlayerProfilesHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerProfile row) => row.ProfileId;
        }

        public readonly LocalPlayerProfilesHandle LocalPlayerProfiles;
    }

    public sealed class LocalPlayerProfilesCols
    {
        public global::SpacetimeDB.Col<PlayerProfile, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, string> ProfileName { get; }
        public global::SpacetimeDB.Col<PlayerProfile, string> TextureId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, bool> AimAssist { get; }
        public global::SpacetimeDB.Col<PlayerProfile, bool> LockOn { get; }

        public LocalPlayerProfilesCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerProfile, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerProfile, SpacetimeDB.Identity>(tableName, "player_id");
            ProfileName = new global::SpacetimeDB.Col<PlayerProfile, string>(tableName, "profile_name");
            TextureId = new global::SpacetimeDB.Col<PlayerProfile, string>(tableName, "texture_id");
            AimAssist = new global::SpacetimeDB.Col<PlayerProfile, bool>(tableName, "aim_assist");
            LockOn = new global::SpacetimeDB.Col<PlayerProfile, bool>(tableName, "lock_on");
        }
    }

    public sealed class LocalPlayerProfilesIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerProfile, ulong> ProfileId { get; }

        public LocalPlayerProfilesIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerProfile, ulong>(tableName, "profile_id");
        }
    }
}
