// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalPlayerStatsHandle : RemoteTableHandle<EventContext, PlayerStats>
        {
            public override string RemoteTableName => "local_player_stats";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerStats row) => row.ProfileId;

                public ProfileIdUniqueIndex(LocalPlayerStatsHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal LocalPlayerStatsHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerStats row) => row.ProfileId;
        }

        public readonly LocalPlayerStatsHandle LocalPlayerStats;
    }

    public sealed class LocalPlayerStatsCols
    {
        public global::SpacetimeDB.Col<PlayerStats, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Strength { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Wisdom { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Dexterity { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> DamageDealer { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Supporter { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Artisan { get; }

        public LocalPlayerStatsCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerStats, ulong>(tableName, "profile_id");
            Strength = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "strength");
            Wisdom = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "wisdom");
            Dexterity = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "dexterity");
            DamageDealer = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "damage_dealer");
            Supporter = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "supporter");
            Artisan = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "artisan");
        }
    }

    public sealed class LocalPlayerStatsIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStats, ulong> ProfileId { get; }

        public LocalPlayerStatsIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerStats, ulong>(tableName, "profile_id");
        }
    }
}
