// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocalPlayerHandle : RemoteTableHandle<EventContext, LoggedInPlayer>
        {
            public override string RemoteTableName => "local_player";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(LoggedInPlayer row) => row.PlayerId;

                public PlayerIdUniqueIndex(LocalPlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal LocalPlayerHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(LoggedInPlayer row) => row.PlayerId;
        }

        public readonly LocalPlayerHandle LocalPlayer;
    }

    public sealed class LocalPlayerCols
    {
        public global::SpacetimeDB.Col<LoggedInPlayer, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, string> Username { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, bool> IsAdmin { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, ulong> ProfileId { get; }

        public LocalPlayerCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<LoggedInPlayer, SpacetimeDB.Identity>(tableName, "player_id");
            Username = new global::SpacetimeDB.Col<LoggedInPlayer, string>(tableName, "username");
            IsAdmin = new global::SpacetimeDB.Col<LoggedInPlayer, bool>(tableName, "is_admin");
            ProfileId = new global::SpacetimeDB.Col<LoggedInPlayer, ulong>(tableName, "profile_id");
        }
    }

    public sealed class LocalPlayerIxCols
    {
        public global::SpacetimeDB.IxCol<LoggedInPlayer, SpacetimeDB.Identity> PlayerId { get; }

        public LocalPlayerIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<LoggedInPlayer, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
