// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LoggedInPlayerHandle : RemoteTableHandle<EventContext, LoggedInPlayer>
        {
            public override string RemoteTableName => "logged_in_player";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(LoggedInPlayer row) => row.PlayerId;

                public PlayerIdUniqueIndex(LoggedInPlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LoggedInPlayer row) => row.ProfileId;

                public ProfileIdUniqueIndex(LoggedInPlayerHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal LoggedInPlayerHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(LoggedInPlayer row) => row.PlayerId;
        }

        public readonly LoggedInPlayerHandle LoggedInPlayer;
    }

    public sealed class LoggedInPlayerCols
    {
        public global::SpacetimeDB.Col<LoggedInPlayer, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, string> Username { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, bool> IsAdmin { get; }
        public global::SpacetimeDB.Col<LoggedInPlayer, ulong> ProfileId { get; }

        public LoggedInPlayerCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<LoggedInPlayer, SpacetimeDB.Identity>(tableName, "player_id");
            Username = new global::SpacetimeDB.Col<LoggedInPlayer, string>(tableName, "username");
            IsAdmin = new global::SpacetimeDB.Col<LoggedInPlayer, bool>(tableName, "is_admin");
            ProfileId = new global::SpacetimeDB.Col<LoggedInPlayer, ulong>(tableName, "profile_id");
        }
    }

    public sealed class LoggedInPlayerIxCols
    {
        public global::SpacetimeDB.IxCol<LoggedInPlayer, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.IxCol<LoggedInPlayer, ulong> ProfileId { get; }

        public LoggedInPlayerIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<LoggedInPlayer, SpacetimeDB.Identity>(tableName, "player_id");
            ProfileId = new global::SpacetimeDB.IxCol<LoggedInPlayer, ulong>(tableName, "profile_id");
        }
    }
}
