// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootDropHandle : RemoteTableHandle<EventContext, LootDrop>
        {
            public override string RemoteTableName => "loot_drop";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(LootDrop row) => row.ChunkIndex;

                public ChunkIndexIndex(LootDropHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class DropIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LootDrop row) => row.DropId;

                public DropIdUniqueIndex(LootDropHandle table) : base(table) { }
            }

            public readonly DropIdUniqueIndex DropId;

            internal LootDropHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                DropId = new(this);
            }

            protected override object GetPrimaryKey(LootDrop row) => row.DropId;
        }

        public readonly LootDropHandle LootDrop;
    }

    public sealed class LootDropCols
    {
        public global::SpacetimeDB.Col<LootDrop, ulong> DropId { get; }
        public global::SpacetimeDB.Col<LootDrop, string> ItemId { get; }
        public global::SpacetimeDB.Col<LootDrop, float> X { get; }
        public global::SpacetimeDB.Col<LootDrop, float> Y { get; }
        public global::SpacetimeDB.Col<LootDrop, long> ChunkIndex { get; }
        public global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Timestamp> ExpiresAt { get; }
        public global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Identity> DroppedBy { get; }
        public global::SpacetimeDB.Col<LootDrop, System.Collections.Generic.List<string>> EnchantmentIds { get; }

        public LootDropCols(string tableName)
        {
            DropId = new global::SpacetimeDB.Col<LootDrop, ulong>(tableName, "drop_id");
            ItemId = new global::SpacetimeDB.Col<LootDrop, string>(tableName, "item_id");
            X = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "y");
            ChunkIndex = new global::SpacetimeDB.Col<LootDrop, long>(tableName, "chunk_index");
            ExpiresAt = new global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Timestamp>(tableName, "expires_at");
            DroppedBy = new global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Identity>(tableName, "dropped_by");
            EnchantmentIds = new global::SpacetimeDB.Col<LootDrop, System.Collections.Generic.List<string>>(tableName, "enchantment_ids");
        }
    }

    public sealed class LootDropIxCols
    {
        public global::SpacetimeDB.IxCol<LootDrop, ulong> DropId { get; }
        public global::SpacetimeDB.IxCol<LootDrop, long> ChunkIndex { get; }

        public LootDropIxCols(string tableName)
        {
            DropId = new global::SpacetimeDB.IxCol<LootDrop, ulong>(tableName, "drop_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<LootDrop, long>(tableName, "chunk_index");
        }
    }
}
