// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapConfigHandle : RemoteTableHandle<EventContext, MapConfig>
        {
            public override string RemoteTableName => "map_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MapConfig row) => row.Id;

                public IdUniqueIndex(MapConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MapConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(MapConfig row) => row.Id;
        }

        public readonly MapConfigHandle MapConfig;
    }

    public sealed class MapConfigCols
    {
        public global::SpacetimeDB.Col<MapConfig, uint> Id { get; }
        public global::SpacetimeDB.Col<MapConfig, int> ChunkHexRadius { get; }
        public global::SpacetimeDB.Col<MapConfig, int> ChunkCols { get; }
        public global::SpacetimeDB.Col<MapConfig, int> ChunkRows { get; }
        public global::SpacetimeDB.Col<MapConfig, float> HexOuterRadius { get; }
        public global::SpacetimeDB.Col<MapConfig, float> LapQX { get; }
        public global::SpacetimeDB.Col<MapConfig, float> LapQY { get; }
        public global::SpacetimeDB.Col<MapConfig, float> LapRX { get; }
        public global::SpacetimeDB.Col<MapConfig, float> LapRY { get; }

        public MapConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MapConfig, uint>(tableName, "id");
            ChunkHexRadius = new global::SpacetimeDB.Col<MapConfig, int>(tableName, "chunk_hex_radius");
            ChunkCols = new global::SpacetimeDB.Col<MapConfig, int>(tableName, "chunk_cols");
            ChunkRows = new global::SpacetimeDB.Col<MapConfig, int>(tableName, "chunk_rows");
            HexOuterRadius = new global::SpacetimeDB.Col<MapConfig, float>(tableName, "hex_outer_radius");
            LapQX = new global::SpacetimeDB.Col<MapConfig, float>(tableName, "lap_q_x");
            LapQY = new global::SpacetimeDB.Col<MapConfig, float>(tableName, "lap_q_y");
            LapRX = new global::SpacetimeDB.Col<MapConfig, float>(tableName, "lap_r_x");
            LapRY = new global::SpacetimeDB.Col<MapConfig, float>(tableName, "lap_r_y");
        }
    }

    public sealed class MapConfigIxCols
    {
        public global::SpacetimeDB.IxCol<MapConfig, uint> Id { get; }

        public MapConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MapConfig, uint>(tableName, "id");
        }
    }
}
