// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MovementDefHandle : RemoteTableHandle<EventContext, MovementDef>
        {
            public override string RemoteTableName => "movement_def";

            public sealed class DefIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MovementDef row) => row.DefId;

                public DefIdUniqueIndex(MovementDefHandle table) : base(table) { }
            }

            public readonly DefIdUniqueIndex DefId;

            internal MovementDefHandle(DbConnection conn) : base(conn)
            {
                DefId = new(this);
            }

            protected override object GetPrimaryKey(MovementDef row) => row.DefId;
        }

        public readonly MovementDefHandle MovementDef;
    }

    public sealed class MovementDefCols
    {
        public global::SpacetimeDB.Col<MovementDef, ulong> DefId { get; }
        public global::SpacetimeDB.Col<MovementDef, MovementBehavior> Movement { get; }

        public MovementDefCols(string tableName)
        {
            DefId = new global::SpacetimeDB.Col<MovementDef, ulong>(tableName, "def_id");
            Movement = new global::SpacetimeDB.Col<MovementDef, MovementBehavior>(tableName, "movement");
        }
    }

    public sealed class MovementDefIxCols
    {
        public global::SpacetimeDB.IxCol<MovementDef, ulong> DefId { get; }

        public MovementDefIxCols(string tableName)
        {
            DefId = new global::SpacetimeDB.IxCol<MovementDef, ulong>(tableName, "def_id");
        }
    }
}
