// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MultiStepDefHandle : RemoteTableHandle<EventContext, MultiStepDef>
        {
            public override string RemoteTableName => "multi_step_def";

            public sealed class DefIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MultiStepDef row) => row.DefId;

                public DefIdUniqueIndex(MultiStepDefHandle table) : base(table) { }
            }

            public readonly DefIdUniqueIndex DefId;

            internal MultiStepDefHandle(DbConnection conn) : base(conn)
            {
                DefId = new(this);
            }

            protected override object GetPrimaryKey(MultiStepDef row) => row.DefId;
        }

        public readonly MultiStepDefHandle MultiStepDef;
    }

    public sealed class MultiStepDefCols
    {
        public global::SpacetimeDB.Col<MultiStepDef, ulong> DefId { get; }
        public global::SpacetimeDB.Col<MultiStepDef, System.Collections.Generic.List<MultiShot>> Shots { get; }
        public global::SpacetimeDB.Col<MultiStepDef, float> NextStepDelay { get; }

        public MultiStepDefCols(string tableName)
        {
            DefId = new global::SpacetimeDB.Col<MultiStepDef, ulong>(tableName, "def_id");
            Shots = new global::SpacetimeDB.Col<MultiStepDef, System.Collections.Generic.List<MultiShot>>(tableName, "shots");
            NextStepDelay = new global::SpacetimeDB.Col<MultiStepDef, float>(tableName, "next_step_delay");
        }
    }

    public sealed class MultiStepDefIxCols
    {
        public global::SpacetimeDB.IxCol<MultiStepDef, ulong> DefId { get; }

        public MultiStepDefIxCols(string tableName)
        {
            DefId = new global::SpacetimeDB.IxCol<MultiStepDef, ulong>(tableName, "def_id");
        }
    }
}
