// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NearbyRemotePlayersHandle : RemoteTableHandle<EventContext, PlayerPosition>
        {
            public override string RemoteTableName => "nearby_remote_players";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerPosition row) => row.ProfileId;

                public ProfileIdUniqueIndex(NearbyRemotePlayersHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal NearbyRemotePlayersHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerPosition row) => row.ProfileId;
        }

        public readonly NearbyRemotePlayersHandle NearbyRemotePlayers;
    }

    public sealed class NearbyRemotePlayersCols
    {
        public global::SpacetimeDB.Col<PlayerPosition, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> X { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> Y { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> MovementDirection { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> MovementSpeed { get; }
        public global::SpacetimeDB.Col<PlayerPosition, long> ChunkIndex { get; }

        public NearbyRemotePlayersCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerPosition, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity>(tableName, "player_id");
            X = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "y");
            MovementDirection = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "movement_direction");
            MovementSpeed = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "movement_speed");
            ChunkIndex = new global::SpacetimeDB.Col<PlayerPosition, long>(tableName, "chunk_index");
        }
    }

    public sealed class NearbyRemotePlayersIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerPosition, ulong> ProfileId { get; }

        public NearbyRemotePlayersIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerPosition, ulong>(tableName, "profile_id");
        }
    }
}
