// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NearbyEnemiesHandle : RemoteTableHandle<EventContext, Enemy>
        {
            public override string RemoteTableName => "nearby_enemies";

            public sealed class EnemyIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Enemy row) => row.EnemyId;

                public EnemyIdUniqueIndex(NearbyEnemiesHandle table) : base(table) { }
            }

            public readonly EnemyIdUniqueIndex EnemyId;

            internal NearbyEnemiesHandle(DbConnection conn) : base(conn)
            {
                EnemyId = new(this);
            }

            protected override object GetPrimaryKey(Enemy row) => row.EnemyId;
        }

        public readonly NearbyEnemiesHandle NearbyEnemies;
    }

    public sealed class NearbyEnemiesCols
    {
        public global::SpacetimeDB.Col<Enemy, ulong> EnemyId { get; }
        public global::SpacetimeDB.Col<Enemy, string> TemplateId { get; }
        public global::SpacetimeDB.Col<Enemy, ulong> BehaviorId { get; }
        public global::SpacetimeDB.Col<Enemy, float> X { get; }
        public global::SpacetimeDB.Col<Enemy, float> Y { get; }
        public global::SpacetimeDB.Col<Enemy, SpacetimeDB.Timestamp> SpawnTime { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Hp { get; }
        public global::SpacetimeDB.Col<Enemy, byte> Phase { get; }
        public global::SpacetimeDB.Col<Enemy, bool> IsElite { get; }
        public global::SpacetimeDB.Col<Enemy, bool> Immortal { get; }
        public global::SpacetimeDB.Col<Enemy, long> ChunkIndex { get; }

        public NearbyEnemiesCols(string tableName)
        {
            EnemyId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "enemy_id");
            TemplateId = new global::SpacetimeDB.Col<Enemy, string>(tableName, "template_id");
            BehaviorId = new global::SpacetimeDB.Col<Enemy, ulong>(tableName, "behavior_id");
            X = new global::SpacetimeDB.Col<Enemy, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<Enemy, float>(tableName, "y");
            SpawnTime = new global::SpacetimeDB.Col<Enemy, SpacetimeDB.Timestamp>(tableName, "spawn_time");
            Hp = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "hp");
            Phase = new global::SpacetimeDB.Col<Enemy, byte>(tableName, "phase");
            IsElite = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "is_elite");
            Immortal = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "immortal");
            ChunkIndex = new global::SpacetimeDB.Col<Enemy, long>(tableName, "chunk_index");
        }
    }

    public sealed class NearbyEnemiesIxCols
    {
        public global::SpacetimeDB.IxCol<Enemy, ulong> EnemyId { get; }

        public NearbyEnemiesIxCols(string tableName)
        {
            EnemyId = new global::SpacetimeDB.IxCol<Enemy, ulong>(tableName, "enemy_id");
        }
    }
}
