// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NearbyRemotePlayerRotationsHandle : RemoteTableHandle<EventContext, PlayerRotation>
        {
            public override string RemoteTableName => "nearby_remote_player_rotations";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerRotation row) => row.ProfileId;

                public ProfileIdUniqueIndex(NearbyRemotePlayerRotationsHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal NearbyRemotePlayerRotationsHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerRotation row) => row.ProfileId;
        }

        public readonly NearbyRemotePlayerRotationsHandle NearbyRemotePlayerRotations;
    }

    public sealed class NearbyRemotePlayerRotationsCols
    {
        public global::SpacetimeDB.Col<PlayerRotation, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerRotation, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerRotation, float> ScreenRotation { get; }
        public global::SpacetimeDB.Col<PlayerRotation, long> ChunkIndex { get; }

        public NearbyRemotePlayerRotationsCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerRotation, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerRotation, SpacetimeDB.Identity>(tableName, "player_id");
            ScreenRotation = new global::SpacetimeDB.Col<PlayerRotation, float>(tableName, "screen_rotation");
            ChunkIndex = new global::SpacetimeDB.Col<PlayerRotation, long>(tableName, "chunk_index");
        }
    }

    public sealed class NearbyRemotePlayerRotationsIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerRotation, ulong> ProfileId { get; }

        public NearbyRemotePlayerRotationsIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerRotation, ulong>(tableName, "profile_id");
        }
    }
}
