// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NearbyHexDecorHandle : RemoteTableHandle<EventContext, HexDecor>
        {
            public override string RemoteTableName => "nearby_hex_decor";

            public sealed class DecorIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HexDecor row) => row.DecorId;

                public DecorIdUniqueIndex(NearbyHexDecorHandle table) : base(table) { }
            }

            public readonly DecorIdUniqueIndex DecorId;

            internal NearbyHexDecorHandle(DbConnection conn) : base(conn)
            {
                DecorId = new(this);
            }

            protected override object GetPrimaryKey(HexDecor row) => row.DecorId;
        }

        public readonly NearbyHexDecorHandle NearbyHexDecor;
    }

    public sealed class NearbyHexDecorCols
    {
        public global::SpacetimeDB.Col<HexDecor, ulong> DecorId { get; }
        public global::SpacetimeDB.Col<HexDecor, int> HexQ { get; }
        public global::SpacetimeDB.Col<HexDecor, int> HexR { get; }
        public global::SpacetimeDB.Col<HexDecor, long> ChunkIndex { get; }
        public global::SpacetimeDB.Col<HexDecor, string> TextureId { get; }
        public global::SpacetimeDB.Col<HexDecor, string> ShadowTextureId { get; }
        public global::SpacetimeDB.Col<HexDecor, float> RotationDegrees { get; }
        public global::SpacetimeDB.Col<HexDecor, string> BiomeId { get; }
        public global::SpacetimeDB.Col<HexDecor, ulong> RegionId { get; }

        public NearbyHexDecorCols(string tableName)
        {
            DecorId = new global::SpacetimeDB.Col<HexDecor, ulong>(tableName, "decor_id");
            HexQ = new global::SpacetimeDB.Col<HexDecor, int>(tableName, "hex_q");
            HexR = new global::SpacetimeDB.Col<HexDecor, int>(tableName, "hex_r");
            ChunkIndex = new global::SpacetimeDB.Col<HexDecor, long>(tableName, "chunk_index");
            TextureId = new global::SpacetimeDB.Col<HexDecor, string>(tableName, "texture_id");
            ShadowTextureId = new global::SpacetimeDB.Col<HexDecor, string>(tableName, "shadow_texture_id");
            RotationDegrees = new global::SpacetimeDB.Col<HexDecor, float>(tableName, "rotation_degrees");
            BiomeId = new global::SpacetimeDB.Col<HexDecor, string>(tableName, "biome_id");
            RegionId = new global::SpacetimeDB.Col<HexDecor, ulong>(tableName, "region_id");
        }
    }

    public sealed class NearbyHexDecorIxCols
    {
        public global::SpacetimeDB.IxCol<HexDecor, ulong> DecorId { get; }

        public NearbyHexDecorIxCols(string tableName)
        {
            DecorId = new global::SpacetimeDB.IxCol<HexDecor, ulong>(tableName, "decor_id");
        }
    }
}
