// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NearbyLootDropsHandle : RemoteTableHandle<EventContext, LootDrop>
        {
            public override string RemoteTableName => "nearby_loot_drops";

            public sealed class DropIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LootDrop row) => row.DropId;

                public DropIdUniqueIndex(NearbyLootDropsHandle table) : base(table) { }
            }

            public readonly DropIdUniqueIndex DropId;

            internal NearbyLootDropsHandle(DbConnection conn) : base(conn)
            {
                DropId = new(this);
            }

            protected override object GetPrimaryKey(LootDrop row) => row.DropId;
        }

        public readonly NearbyLootDropsHandle NearbyLootDrops;
    }

    public sealed class NearbyLootDropsCols
    {
        public global::SpacetimeDB.Col<LootDrop, ulong> DropId { get; }
        public global::SpacetimeDB.Col<LootDrop, string> ItemId { get; }
        public global::SpacetimeDB.Col<LootDrop, float> X { get; }
        public global::SpacetimeDB.Col<LootDrop, float> Y { get; }
        public global::SpacetimeDB.Col<LootDrop, long> ChunkIndex { get; }
        public global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Timestamp> ExpiresAt { get; }
        public global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Identity> DroppedBy { get; }
        public global::SpacetimeDB.Col<LootDrop, System.Collections.Generic.List<string>> EnchantmentIds { get; }

        public NearbyLootDropsCols(string tableName)
        {
            DropId = new global::SpacetimeDB.Col<LootDrop, ulong>(tableName, "drop_id");
            ItemId = new global::SpacetimeDB.Col<LootDrop, string>(tableName, "item_id");
            X = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "y");
            ChunkIndex = new global::SpacetimeDB.Col<LootDrop, long>(tableName, "chunk_index");
            ExpiresAt = new global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Timestamp>(tableName, "expires_at");
            DroppedBy = new global::SpacetimeDB.Col<LootDrop, SpacetimeDB.Identity>(tableName, "dropped_by");
            EnchantmentIds = new global::SpacetimeDB.Col<LootDrop, System.Collections.Generic.List<string>>(tableName, "enchantment_ids");
        }
    }

    public sealed class NearbyLootDropsIxCols
    {
        public global::SpacetimeDB.IxCol<LootDrop, ulong> DropId { get; }

        public NearbyLootDropsIxCols(string tableName)
        {
            DropId = new global::SpacetimeDB.IxCol<LootDrop, ulong>(tableName, "drop_id");
        }
    }
}
