// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OverlayAdjacencyRuleHandle : RemoteTableHandle<EventContext, OverlayAdjacencyRule>
        {
            public override string RemoteTableName => "overlay_adjacency_rule";

            public sealed class RuleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OverlayAdjacencyRule row) => row.RuleId;

                public RuleIdUniqueIndex(OverlayAdjacencyRuleHandle table) : base(table) { }
            }

            public readonly RuleIdUniqueIndex RuleId;

            internal OverlayAdjacencyRuleHandle(DbConnection conn) : base(conn)
            {
                RuleId = new(this);
            }

            protected override object GetPrimaryKey(OverlayAdjacencyRule row) => row.RuleId;
        }

        public readonly OverlayAdjacencyRuleHandle OverlayAdjacencyRule;
    }

    public sealed class OverlayAdjacencyRuleCols
    {
        public global::SpacetimeDB.Col<OverlayAdjacencyRule, ulong> RuleId { get; }
        public global::SpacetimeDB.Col<OverlayAdjacencyRule, string> TagA { get; }
        public global::SpacetimeDB.Col<OverlayAdjacencyRule, string> TagB { get; }

        public OverlayAdjacencyRuleCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.Col<OverlayAdjacencyRule, ulong>(tableName, "rule_id");
            TagA = new global::SpacetimeDB.Col<OverlayAdjacencyRule, string>(tableName, "tag_a");
            TagB = new global::SpacetimeDB.Col<OverlayAdjacencyRule, string>(tableName, "tag_b");
        }
    }

    public sealed class OverlayAdjacencyRuleIxCols
    {
        public global::SpacetimeDB.IxCol<OverlayAdjacencyRule, ulong> RuleId { get; }

        public OverlayAdjacencyRuleIxCols(string tableName)
        {
            RuleId = new global::SpacetimeDB.IxCol<OverlayAdjacencyRule, ulong>(tableName, "rule_id");
        }
    }
}
