// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerStatsHandle : RemoteTableHandle<EventContext, PlayerStats>
        {
            public override string RemoteTableName => "player_stats";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerStats row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerStatsHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerStatsHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerStats row) => row.ProfileId;
        }

        public readonly PlayerStatsHandle PlayerStats;
    }

    public sealed class PlayerStatsCols
    {
        public global::SpacetimeDB.Col<PlayerStats, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Strength { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Wisdom { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Dexterity { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Defense { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Vitality { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Speed { get; }

        public PlayerStatsCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerStats, ulong>(tableName, "profile_id");
            Strength = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "strength");
            Wisdom = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "wisdom");
            Dexterity = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "dexterity");
            Defense = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "defense");
            Vitality = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "vitality");
            Speed = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "speed");
        }
    }

    public sealed class PlayerStatsIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStats, ulong> ProfileId { get; }

        public PlayerStatsIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerStats, ulong>(tableName, "profile_id");
        }
    }
}
