// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerPositionHandle : RemoteTableHandle<EventContext, PlayerPosition>
        {
            public override string RemoteTableName => "player_position";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(PlayerPosition row) => row.ChunkIndex;

                public ChunkIndexIndex(PlayerPositionHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerPosition row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerPositionHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerPositionHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerPosition row) => row.ProfileId;
        }

        public readonly PlayerPositionHandle PlayerPosition;
    }

    public sealed class PlayerPositionCols
    {
        public global::SpacetimeDB.Col<PlayerPosition, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> X { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> Y { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> MovementDirection { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> MovementSpeed { get; }
        public global::SpacetimeDB.Col<PlayerPosition, long> ChunkIndex { get; }

        public PlayerPositionCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerPosition, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity>(tableName, "player_id");
            X = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "y");
            MovementDirection = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "movement_direction");
            MovementSpeed = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "movement_speed");
            ChunkIndex = new global::SpacetimeDB.Col<PlayerPosition, long>(tableName, "chunk_index");
        }
    }

    public sealed class PlayerPositionIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerPosition, ulong> ProfileId { get; }
        public global::SpacetimeDB.IxCol<PlayerPosition, long> ChunkIndex { get; }

        public PlayerPositionIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerPosition, ulong>(tableName, "profile_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<PlayerPosition, long>(tableName, "chunk_index");
        }
    }
}
