// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerRotationHandle : RemoteTableHandle<EventContext, PlayerRotation>
        {
            public override string RemoteTableName => "player_rotation";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(PlayerRotation row) => row.ChunkIndex;

                public ChunkIndexIndex(PlayerRotationHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerRotation row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerRotationHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerRotationHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerRotation row) => row.ProfileId;
        }

        public readonly PlayerRotationHandle PlayerRotation;
    }

    public sealed class PlayerRotationCols
    {
        public global::SpacetimeDB.Col<PlayerRotation, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerRotation, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerRotation, float> ScreenRotation { get; }
        public global::SpacetimeDB.Col<PlayerRotation, long> ChunkIndex { get; }

        public PlayerRotationCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerRotation, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerRotation, SpacetimeDB.Identity>(tableName, "player_id");
            ScreenRotation = new global::SpacetimeDB.Col<PlayerRotation, float>(tableName, "screen_rotation");
            ChunkIndex = new global::SpacetimeDB.Col<PlayerRotation, long>(tableName, "chunk_index");
        }
    }

    public sealed class PlayerRotationIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerRotation, ulong> ProfileId { get; }
        public global::SpacetimeDB.IxCol<PlayerRotation, long> ChunkIndex { get; }

        public PlayerRotationIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerRotation, ulong>(tableName, "profile_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<PlayerRotation, long>(tableName, "chunk_index");
        }
    }
}
