// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerChunkHandle : RemoteTableHandle<EventContext, PlayerChunk>
        {
            public override string RemoteTableName => "player_chunk";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerChunk row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerChunkHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerChunkHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerChunk row) => row.ProfileId;
        }

        public readonly PlayerChunkHandle PlayerChunk;
    }

    public sealed class PlayerChunkCols
    {
        public global::SpacetimeDB.Col<PlayerChunk, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerChunk, int> ChunkQ { get; }
        public global::SpacetimeDB.Col<PlayerChunk, int> ChunkR { get; }

        public PlayerChunkCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerChunk, ulong>(tableName, "profile_id");
            ChunkQ = new global::SpacetimeDB.Col<PlayerChunk, int>(tableName, "chunk_q");
            ChunkR = new global::SpacetimeDB.Col<PlayerChunk, int>(tableName, "chunk_r");
        }
    }

    public sealed class PlayerChunkIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerChunk, ulong> ProfileId { get; }

        public PlayerChunkIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerChunk, ulong>(tableName, "profile_id");
        }
    }
}
