// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerProfileHandle : RemoteTableHandle<EventContext, PlayerProfile>
        {
            public override string RemoteTableName => "player_profile";

            public sealed class PlayerIdIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerProfile row) => row.PlayerId;

                public PlayerIdIndex(PlayerProfileHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            public sealed class ByPlayerProfileNameIndex : BTreeIndexBase<(SpacetimeDB.Identity PlayerId, string ProfileName)>
            {
                protected override (SpacetimeDB.Identity PlayerId, string ProfileName) GetKey(PlayerProfile row) => (row.PlayerId, row.ProfileName);

                public ByPlayerProfileNameIndex(PlayerProfileHandle table) : base(table) { }
            }

            public readonly ByPlayerProfileNameIndex ByPlayerProfileName;

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerProfile row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerProfileHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerProfileHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
                ByPlayerProfileName = new(this);
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerProfile row) => row.ProfileId;
        }

        public readonly PlayerProfileHandle PlayerProfile;
    }

    public sealed class PlayerProfileCols
    {
        public global::SpacetimeDB.Col<PlayerProfile, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, string> ProfileName { get; }
        public global::SpacetimeDB.Col<PlayerProfile, string> TextureId { get; }
        public global::SpacetimeDB.Col<PlayerProfile, bool> AimAssist { get; }
        public global::SpacetimeDB.Col<PlayerProfile, bool> LockOn { get; }

        public PlayerProfileCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerProfile, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.Col<PlayerProfile, SpacetimeDB.Identity>(tableName, "player_id");
            ProfileName = new global::SpacetimeDB.Col<PlayerProfile, string>(tableName, "profile_name");
            TextureId = new global::SpacetimeDB.Col<PlayerProfile, string>(tableName, "texture_id");
            AimAssist = new global::SpacetimeDB.Col<PlayerProfile, bool>(tableName, "aim_assist");
            LockOn = new global::SpacetimeDB.Col<PlayerProfile, bool>(tableName, "lock_on");
        }
    }

    public sealed class PlayerProfileIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerProfile, ulong> ProfileId { get; }
        public global::SpacetimeDB.IxCol<PlayerProfile, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.IxCol<PlayerProfile, string> ProfileName { get; }

        public PlayerProfileIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerProfile, ulong>(tableName, "profile_id");
            PlayerId = new global::SpacetimeDB.IxCol<PlayerProfile, SpacetimeDB.Identity>(tableName, "player_id");
            ProfileName = new global::SpacetimeDB.IxCol<PlayerProfile, string>(tableName, "profile_name");
        }
    }
}
