// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerDataHandle : RemoteTableHandle<EventContext, PlayerData>
        {
            public override string RemoteTableName => "player_data";

            public sealed class ProfileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerData row) => row.ProfileId;

                public ProfileIdUniqueIndex(PlayerDataHandle table) : base(table) { }
            }

            public readonly ProfileIdUniqueIndex ProfileId;

            internal PlayerDataHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
            }

            protected override object GetPrimaryKey(PlayerData row) => row.ProfileId;
        }

        public readonly PlayerDataHandle PlayerData;
    }

    public sealed class PlayerDataCols
    {
        public global::SpacetimeDB.Col<PlayerData, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerData, uint> Level { get; }
        public global::SpacetimeDB.Col<PlayerData, uint> Xp { get; }
        public global::SpacetimeDB.Col<PlayerData, uint> Hp { get; }
        public global::SpacetimeDB.Col<PlayerData, uint> MaxHp { get; }
        public global::SpacetimeDB.Col<PlayerData, int> Defense { get; }
        public global::SpacetimeDB.Col<PlayerData, float> BaseSpeed { get; }

        public PlayerDataCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.Col<PlayerData, ulong>(tableName, "profile_id");
            Level = new global::SpacetimeDB.Col<PlayerData, uint>(tableName, "level");
            Xp = new global::SpacetimeDB.Col<PlayerData, uint>(tableName, "xp");
            Hp = new global::SpacetimeDB.Col<PlayerData, uint>(tableName, "hp");
            MaxHp = new global::SpacetimeDB.Col<PlayerData, uint>(tableName, "max_hp");
            Defense = new global::SpacetimeDB.Col<PlayerData, int>(tableName, "defense");
            BaseSpeed = new global::SpacetimeDB.Col<PlayerData, float>(tableName, "base_speed");
        }
    }

    public sealed class PlayerDataIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerData, ulong> ProfileId { get; }

        public PlayerDataIxCols(string tableName)
        {
            ProfileId = new global::SpacetimeDB.IxCol<PlayerData, ulong>(tableName, "profile_id");
        }
    }
}
