// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerInventorySlotHandle : RemoteTableHandle<EventContext, PlayerInventorySlot>
        {
            public override string RemoteTableName => "player_inventory_slot";

            public sealed class ProfileIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInventorySlot row) => row.ProfileId;

                public ProfileIdIndex(PlayerInventorySlotHandle table) : base(table) { }
            }

            public readonly ProfileIdIndex ProfileId;

            public sealed class ByProfileSlotIndex : BTreeIndexBase<(ulong ProfileId, uint SlotIndex)>
            {
                protected override (ulong ProfileId, uint SlotIndex) GetKey(PlayerInventorySlot row) => (row.ProfileId, row.SlotIndex);

                public ByProfileSlotIndex(PlayerInventorySlotHandle table) : base(table) { }
            }

            public readonly ByProfileSlotIndex ByProfileSlot;

            public sealed class SlotIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInventorySlot row) => row.SlotId;

                public SlotIdUniqueIndex(PlayerInventorySlotHandle table) : base(table) { }
            }

            public readonly SlotIdUniqueIndex SlotId;

            internal PlayerInventorySlotHandle(DbConnection conn) : base(conn)
            {
                ProfileId = new(this);
                ByProfileSlot = new(this);
                SlotId = new(this);
            }

            protected override object GetPrimaryKey(PlayerInventorySlot row) => row.SlotId;
        }

        public readonly PlayerInventorySlotHandle PlayerInventorySlot;
    }

    public sealed class PlayerInventorySlotCols
    {
        public global::SpacetimeDB.Col<PlayerInventorySlot, ulong> SlotId { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, ulong> ProfileId { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, uint> SlotIndex { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, SlotRole> Role { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, string> ItemId { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, System.Collections.Generic.List<string>> EnchantmentIds { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, SpacetimeDB.Timestamp> CooldownUntil { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, uint> Charges { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, uint> ActiveToggle { get; }
        public global::SpacetimeDB.Col<PlayerInventorySlot, uint> OccupiedBy { get; }

        public PlayerInventorySlotCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.Col<PlayerInventorySlot, ulong>(tableName, "slot_id");
            ProfileId = new global::SpacetimeDB.Col<PlayerInventorySlot, ulong>(tableName, "profile_id");
            SlotIndex = new global::SpacetimeDB.Col<PlayerInventorySlot, uint>(tableName, "slot_index");
            Role = new global::SpacetimeDB.Col<PlayerInventorySlot, SlotRole>(tableName, "role");
            ItemId = new global::SpacetimeDB.Col<PlayerInventorySlot, string>(tableName, "item_id");
            EnchantmentIds = new global::SpacetimeDB.Col<PlayerInventorySlot, System.Collections.Generic.List<string>>(tableName, "enchantment_ids");
            CooldownUntil = new global::SpacetimeDB.Col<PlayerInventorySlot, SpacetimeDB.Timestamp>(tableName, "cooldown_until");
            Charges = new global::SpacetimeDB.Col<PlayerInventorySlot, uint>(tableName, "charges");
            ActiveToggle = new global::SpacetimeDB.Col<PlayerInventorySlot, uint>(tableName, "active_toggle");
            OccupiedBy = new global::SpacetimeDB.Col<PlayerInventorySlot, uint>(tableName, "occupied_by");
        }
    }

    public sealed class PlayerInventorySlotIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerInventorySlot, ulong> SlotId { get; }
        public global::SpacetimeDB.IxCol<PlayerInventorySlot, ulong> ProfileId { get; }
        public global::SpacetimeDB.IxCol<PlayerInventorySlot, uint> SlotIndex { get; }

        public PlayerInventorySlotIxCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.IxCol<PlayerInventorySlot, ulong>(tableName, "slot_id");
            ProfileId = new global::SpacetimeDB.IxCol<PlayerInventorySlot, ulong>(tableName, "profile_id");
            SlotIndex = new global::SpacetimeDB.IxCol<PlayerInventorySlot, uint>(tableName, "slot_index");
        }
    }
}
