// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RepeatStepDefHandle : RemoteTableHandle<EventContext, RepeatStepDef>
        {
            public override string RemoteTableName => "repeat_step_def";

            public sealed class DefIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RepeatStepDef row) => row.DefId;

                public DefIdUniqueIndex(RepeatStepDefHandle table) : base(table) { }
            }

            public readonly DefIdUniqueIndex DefId;

            internal RepeatStepDefHandle(DbConnection conn) : base(conn)
            {
                DefId = new(this);
            }

            protected override object GetPrimaryKey(RepeatStepDef row) => row.DefId;
        }

        public readonly RepeatStepDefHandle RepeatStepDef;
    }

    public sealed class RepeatStepDefCols
    {
        public global::SpacetimeDB.Col<RepeatStepDef, ulong> DefId { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, PatternType> PatternType { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, EnemyTarget> Target { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> OffsetX { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> OffsetY { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> BaseAngleOffset { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, string> TextureId { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> Lifetime { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, uint> Damage { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> RepeatInterval { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, uint> RepeatTarget { get; }
        public global::SpacetimeDB.Col<RepeatStepDef, float> NextStepDelay { get; }

        public RepeatStepDefCols(string tableName)
        {
            DefId = new global::SpacetimeDB.Col<RepeatStepDef, ulong>(tableName, "def_id");
            PatternType = new global::SpacetimeDB.Col<RepeatStepDef, PatternType>(tableName, "pattern_type");
            Target = new global::SpacetimeDB.Col<RepeatStepDef, EnemyTarget>(tableName, "target");
            OffsetX = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "offset_x");
            OffsetY = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "offset_y");
            BaseAngleOffset = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "base_angle_offset");
            TextureId = new global::SpacetimeDB.Col<RepeatStepDef, string>(tableName, "texture_id");
            Lifetime = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "lifetime");
            Damage = new global::SpacetimeDB.Col<RepeatStepDef, uint>(tableName, "damage");
            RepeatInterval = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "repeat_interval");
            RepeatTarget = new global::SpacetimeDB.Col<RepeatStepDef, uint>(tableName, "repeat_target");
            NextStepDelay = new global::SpacetimeDB.Col<RepeatStepDef, float>(tableName, "next_step_delay");
        }
    }

    public sealed class RepeatStepDefIxCols
    {
        public global::SpacetimeDB.IxCol<RepeatStepDef, ulong> DefId { get; }

        public RepeatStepDefIxCols(string tableName)
        {
            DefId = new global::SpacetimeDB.IxCol<RepeatStepDef, ulong>(tableName, "def_id");
        }
    }
}
