// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RepeatStepInstanceHandle : RemoteTableHandle<EventContext, RepeatStepInstance>
        {
            public override string RemoteTableName => "repeat_step_instance";

            public sealed class RepeatIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RepeatStepInstance row) => row.RepeatId;

                public RepeatIdUniqueIndex(RepeatStepInstanceHandle table) : base(table) { }
            }

            public readonly RepeatIdUniqueIndex RepeatId;

            internal RepeatStepInstanceHandle(DbConnection conn) : base(conn)
            {
                RepeatId = new(this);
            }

            protected override object GetPrimaryKey(RepeatStepInstance row) => row.RepeatId;
        }

        public readonly RepeatStepInstanceHandle RepeatStepInstance;
    }

    public sealed class RepeatStepInstanceCols
    {
        public global::SpacetimeDB.Col<RepeatStepInstance, ulong> RepeatId { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, PatternType> PatternType { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, EnemyTarget> Target { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> OffsetX { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> OffsetY { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> BaseAngleOffset { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, string> TextureId { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> Lifetime { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, uint> Damage { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> AngularSpeed { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> SpeedAcceleration { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> RepeatInterval { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, uint> RepeatTarget { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> AngleStep { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, float> NextStepDelay { get; }
        public global::SpacetimeDB.Col<RepeatStepInstance, uint> RepeatCount { get; }

        public RepeatStepInstanceCols(string tableName)
        {
            RepeatId = new global::SpacetimeDB.Col<RepeatStepInstance, ulong>(tableName, "repeat_id");
            PatternType = new global::SpacetimeDB.Col<RepeatStepInstance, PatternType>(tableName, "pattern_type");
            Target = new global::SpacetimeDB.Col<RepeatStepInstance, EnemyTarget>(tableName, "target");
            OffsetX = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "offset_x");
            OffsetY = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "offset_y");
            BaseAngleOffset = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "base_angle_offset");
            TextureId = new global::SpacetimeDB.Col<RepeatStepInstance, string>(tableName, "texture_id");
            Lifetime = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "lifetime");
            Damage = new global::SpacetimeDB.Col<RepeatStepInstance, uint>(tableName, "damage");
            AngularSpeed = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "angular_speed");
            SpeedAcceleration = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "speed_acceleration");
            RepeatInterval = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "repeat_interval");
            RepeatTarget = new global::SpacetimeDB.Col<RepeatStepInstance, uint>(tableName, "repeat_target");
            AngleStep = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "angle_step");
            NextStepDelay = new global::SpacetimeDB.Col<RepeatStepInstance, float>(tableName, "next_step_delay");
            RepeatCount = new global::SpacetimeDB.Col<RepeatStepInstance, uint>(tableName, "repeat_count");
        }
    }

    public sealed class RepeatStepInstanceIxCols
    {
        public global::SpacetimeDB.IxCol<RepeatStepInstance, ulong> RepeatId { get; }

        public RepeatStepInstanceIxCols(string tableName)
        {
            RepeatId = new global::SpacetimeDB.IxCol<RepeatStepInstance, ulong>(tableName, "repeat_id");
        }
    }
}
