// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SingleStepDefHandle : RemoteTableHandle<EventContext, SingleStepDef>
        {
            public override string RemoteTableName => "single_step_def";

            public sealed class DefIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SingleStepDef row) => row.DefId;

                public DefIdUniqueIndex(SingleStepDefHandle table) : base(table) { }
            }

            public readonly DefIdUniqueIndex DefId;

            internal SingleStepDefHandle(DbConnection conn) : base(conn)
            {
                DefId = new(this);
            }

            protected override object GetPrimaryKey(SingleStepDef row) => row.DefId;
        }

        public readonly SingleStepDefHandle SingleStepDef;
    }

    public sealed class SingleStepDefCols
    {
        public global::SpacetimeDB.Col<SingleStepDef, ulong> DefId { get; }
        public global::SpacetimeDB.Col<SingleStepDef, PatternType> PatternType { get; }
        public global::SpacetimeDB.Col<SingleStepDef, EnemyTarget> Target { get; }
        public global::SpacetimeDB.Col<SingleStepDef, float> OffsetX { get; }
        public global::SpacetimeDB.Col<SingleStepDef, float> OffsetY { get; }
        public global::SpacetimeDB.Col<SingleStepDef, float> BaseAngleOffset { get; }
        public global::SpacetimeDB.Col<SingleStepDef, string> TextureId { get; }
        public global::SpacetimeDB.Col<SingleStepDef, float> Lifetime { get; }
        public global::SpacetimeDB.Col<SingleStepDef, uint> Damage { get; }
        public global::SpacetimeDB.Col<SingleStepDef, float> NextStepDelay { get; }

        public SingleStepDefCols(string tableName)
        {
            DefId = new global::SpacetimeDB.Col<SingleStepDef, ulong>(tableName, "def_id");
            PatternType = new global::SpacetimeDB.Col<SingleStepDef, PatternType>(tableName, "pattern_type");
            Target = new global::SpacetimeDB.Col<SingleStepDef, EnemyTarget>(tableName, "target");
            OffsetX = new global::SpacetimeDB.Col<SingleStepDef, float>(tableName, "offset_x");
            OffsetY = new global::SpacetimeDB.Col<SingleStepDef, float>(tableName, "offset_y");
            BaseAngleOffset = new global::SpacetimeDB.Col<SingleStepDef, float>(tableName, "base_angle_offset");
            TextureId = new global::SpacetimeDB.Col<SingleStepDef, string>(tableName, "texture_id");
            Lifetime = new global::SpacetimeDB.Col<SingleStepDef, float>(tableName, "lifetime");
            Damage = new global::SpacetimeDB.Col<SingleStepDef, uint>(tableName, "damage");
            NextStepDelay = new global::SpacetimeDB.Col<SingleStepDef, float>(tableName, "next_step_delay");
        }
    }

    public sealed class SingleStepDefIxCols
    {
        public global::SpacetimeDB.IxCol<SingleStepDef, ulong> DefId { get; }

        public SingleStepDefIxCols(string tableName)
        {
            DefId = new global::SpacetimeDB.IxCol<SingleStepDef, ulong>(tableName, "def_id");
        }
    }
}
