// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TextureEntryHandle : RemoteTableHandle<EventContext, TextureEntry>
        {
            public override string RemoteTableName => "texture_entry";

            public sealed class TextureIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(TextureEntry row) => row.TextureId;

                public TextureIdUniqueIndex(TextureEntryHandle table) : base(table) { }
            }

            public readonly TextureIdUniqueIndex TextureId;

            internal TextureEntryHandle(DbConnection conn) : base(conn)
            {
                TextureId = new(this);
            }

            protected override object GetPrimaryKey(TextureEntry row) => row.TextureId;
        }

        public readonly TextureEntryHandle TextureEntry;
    }

    public sealed class TextureEntryCols
    {
        public global::SpacetimeDB.Col<TextureEntry, string> TextureId { get; }
        public global::SpacetimeDB.Col<TextureEntry, string> ResPath { get; }
        public global::SpacetimeDB.Col<TextureEntry, TextureKind> Kind { get; }

        public TextureEntryCols(string tableName)
        {
            TextureId = new global::SpacetimeDB.Col<TextureEntry, string>(tableName, "texture_id");
            ResPath = new global::SpacetimeDB.Col<TextureEntry, string>(tableName, "res_path");
            Kind = new global::SpacetimeDB.Col<TextureEntry, TextureKind>(tableName, "kind");
        }
    }

    public sealed class TextureEntryIxCols
    {
        public global::SpacetimeDB.IxCol<TextureEntry, string> TextureId { get; }

        public TextureEntryIxCols(string tableName)
        {
            TextureId = new global::SpacetimeDB.IxCol<TextureEntry, string>(tableName, "texture_id");
        }
    }
}
