// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TriangleTileHandle : RemoteTableHandle<EventContext, TriangleTile>
        {
            public override string RemoteTableName => "triangle_tile";

            public sealed class ChunkIndexIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(TriangleTile row) => row.ChunkIndex;

                public ChunkIndexIndex(TriangleTileHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class TileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TriangleTile row) => row.TileId;

                public TileIdUniqueIndex(TriangleTileHandle table) : base(table) { }
            }

            public readonly TileIdUniqueIndex TileId;

            internal TriangleTileHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                TileId = new(this);
            }

            protected override object GetPrimaryKey(TriangleTile row) => row.TileId;
        }

        public readonly TriangleTileHandle TriangleTile;
    }

    public sealed class TriangleTileCols
    {
        public global::SpacetimeDB.Col<TriangleTile, ulong> TileId { get; }
        public global::SpacetimeDB.Col<TriangleTile, int> HexQ { get; }
        public global::SpacetimeDB.Col<TriangleTile, int> HexR { get; }
        public global::SpacetimeDB.Col<TriangleTile, byte> TriIndex { get; }
        public global::SpacetimeDB.Col<TriangleTile, long> ChunkIndex { get; }
        public global::SpacetimeDB.Col<TriangleTile, string> TextureId { get; }
        public global::SpacetimeDB.Col<TriangleTile, byte> Rotation { get; }
        public global::SpacetimeDB.Col<TriangleTile, string> OverlayTextureId { get; }
        public global::SpacetimeDB.Col<TriangleTile, byte> OverlayRotation { get; }
        public global::SpacetimeDB.Col<TriangleTile, float> OverlayScale { get; }
        public global::SpacetimeDB.Col<TriangleTile, string> BiomeId { get; }
        public global::SpacetimeDB.Col<TriangleTile, ulong> RegionId { get; }

        public TriangleTileCols(string tableName)
        {
            TileId = new global::SpacetimeDB.Col<TriangleTile, ulong>(tableName, "tile_id");
            HexQ = new global::SpacetimeDB.Col<TriangleTile, int>(tableName, "hex_q");
            HexR = new global::SpacetimeDB.Col<TriangleTile, int>(tableName, "hex_r");
            TriIndex = new global::SpacetimeDB.Col<TriangleTile, byte>(tableName, "tri_index");
            ChunkIndex = new global::SpacetimeDB.Col<TriangleTile, long>(tableName, "chunk_index");
            TextureId = new global::SpacetimeDB.Col<TriangleTile, string>(tableName, "texture_id");
            Rotation = new global::SpacetimeDB.Col<TriangleTile, byte>(tableName, "rotation");
            OverlayTextureId = new global::SpacetimeDB.Col<TriangleTile, string>(tableName, "overlay_texture_id");
            OverlayRotation = new global::SpacetimeDB.Col<TriangleTile, byte>(tableName, "overlay_rotation");
            OverlayScale = new global::SpacetimeDB.Col<TriangleTile, float>(tableName, "overlay_scale");
            BiomeId = new global::SpacetimeDB.Col<TriangleTile, string>(tableName, "biome_id");
            RegionId = new global::SpacetimeDB.Col<TriangleTile, ulong>(tableName, "region_id");
        }
    }

    public sealed class TriangleTileIxCols
    {
        public global::SpacetimeDB.IxCol<TriangleTile, ulong> TileId { get; }
        public global::SpacetimeDB.IxCol<TriangleTile, long> ChunkIndex { get; }

        public TriangleTileIxCols(string tableName)
        {
            TileId = new global::SpacetimeDB.IxCol<TriangleTile, ulong>(tableName, "tile_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<TriangleTile, long>(tableName, "chunk_index");
        }
    }
}
