// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldDefHandle : RemoteTableHandle<EventContext, WorldDef>
        {
            public override string RemoteTableName => "world_def";

            public sealed class WorldIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(WorldDef row) => row.WorldId;

                public WorldIdUniqueIndex(WorldDefHandle table) : base(table) { }
            }

            public readonly WorldIdUniqueIndex WorldId;

            internal WorldDefHandle(DbConnection conn) : base(conn)
            {
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(WorldDef row) => row.WorldId;
        }

        public readonly WorldDefHandle WorldDef;
    }

    public sealed class WorldDefCols
    {
        public global::SpacetimeDB.Col<WorldDef, string> WorldId { get; }
        public global::SpacetimeDB.Col<WorldDef, string> DisplayName { get; }
        public global::SpacetimeDB.Col<WorldDef, System.Collections.Generic.List<BiomeWeight>> BiomeWeights { get; }

        public WorldDefCols(string tableName)
        {
            WorldId = new global::SpacetimeDB.Col<WorldDef, string>(tableName, "world_id");
            DisplayName = new global::SpacetimeDB.Col<WorldDef, string>(tableName, "display_name");
            BiomeWeights = new global::SpacetimeDB.Col<WorldDef, System.Collections.Generic.List<BiomeWeight>>(tableName, "biome_weights");
        }
    }

    public sealed class WorldDefIxCols
    {
        public global::SpacetimeDB.IxCol<WorldDef, string> WorldId { get; }

        public WorldDefIxCols(string tableName)
        {
            WorldId = new global::SpacetimeDB.IxCol<WorldDef, string>(tableName, "world_id");
        }
    }
}
